-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 3); do not edit.

ALTER TABLE member_tokens ADD COLUMN predecessor_id TEXT;

ALTER TABLE member_tokens ADD COLUMN lineage_root TEXT;

ALTER TABLE member_tokens ADD COLUMN lineage_started_at INTEGER;

ALTER TABLE member_tokens ADD COLUMN first_used_at INTEGER;

CREATE INDEX IF NOT EXISTS idx_member_tokens_lineage ON member_tokens (lineage_root);

CREATE UNIQUE INDEX IF NOT EXISTS idx_member_tokens_live_successor ON member_tokens (predecessor_id) WHERE revoked_at IS NULL;

UPDATE member_tokens SET lineage_root = id WHERE lineage_root IS NULL;

UPDATE member_tokens SET lineage_started_at = expires_at - 604800000 WHERE lineage_started_at IS NULL;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '3');
