-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 6); do not edit.

CREATE TABLE IF NOT EXISTS deployment_settings (
     leaf       TEXT PRIMARY KEY,
     value      TEXT NOT NULL,
     updated_at INTEGER NOT NULL,
     updated_by TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS project_capabilities (
     project_id TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     capability TEXT NOT NULL,
     enabled    INTEGER NOT NULL,
     updated_at INTEGER NOT NULL,
     updated_by TEXT NOT NULL,
     PRIMARY KEY (project_id, capability));

CREATE TABLE IF NOT EXISTS step_up_authorities (
     id          TEXT PRIMARY KEY,
     key_hash    TEXT NOT NULL,
     purpose     TEXT NOT NULL,
     created_at  INTEGER NOT NULL,
     expires_at  INTEGER NOT NULL,
     used_at     INTEGER,
     used_by     TEXT,
     revoked_at  INTEGER);

CREATE UNIQUE INDEX IF NOT EXISTS idx_step_up_authorities_hash ON step_up_authorities (key_hash);

CREATE TABLE IF NOT EXISTS deployment_secrets (
     name        TEXT PRIMARY KEY,
     ciphertext  TEXT NOT NULL,
     iv          TEXT NOT NULL,
     key_version INTEGER NOT NULL,
     updated_at  INTEGER NOT NULL,
     updated_by  TEXT NOT NULL);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '6');
