-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 7); do not edit.

CREATE TABLE IF NOT EXISTS agents (
     id                 TEXT PRIMARY KEY,
     name               TEXT NOT NULL,
     provider           TEXT,
     model              TEXT,
     system_prompt_hash TEXT,
     system_prompt      TEXT,
     config             TEXT,
     source             TEXT NOT NULL DEFAULT 'built-in',
     max_turns          INTEGER,
     timeout_seconds    INTEGER,
     tool_access        TEXT,
     enabled            INTEGER NOT NULL DEFAULT 1,
     created_at         INTEGER NOT NULL,
     updated_at         INTEGER);

CREATE TABLE IF NOT EXISTS agent_tasks (
     id             TEXT PRIMARY KEY,
     agent_id       TEXT NOT NULL REFERENCES agents(id),
     source         TEXT NOT NULL DEFAULT 'built-in',
     display_name   TEXT,
     description    TEXT,
     prompt         TEXT NOT NULL,
     is_default     INTEGER NOT NULL DEFAULT 0,
     tool_overrides TEXT,
     model          TEXT,
     config         TEXT,
     created_at     INTEGER NOT NULL,
     updated_at     INTEGER);

CREATE TABLE IF NOT EXISTS agent_runs (
     project_id         TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id                 TEXT NOT NULL,
     agent_id           TEXT NOT NULL REFERENCES agents(id),
     task               TEXT,
     instruction        TEXT,
     status             TEXT NOT NULL DEFAULT 'pending',
     harness            TEXT,
     provider           TEXT,
     model              TEXT,
     session_ref        TEXT,
     resumable          INTEGER NOT NULL DEFAULT 0,
     resume_status      TEXT,
     resume_mode        TEXT,
     resumed_at         INTEGER,
     resume_attempts    INTEGER NOT NULL DEFAULT 0,
     checkpoints        TEXT,
     usage_data         TEXT,
     started_at         INTEGER,
     completed_at       INTEGER,
     tokens_used        INTEGER,
     cost_usd           REAL,
     actual_cost_usd    REAL,
     estimated_cost_usd REAL,
     cost_source        TEXT,
     cost_data          TEXT,
     actions_taken      TEXT,
     error              TEXT,
     dry_run            INTEGER NOT NULL DEFAULT 0,
     reasoning_level    TEXT,
     execution_overrides TEXT,
     run_context        TEXT,
     PRIMARY KEY (project_id, id));

CREATE INDEX IF NOT EXISTS idx_agent_runs_task ON agent_runs (project_id, task, status, started_at);

CREATE TABLE IF NOT EXISTS agent_run_events (
     project_id  TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id          TEXT NOT NULL,
     run_id      TEXT NOT NULL,
     phase_name  TEXT,
     event_type  TEXT NOT NULL,
     tool_name   TEXT,
     outcome     TEXT,
     duration_ms INTEGER,
     payload     TEXT,
     recorded_at INTEGER NOT NULL,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, run_id) REFERENCES agent_runs(project_id, id) ON DELETE CASCADE);

CREATE INDEX IF NOT EXISTS idx_agent_run_events_run ON agent_run_events (project_id, run_id, recorded_at);

CREATE TABLE IF NOT EXISTS agent_run_write_intents (
     project_id         TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id                 TEXT NOT NULL,
     run_id             TEXT NOT NULL,
     phase_id           TEXT,
     tool_name          TEXT NOT NULL,
     tool_input         TEXT NOT NULL,
     synthetic_output   TEXT NOT NULL,
     stub_id            TEXT,
     classifier_verdict TEXT,
     classifier_reason  TEXT,
     recorded_at        INTEGER NOT NULL,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, run_id) REFERENCES agent_runs(project_id, id) ON DELETE CASCADE);

CREATE INDEX IF NOT EXISTS idx_agent_run_write_intents_run ON agent_run_write_intents (project_id, run_id, recorded_at);

CREATE TABLE IF NOT EXISTS agent_turns (
     project_id          TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id                  TEXT NOT NULL,
     run_id              TEXT NOT NULL,
     agent_id            TEXT NOT NULL REFERENCES agents(id),
     turn_number         INTEGER NOT NULL,
     tool_name           TEXT NOT NULL,
     tool_input          TEXT,
     tool_output_summary TEXT,
     started_at          INTEGER,
     completed_at        INTEGER,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, run_id) REFERENCES agent_runs(project_id, id));

CREATE INDEX IF NOT EXISTS idx_agent_turns_run ON agent_turns (project_id, run_id, turn_number);

CREATE TABLE IF NOT EXISTS agent_reports (
     project_id TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id         TEXT NOT NULL,
     run_id     TEXT NOT NULL,
     agent_id   TEXT NOT NULL REFERENCES agents(id),
     action     TEXT NOT NULL,
     summary    TEXT NOT NULL,
     details    TEXT,
     created_at INTEGER NOT NULL,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, run_id) REFERENCES agent_runs(project_id, id));

CREATE INDEX IF NOT EXISTS idx_agent_reports_run ON agent_reports (project_id, run_id, created_at);

CREATE TABLE IF NOT EXISTS agent_state (
     project_id TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     agent_id   TEXT NOT NULL REFERENCES agents(id),
     key        TEXT NOT NULL,
     value      TEXT NOT NULL,
     updated_at INTEGER NOT NULL,
     PRIMARY KEY (project_id, agent_id, key));

CREATE TABLE IF NOT EXISTS spores (
     project_id       TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id               TEXT NOT NULL,
     agent_id         TEXT NOT NULL REFERENCES agents(id),
     session_id       TEXT,
     prompt_id        TEXT,
     observation_type TEXT NOT NULL,
     status           TEXT NOT NULL DEFAULT 'active',
     content          TEXT NOT NULL,
     context          TEXT,
     importance       INTEGER NOT NULL DEFAULT 5,
     file_path        TEXT,
     tags             TEXT,
     content_hash     TEXT,
     properties       TEXT,
     created_at       INTEGER NOT NULL,
     updated_at       INTEGER,
     embedded         INTEGER NOT NULL DEFAULT 0,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, session_id) REFERENCES sessions(project_id, session_id));

CREATE INDEX IF NOT EXISTS idx_spores_status ON spores (project_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_spores_type ON spores (project_id, observation_type, created_at);

CREATE INDEX IF NOT EXISTS idx_spores_unembedded ON spores (project_id, created_at) WHERE embedded = 0;

CREATE TABLE IF NOT EXISTS resolution_events (
     project_id   TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id           TEXT NOT NULL,
     agent_id     TEXT NOT NULL REFERENCES agents(id),
     spore_id     TEXT NOT NULL,
     action       TEXT NOT NULL,
     new_spore_id TEXT,
     reason       TEXT,
     session_id   TEXT,
     created_at   INTEGER NOT NULL,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, spore_id) REFERENCES spores(project_id, id));

CREATE INDEX IF NOT EXISTS idx_resolution_events_spore ON resolution_events (project_id, spore_id, created_at);

CREATE TABLE IF NOT EXISTS skill_candidates (
     project_id            TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id                    TEXT NOT NULL,
     agent_id              TEXT NOT NULL REFERENCES agents(id),
     topic                 TEXT NOT NULL,
     rationale             TEXT NOT NULL,
     confidence            REAL NOT NULL DEFAULT 0.0,
     status                TEXT NOT NULL DEFAULT 'identified',
     source_ids            TEXT NOT NULL DEFAULT '[]',
     skill_id              TEXT,
     supersedes            TEXT,
     evidence_bundle_id    TEXT,
     quality_score         REAL,
     quality_failures      TEXT NOT NULL DEFAULT '[]',
     coverage_matches      TEXT NOT NULL DEFAULT '[]',
     last_reconciled_at    INTEGER,
     reconciliation_reason TEXT,
     created_at            INTEGER NOT NULL,
     updated_at            INTEGER NOT NULL,
     approved_at           INTEGER,
     PRIMARY KEY (project_id, id));

CREATE INDEX IF NOT EXISTS idx_skill_candidates_status ON skill_candidates (project_id, status, created_at);

CREATE TABLE IF NOT EXISTS skill_records (
     project_id   TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id           TEXT NOT NULL,
     agent_id     TEXT NOT NULL REFERENCES agents(id),
     name         TEXT NOT NULL,
     display_name TEXT NOT NULL,
     description  TEXT NOT NULL,
     status       TEXT NOT NULL DEFAULT 'active',
     embedded     INTEGER NOT NULL DEFAULT 0,
     generation   INTEGER NOT NULL DEFAULT 1,
     candidate_id TEXT,
     source_ids   TEXT NOT NULL DEFAULT '[]',
     path         TEXT NOT NULL,
     usage_count  INTEGER NOT NULL DEFAULT 0,
     last_used_at INTEGER,
     created_at   INTEGER NOT NULL,
     updated_at   INTEGER NOT NULL,
     properties   TEXT NOT NULL DEFAULT '{}',
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, candidate_id) REFERENCES skill_candidates(project_id, id));

CREATE UNIQUE INDEX IF NOT EXISTS idx_skill_records_name ON skill_records (project_id, name);

CREATE TABLE IF NOT EXISTS skill_lineage (
     project_id       TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id               TEXT NOT NULL,
     skill_id         TEXT NOT NULL,
     generation       INTEGER NOT NULL,
     action           TEXT NOT NULL,
     rationale        TEXT NOT NULL,
     source_ids_added TEXT NOT NULL DEFAULT '[]',
     content_snapshot TEXT NOT NULL,
     created_at       INTEGER NOT NULL,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, skill_id) REFERENCES skill_records(project_id, id));

CREATE INDEX IF NOT EXISTS idx_skill_lineage_skill ON skill_lineage (project_id, skill_id, generation);

CREATE TABLE IF NOT EXISTS skill_usage (
     project_id  TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id          TEXT NOT NULL,
     skill_id    TEXT NOT NULL,
     session_id  TEXT NOT NULL,
     detected_at INTEGER NOT NULL,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, skill_id) REFERENCES skill_records(project_id, id),
     FOREIGN KEY (project_id, session_id) REFERENCES sessions(project_id, session_id));

CREATE INDEX IF NOT EXISTS idx_skill_usage_skill ON skill_usage (project_id, skill_id, detected_at);

CREATE TABLE IF NOT EXISTS digest_extracts (
     project_id     TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id             TEXT NOT NULL,
     agent_id       TEXT NOT NULL REFERENCES agents(id),
     tier           INTEGER NOT NULL,
     content        TEXT NOT NULL,
     substrate_hash TEXT,
     generated_at   INTEGER NOT NULL,
     PRIMARY KEY (project_id, id));

CREATE INDEX IF NOT EXISTS idx_digest_extracts_tier ON digest_extracts (project_id, tier, generated_at);

CREATE TABLE IF NOT EXISTS digest_extract_revisions (
     project_id         TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id                 TEXT NOT NULL,
     agent_id           TEXT NOT NULL,
     tier               INTEGER NOT NULL,
     content            TEXT NOT NULL,
     metadata           TEXT,
     run_id             TEXT,
     parent_revision_id TEXT,
     created_at         INTEGER NOT NULL,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, run_id) REFERENCES agent_runs(project_id, id) ON DELETE SET NULL,
     FOREIGN KEY (project_id, parent_revision_id) REFERENCES digest_extract_revisions(project_id, id));

CREATE INDEX IF NOT EXISTS idx_digest_extract_revisions_tier ON digest_extract_revisions (project_id, tier, created_at);

CREATE TABLE IF NOT EXISTS cortex_instructions (
     project_id    TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id            TEXT NOT NULL,
     agent_id      TEXT NOT NULL,
     content       TEXT NOT NULL,
     input_hash    TEXT NOT NULL,
     source_run_id TEXT,
     generated_at  INTEGER NOT NULL,
     PRIMARY KEY (project_id, id));

CREATE TABLE IF NOT EXISTS knowledge_git_provenance (
     project_id               TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id                       TEXT NOT NULL,
     identity_key             TEXT NOT NULL,
     session_id               TEXT,
     prompt_id                TEXT,
     capture_point            TEXT NOT NULL,
     captured_at              INTEGER NOT NULL,
     project_root             TEXT,
     branch                   TEXT,
     head_sha                 TEXT,
     upstream_ref             TEXT,
     upstream_sha             TEXT,
     production_ref           TEXT,
     production_sha           TEXT,
     is_dirty                 INTEGER NOT NULL DEFAULT 0,
     staged_count             INTEGER NOT NULL DEFAULT 0,
     unstaged_count           INTEGER NOT NULL DEFAULT 0,
     untracked_count          INTEGER NOT NULL DEFAULT 0,
     changed_paths_json       TEXT,
     tracked_blob_hashes_json TEXT,
     patch_ids_json           TEXT,
     status_hash              TEXT NOT NULL,
     evidence_json            TEXT,
     error                    TEXT,
     created_at               INTEGER NOT NULL,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, session_id) REFERENCES sessions(project_id, session_id));

CREATE UNIQUE INDEX IF NOT EXISTS idx_knowledge_git_provenance_identity ON knowledge_git_provenance (project_id, identity_key);

CREATE TABLE IF NOT EXISTS knowledge_release_state (
     project_id        TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     id                TEXT NOT NULL,
     identity_key      TEXT NOT NULL,
     namespace         TEXT NOT NULL,
     record_id         TEXT NOT NULL,
     source_session_id TEXT,
     source_prompt_id  TEXT,
     state             TEXT NOT NULL,
     confidence        TEXT NOT NULL,
     basis_kind        TEXT,
     basis_ref         TEXT,
     basis_sha         TEXT,
     release_pr_number INTEGER,
     reason            TEXT,
     evidence_json     TEXT,
     checked_at        INTEGER NOT NULL,
     created_at        INTEGER NOT NULL,
     updated_at        INTEGER,
     PRIMARY KEY (project_id, id),
     FOREIGN KEY (project_id, source_session_id) REFERENCES sessions(project_id, session_id));

CREATE UNIQUE INDEX IF NOT EXISTS idx_knowledge_release_state_identity ON knowledge_release_state (project_id, identity_key);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '7');
