-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 8); do not edit.

ALTER TABLE members ADD COLUMN github_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_members_github_id ON members (github_id);

CREATE TABLE IF NOT EXISTS identity_link_authorities (
     id          TEXT PRIMARY KEY,
     key_hash    TEXT NOT NULL,
     member_id   TEXT NOT NULL REFERENCES members(id),
     created_at  INTEGER NOT NULL,
     expires_at  INTEGER NOT NULL,
     used_at     INTEGER,
     used_by     TEXT,
     revoked_at  INTEGER);

CREATE UNIQUE INDEX IF NOT EXISTS idx_identity_link_authorities_hash ON identity_link_authorities (key_hash);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '8');
