-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 11); do not edit.

INSERT OR IGNORE INTO agents (id, name, source, enabled, created_at) VALUES ('user', 'User (MCP)', 'built-in', 1, 0);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '11');
