-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 12); do not edit.

ALTER TABLE sessions ADD COLUMN title TEXT;

ALTER TABLE sessions ADD COLUMN summary TEXT;

ALTER TABLE sessions ADD COLUMN titled_at INTEGER;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '12');
