-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 13); do not edit.

CREATE TABLE IF NOT EXISTS backups (
     id             TEXT PRIMARY KEY,
     key            TEXT NOT NULL,
     created_at     INTEGER NOT NULL,
     size_bytes     INTEGER NOT NULL,
     counts_json    TEXT NOT NULL,
     schema_version INTEGER NOT NULL,
     producer       TEXT NOT NULL,
     pinned         INTEGER NOT NULL DEFAULT 0);

CREATE INDEX IF NOT EXISTS idx_backups_created ON backups (created_at, id);

INSERT OR IGNORE INTO schema_meta (key, value) VALUES ('deployment_id', lower(hex(randomblob(16))));

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '13');
