-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 16); do not edit.

ALTER TABLE agent_runs ADD COLUMN queued_at INTEGER;

ALTER TABLE agent_runs ADD COLUMN held_by TEXT;

ALTER TABLE agent_runs ADD COLUMN dispatch_spec TEXT;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '16');
