-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 17); do not edit.

CREATE TABLE IF NOT EXISTS spore_injections (
     project_id  TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     session_id  TEXT NOT NULL,
     prompt_id   TEXT NOT NULL,
     prompt_hash TEXT NOT NULL,
     spore_ids   TEXT NOT NULL,
     created_at  INTEGER NOT NULL,
     PRIMARY KEY (project_id, session_id, prompt_hash));

CREATE INDEX IF NOT EXISTS idx_spore_injections_session ON spore_injections (project_id, session_id, created_at);

CREATE INDEX IF NOT EXISTS idx_spore_injections_prompt ON spore_injections (project_id, session_id, prompt_id);

CREATE INDEX IF NOT EXISTS idx_resolution_events_successor ON resolution_events (project_id, new_spore_id, created_at);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '17');
