-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 18); do not edit.

CREATE TABLE IF NOT EXISTS session_injections (
     project_id TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     session_id TEXT NOT NULL,
     kind       TEXT NOT NULL,
     created_at INTEGER NOT NULL,
     PRIMARY KEY (project_id, session_id, kind));

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '18');
