-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 25); do not edit.

ALTER TABLE external_grants ADD COLUMN expires_at INTEGER;

UPDATE external_grants SET expires_at = created_at + 7776000000 WHERE expires_at IS NULL;

ALTER TABLE spores ADD COLUMN provenance_kind TEXT;

ALTER TABLE spores ADD COLUMN provenance_ref TEXT;

ALTER TABLE resolution_events ADD COLUMN provenance_kind TEXT;

ALTER TABLE resolution_events ADD COLUMN provenance_ref TEXT;

CREATE INDEX IF NOT EXISTS idx_external_grants_expiry ON external_grants (expires_at) WHERE revoked_at IS NULL;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '25');
