-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 26); do not edit.

ALTER TABLE members ADD COLUMN role TEXT NOT NULL DEFAULT 'admin';

ALTER TABLE enrollment_authorities ADD COLUMN role TEXT NOT NULL DEFAULT 'admin';

ALTER TABLE enrollment_authorities ADD COLUMN project_id TEXT CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id);

CREATE INDEX IF NOT EXISTS idx_enrollment_authorities_finished ON enrollment_authorities (expires_at);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '26');
