-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 27); do not edit.

ALTER TABLE spores ADD COLUMN agent_line TEXT;

CREATE INDEX IF NOT EXISTS idx_spores_underived ON spores (project_id, created_at) WHERE agent_line IS NULL;

ALTER TABLE spore_injections ADD COLUMN plan_ids TEXT;

CREATE TABLE IF NOT EXISTS project_remotes (
     remote        TEXT PRIMARY KEY,
     project_id    TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     first_seen_at INTEGER NOT NULL);

CREATE INDEX IF NOT EXISTS idx_project_remotes_project ON project_remotes (project_id);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '27');
