-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 28); do not edit.

ALTER TABLE transcripts ADD COLUMN parsed_offset INTEGER NOT NULL DEFAULT 0;

ALTER TABLE transcripts ADD COLUMN parsed_at INTEGER;

ALTER TABLE transcripts ADD COLUMN parser_version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE transcripts ADD COLUMN parse_error TEXT;

ALTER TABLE transcripts ADD COLUMN parse_failed_at INTEGER;

ALTER TABLE transcripts ADD COLUMN fidelity TEXT;

ALTER TABLE transcripts ADD COLUMN role TEXT NOT NULL DEFAULT 'primary';

ALTER TABLE transcripts ADD COLUMN head_hash TEXT;

CREATE INDEX IF NOT EXISTS idx_transcripts_unparsed ON transcripts (project_id, last_received_at) WHERE parsed_offset < size AND parse_error IS NULL;

ALTER TABLE plans ADD COLUMN source TEXT;

CREATE TABLE IF NOT EXISTS session_tombstones (
     project_id TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')),
     session_id TEXT NOT NULL,
     reason     TEXT,
     created_at INTEGER NOT NULL,
     created_by TEXT NOT NULL,
     PRIMARY KEY (project_id, session_id));

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '28');
