-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 29); do not edit.

INSERT INTO agents (id, name, source, enabled, created_at, updated_at)
     SELECT id, COALESCE(label, 'External agent'), 'grant', 1, created_at, created_at
       FROM external_grants
      WHERE id NOT IN (SELECT id FROM agents);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '29');
