-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 31); do not edit.

ALTER TABLE prompt_batches ADD COLUMN processed INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_prompt_batches_unprocessed ON prompt_batches (project_id, processed, created_at, prompt_id);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '31');
