-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 32); do not edit.

ALTER TABLE transcripts ADD COLUMN imported_at INTEGER;

CREATE INDEX IF NOT EXISTS idx_transcripts_backlog ON transcripts (imported_at, last_received_at, transcript_id) WHERE parsed_offset < size;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '32');
