-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 33); do not edit.

ALTER TABLE agent_runs ADD COLUMN leased_by TEXT REFERENCES member_credentials(id);

ALTER TABLE agent_runs ADD COLUMN lease_expires_at INTEGER;

CREATE INDEX IF NOT EXISTS idx_agent_runs_claimable ON agent_runs (status, queued_at);

CREATE INDEX IF NOT EXISTS idx_agent_runs_lease ON agent_runs (leased_by, lease_expires_at);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '33');
