-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 34); do not edit.

CREATE INDEX IF NOT EXISTS idx_sessions_occurred ON sessions (project_id, COALESCE(started_at, first_received_at), session_id);

DROP INDEX IF EXISTS idx_sessions_recent;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '34');
