-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 37); do not edit.

CREATE TABLE IF NOT EXISTS backup_restore_progress (
    table_name TEXT PRIMARY KEY,
    artifact_hash TEXT NOT NULL,
    next_row INTEGER NOT NULL CHECK (next_row >= 0),
    verified INTEGER NOT NULL DEFAULT 1 CONSTRAINT backup_restore_rows_match CHECK (verified = 1)
  );

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '37');
