-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 38); do not edit.

CREATE INDEX IF NOT EXISTS idx_tool_calls_input_blob_key ON tool_calls (project_id, input_blob_key) WHERE input_blob_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tool_calls_output_blob_key ON tool_calls (project_id, output_blob_key) WHERE output_blob_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_events_blob_key ON events (project_id, blob_key) WHERE blob_key IS NOT NULL;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '38');
