-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 39); do not edit.

ALTER TABLE sessions ADD COLUMN ended_by TEXT;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '39');
