-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 42); do not edit.

ALTER TABLE blobs ADD COLUMN generation TEXT CHECK (generation IS NULL OR (length(generation) = 36 AND generation NOT GLOB '*[^0-9a-f-]*'));

CREATE TABLE IF NOT EXISTS object_releases (
     physical   TEXT PRIMARY KEY,
     kind       TEXT NOT NULL CHECK (kind IN ('blob', 'upload', 'backup')),
     created_at INTEGER NOT NULL);

CREATE INDEX IF NOT EXISTS idx_object_releases_created ON object_releases (created_at);

CREATE INDEX IF NOT EXISTS idx_blob_reservations_expiry ON blob_reservations (expires_at);

CREATE TABLE IF NOT EXISTS blob_release_candidates (
     project_id TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')),
     key        TEXT NOT NULL,
     created_at INTEGER NOT NULL,
     PRIMARY KEY (project_id, key));

CREATE TABLE IF NOT EXISTS backup_release_candidates (
     id         TEXT PRIMARY KEY,
     created_at INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS recovery_holds (
     token          TEXT PRIMARY KEY,
     acquired_at    INTEGER NOT NULL,
     released_at    INTEGER,
     release_reason TEXT);

CREATE UNIQUE INDEX IF NOT EXISTS idx_recovery_holds_open ON recovery_holds ((released_at IS NULL)) WHERE released_at IS NULL;

CREATE TABLE IF NOT EXISTS restore_reference_guard (missing TEXT NOT NULL CHECK (missing IS NULL));

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '42');
