-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 43); do not edit.

ALTER TABLE recovery_holds ADD COLUMN holder TEXT NOT NULL DEFAULT 'producer' CHECK (holder IN ('producer', 'operator'));

ALTER TABLE recovery_holds ADD COLUMN released_by TEXT CHECK (released_by IS NULL OR released_by IN ('producer', 'operator'));

DROP INDEX IF EXISTS idx_recovery_holds_open;

CREATE UNIQUE INDEX IF NOT EXISTS idx_recovery_holds_open_holder ON recovery_holds (holder) WHERE released_at IS NULL;

CREATE TRIGGER IF NOT EXISTS recovery_holds_operator_inserted_open BEFORE INSERT ON recovery_holds
     WHEN NEW.holder IS 'operator' AND (NEW.released_at IS NOT NULL OR NEW.released_by IS NOT NULL OR NEW.release_reason IS NOT NULL)
     BEGIN SELECT RAISE(ABORT, 'an operator recovery hold is inserted open'); END;

CREATE TRIGGER IF NOT EXISTS recovery_holds_released_by_holder BEFORE INSERT ON recovery_holds
     WHEN NEW.released_by IS NOT NULL AND NEW.released_by IS NOT NEW.holder
     BEGIN SELECT RAISE(ABORT, 'a recovery hold is released by its own holder'); END;

CREATE TRIGGER IF NOT EXISTS recovery_holds_operator_transition BEFORE UPDATE ON recovery_holds
     WHEN OLD.holder IS 'operator' AND NOT (
       OLD.released_at IS NULL AND OLD.released_by IS NULL AND OLD.release_reason IS NULL
       AND NEW.released_at IS NOT NULL AND NEW.released_by IS 'operator'
       AND (NEW.release_reason IS 'complete' OR NEW.release_reason IS 'abandoned')
       AND NEW.token IS OLD.token AND NEW.acquired_at IS OLD.acquired_at AND NEW.holder IS OLD.holder)
     BEGIN SELECT RAISE(ABORT, 'an operator recovery hold changes only through its own release'); END;

CREATE TRIGGER IF NOT EXISTS recovery_holds_producer_transition BEFORE UPDATE ON recovery_holds
     WHEN OLD.holder IS 'producer' AND (NEW.holder IS NOT 'producer' OR NEW.released_by IS 'operator')
     BEGIN SELECT RAISE(ABORT, 'a producer recovery hold is never an operator hold'); END;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '43');
