-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 47); do not edit.

ALTER TABLE sessions ADD COLUMN titling_attempts INTEGER NOT NULL DEFAULT 0;

CREATE TRIGGER IF NOT EXISTS agent_runs_title_attempt AFTER UPDATE OF status ON agent_runs
     WHEN old.status = 'queued' AND new.status = 'running' AND new.task = 'title-summary'
       AND json_valid(new.run_context) AND json_extract(new.run_context, '$.mode') = 'claim' BEGIN
    UPDATE sessions SET titling_attempts = titling_attempts + 1
     WHERE project_id = new.project_id AND session_id = json_extract(new.run_context, '$.session_id'); END;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '47');
