-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 47); do not edit.

ALTER TABLE sessions ADD COLUMN titling_attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE agent_runs ADD COLUMN attempt_counted INTEGER;

CREATE TRIGGER IF NOT EXISTS agent_runs_title_attempt AFTER UPDATE OF status ON agent_runs
     WHEN old.status = 'queued' AND new.status = 'running' AND new.attempt_counted IS NULL AND new.task = 'title-summary'
       AND json_valid(new.run_context) AND json_extract(new.run_context, '$.mode') = 'claim' BEGIN
    UPDATE sessions SET titling_attempts = titling_attempts + 1
     WHERE project_id = new.project_id AND session_id = json_extract(new.run_context, '$.session_id')
       AND NOT EXISTS (SELECT 1 FROM agent_runs p WHERE p.project_id = new.project_id
         AND p.id = json_extract(new.run_context, '$.replaces') AND p.attempt_counted = 1);
    UPDATE agent_runs SET attempt_counted = 1 WHERE project_id = new.project_id AND id = new.id; END;

CREATE INDEX IF NOT EXISTS idx_sessions_untitled_ended ON sessions (ended_at) WHERE ended_at IS NOT NULL AND title IS NULL;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '47');
