-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 50); do not edit.

CREATE TABLE IF NOT EXISTS embedding_hubness_members (
    project_id TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')), model_key TEXT NOT NULL, id TEXT NOT NULL,
    state INTEGER NOT NULL DEFAULT 0 CHECK (state IN (0, 1, 2)),
    n INTEGER NOT NULL DEFAULT 0, mean REAL NOT NULL DEFAULT 0, m2 REAL NOT NULL DEFAULT 0,
    vector TEXT NOT NULL,
    PRIMARY KEY(project_id, model_key, id));

CREATE INDEX IF NOT EXISTS idx_embedding_hubness_members_state ON embedding_hubness_members(project_id, model_key, state, id);

ALTER TABLE embedding_cursors ADD COLUMN hubness_token TEXT;

UPDATE embedding_cursors SET hubness_count = NULL, hubness_target_count = NULL, hubness_cursor = NULL;

DELETE FROM embedding_hubness_work;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '50');
