-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 52); do not edit.

ALTER TABLE member_credentials ADD COLUMN rotates INTEGER NOT NULL DEFAULT 1;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '52');
