-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 55); do not edit.

CREATE TABLE IF NOT EXISTS machine_settings (
     machine_id TEXT NOT NULL REFERENCES machine_claims(machine_id),
     leaf       TEXT NOT NULL,
     value      TEXT NOT NULL,
     updated_at INTEGER NOT NULL,
     updated_by TEXT NOT NULL,
     PRIMARY KEY (machine_id, leaf));

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '55');
