-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 56); do not edit.

ALTER TABLE transcripts ADD COLUMN parse_segment_lines INTEGER;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '56');
