-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 58); do not edit.

CREATE TABLE IF NOT EXISTS run_reads (
     project_id  TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     run_id      TEXT NOT NULL,
     session_id  TEXT NOT NULL,
     token_id    TEXT NOT NULL,
     received_at INTEGER NOT NULL,
     PRIMARY KEY (project_id, run_id, session_id),
     FOREIGN KEY (project_id, run_id) REFERENCES agent_runs(project_id, id) ON DELETE CASCADE,
     FOREIGN KEY (project_id, session_id) REFERENCES sessions(project_id, session_id));

CREATE INDEX IF NOT EXISTS idx_run_reads_session ON run_reads (project_id, session_id, received_at);

CREATE INDEX IF NOT EXISTS idx_spores_session ON spores (project_id, session_id, created_at);

CREATE INDEX IF NOT EXISTS idx_agent_runs_session ON agent_runs (project_id, CASE WHEN json_valid(run_context) THEN json_extract(run_context, '$.session_id') END);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '58');
