-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 59); do not edit.

ALTER TABLE machine_claims ADD COLUMN label TEXT;

CREATE INDEX IF NOT EXISTS idx_machine_claims_member ON machine_claims (member_id);

UPDATE machine_claims SET label = (
     SELECT c.runtime_label FROM member_credentials c
      WHERE c.machine_id = machine_claims.machine_id AND c.runtime_label IS NOT NULL
      ORDER BY (c.revoked_at IS NULL) DESC, c.issued_at DESC, c.id DESC LIMIT 1)
    WHERE label IS NULL;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '59');
