-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 61); do not edit.

CREATE TABLE IF NOT EXISTS uncaptured_roots (
     machine_id    TEXT NOT NULL,
     root_key      TEXT NOT NULL,
     member_id     TEXT NOT NULL REFERENCES members(id),
     label         TEXT NOT NULL,
     remote        TEXT,
     reason        TEXT NOT NULL,
     misses        INTEGER NOT NULL DEFAULT 1,
     held          TEXT NOT NULL DEFAULT 'held',
     first_seen_at INTEGER NOT NULL,
     last_seen_at  INTEGER NOT NULL,
     PRIMARY KEY (machine_id, root_key));

CREATE INDEX IF NOT EXISTS idx_uncaptured_roots_member ON uncaptured_roots (member_id, last_seen_at);

CREATE INDEX IF NOT EXISTS idx_uncaptured_roots_seen ON uncaptured_roots (last_seen_at);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '61');
