-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 62); do not edit.

ALTER TABLE agent_runs ADD COLUMN error_code TEXT;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '62');
