-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 63); do not edit.

CREATE TABLE IF NOT EXISTS deployment_setting_resets (
     leaf TEXT PRIMARY KEY,
     reset_at INTEGER NOT NULL,
     reset_by TEXT NOT NULL);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '63');
