-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 65); do not edit.

CREATE TABLE IF NOT EXISTS worker_model_catalogs (
     machine_id  TEXT NOT NULL,
     harness     TEXT NOT NULL,
     catalog     TEXT NOT NULL,
     resolutions TEXT NOT NULL,
     fetched_at  INTEGER NOT NULL,
     received_at INTEGER NOT NULL,
     PRIMARY KEY (machine_id, harness));

CREATE INDEX IF NOT EXISTS idx_worker_model_catalogs_received ON worker_model_catalogs (received_at);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '65');
