-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 66); do not edit.

ALTER TABLE agent_reports ADD COLUMN audit TEXT;

CREATE TABLE IF NOT EXISTS agent_run_attempts (
     project_id     TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     run_id         TEXT NOT NULL,
     attempt_id     TEXT NOT NULL,
     leased_by      TEXT NOT NULL,
     machine_id     TEXT,
     claimed_at     INTEGER NOT NULL,
     steps_total    INTEGER,
     steps_overflow INTEGER,
     unrecognized   TEXT,
     PRIMARY KEY (project_id, run_id, attempt_id),
     FOREIGN KEY (project_id, run_id) REFERENCES agent_runs(project_id, id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS agent_run_steps (
     project_id  TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')) REFERENCES projects(project_id),
     run_id      TEXT NOT NULL,
     attempt_id  TEXT NOT NULL,
     seq         INTEGER NOT NULL CHECK (seq >= 0),
     call_id     TEXT,
     kind        TEXT NOT NULL CHECK (kind IN ('read', 'search', 'edit', 'command', 'fetch', 'myco', 'tool')),
     tool        TEXT NOT NULL,
     target      TEXT,
     outcome     TEXT NOT NULL CHECK (outcome IN ('ok', 'error', 'refused', 'unfinished')),
     exit_code   INTEGER,
     started_at  INTEGER NOT NULL,
     ended_at    INTEGER,
     received_at INTEGER NOT NULL,
     PRIMARY KEY (project_id, run_id, attempt_id, seq),
     FOREIGN KEY (project_id, run_id, attempt_id) REFERENCES agent_run_attempts(project_id, run_id, attempt_id) ON DELETE CASCADE);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '66');
