-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 69); do not edit.

ALTER TABLE machine_claims ADD COLUMN settings_revision INTEGER NOT NULL DEFAULT 0;

ALTER TABLE machine_claims ADD COLUMN settings_cached_revision TEXT;

ALTER TABLE machine_claims ADD COLUMN settings_cached_values TEXT;

ALTER TABLE machine_claims ADD COLUMN settings_report_order INTEGER NOT NULL DEFAULT -1;

ALTER TABLE machine_claims ADD COLUMN settings_contract_supported INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS machine_settings_snapshots (
     machine_id TEXT NOT NULL REFERENCES machine_claims(machine_id) ON DELETE CASCADE,
     revision TEXT NOT NULL,
     leaves TEXT NOT NULL,
     sent_order INTEGER NOT NULL,
     PRIMARY KEY (machine_id, revision));

CREATE TRIGGER IF NOT EXISTS machine_settings_insert_revision AFTER INSERT ON machine_settings BEGIN
     UPDATE machine_claims SET settings_revision = settings_revision + 1 WHERE machine_id = NEW.machine_id; END;

CREATE TRIGGER IF NOT EXISTS machine_settings_update_revision AFTER UPDATE ON machine_settings BEGIN
     UPDATE machine_claims SET settings_revision = settings_revision + 1 WHERE machine_id = NEW.machine_id; END;

CREATE TRIGGER IF NOT EXISTS machine_settings_delete_revision AFTER DELETE ON machine_settings BEGIN
     UPDATE machine_claims SET settings_revision = settings_revision + 1 WHERE machine_id = OLD.machine_id; END;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '69');
