-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 72); do not edit.

CREATE INDEX IF NOT EXISTS idx_machine_claims_claimed ON machine_claims (claimed_at DESC, machine_id ASC);

CREATE INDEX IF NOT EXISTS idx_member_credentials_machine ON member_credentials (machine_id, issued_at DESC, id DESC);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '72');
