-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 74); do not edit.

CREATE TABLE IF NOT EXISTS recovery_forget_commands (
    id TEXT PRIMARY KEY, actor_id TEXT NOT NULL REFERENCES members(id), created_at INTEGER NOT NULL,
    attempt INTEGER, forgettable_at INTEGER);

CREATE INDEX IF NOT EXISTS idx_recovery_forget_commands_actor ON recovery_forget_commands(actor_id);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '74');
