-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 76); do not edit.

CREATE INDEX IF NOT EXISTS idx_storage_cleanup_queue_packing
    ON storage_cleanup_queue(project_id,session_id,resource_kind,resource_id);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '76');
