-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 77); do not edit.

CREATE TABLE IF NOT EXISTS device_requests (
    id TEXT PRIMARY KEY,
    device_hash TEXT NOT NULL UNIQUE,
    user_hash TEXT NOT NULL UNIQUE,
    machine_id TEXT NOT NULL,
    machine_name TEXT NOT NULL,
    os TEXT NOT NULL,
    source_ip TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    interval_seconds INTEGER NOT NULL DEFAULT 5,
    next_poll_at INTEGER NOT NULL,
    slowed INTEGER NOT NULL DEFAULT 0,
    decision TEXT CHECK (decision IN ('approved', 'denied')),
    decided_by TEXT REFERENCES members(id),
    decided_at INTEGER
  );

CREATE INDEX IF NOT EXISTS idx_device_requests_expiry ON device_requests(expires_at);

CREATE INDEX IF NOT EXISTS idx_device_requests_decider ON device_requests(decided_by);

CREATE INDEX IF NOT EXISTS idx_device_requests_pending_expiry ON device_requests(expires_at) WHERE decision IS NULL;

CREATE INDEX IF NOT EXISTS idx_device_requests_decided_expiry ON device_requests(expires_at) WHERE decision IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_device_requests_source_pending ON device_requests(source_ip, expires_at) WHERE decision IS NULL;

CREATE INDEX IF NOT EXISTS idx_device_requests_source_created ON device_requests(source_ip, created_at);

CREATE TABLE IF NOT EXISTS device_decision_audit (
    request_id TEXT PRIMARY KEY,
    member_id TEXT NOT NULL REFERENCES members(id),
    machine_id TEXT NOT NULL,
    machine_name TEXT NOT NULL,
    os TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    decision TEXT NOT NULL CHECK (decision IN ('approved', 'denied')),
    decided_at INTEGER NOT NULL
  );

CREATE INDEX IF NOT EXISTS idx_device_decision_audit_member ON device_decision_audit(member_id);

CREATE TRIGGER IF NOT EXISTS device_decision_audit_immutable BEFORE UPDATE ON device_decision_audit BEGIN
    SELECT RAISE(ABORT, 'device decision audit is immutable'); END;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '77');
