-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 78); do not edit.

ALTER TABLE sessions ADD COLUMN title_material_at INTEGER;

CREATE INDEX IF NOT EXISTS idx_sessions_untitled_open ON sessions (last_received_at)
    WHERE ended_at IS NULL AND title IS NULL;

CREATE INDEX IF NOT EXISTS idx_sessions_titled_recent ON sessions (last_received_at)
    WHERE title IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_prompt_batches_user_received ON prompt_batches (project_id, session_id, origin, received_at);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '78');
