-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 82); do not edit.

CREATE TABLE IF NOT EXISTS embedding_work_state (
    project_id TEXT NOT NULL CHECK (project_id NOT GLOB '*[^A-Za-z0-9._-]*' AND length(project_id) BETWEEN 1 AND 64 AND project_id NOT IN ('.', '..')), model_key TEXT NOT NULL,
    kind TEXT NOT NULL CHECK(kind IN ('embedding','hubness')), scope TEXT NOT NULL,
    revision INTEGER NOT NULL DEFAULT 0, checked_revision INTEGER NOT NULL DEFAULT -1,
    pending INTEGER NOT NULL DEFAULT 1 CHECK(pending IN (0,1)), wake_at INTEGER,
    sweep_at INTEGER NOT NULL DEFAULT 0, sweep_cursor TEXT, idle_rounds INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(project_id,model_key,kind));

CREATE INDEX IF NOT EXISTS idx_embedding_versions_attempt ON embedding_versions(project_id,type,attempted_at,record_id);

CREATE INDEX IF NOT EXISTS idx_embedding_receipts_identity ON embedding_receipts(project_id,type,record_id);

CREATE INDEX IF NOT EXISTS idx_embedding_receipts_retire ON embedding_receipts(project_id,model_key,updated_at,id) WHERE ready >= 0;

CREATE INDEX IF NOT EXISTS idx_embedding_receipts_delete ON embedding_receipts(project_id,ready,updated_at,id) WHERE ready < 0;

CREATE INDEX IF NOT EXISTS idx_embedding_receipts_spore ON embedding_receipts(project_id,model_key,id) WHERE type = 'spore' AND ready = 1;

CREATE INDEX IF NOT EXISTS idx_embedding_failures_retry ON embedding_source_failures(project_id,model_key,recorded_at);

CREATE INDEX IF NOT EXISTS idx_knowledge_release_embedding ON knowledge_release_state(project_id,namespace,record_id,checked_at DESC,id);

CREATE INDEX IF NOT EXISTS idx_agent_runs_task_live ON agent_runs(task,status);

CREATE INDEX IF NOT EXISTS idx_agent_runs_entry ON agent_runs(project_id,task,COALESCE(queued_at,started_at) DESC) WHERE status != 'skipped';

CREATE INDEX IF NOT EXISTS idx_agent_runs_skipped_entry ON agent_runs(project_id,task,run_context,COALESCE(queued_at,started_at) DESC) WHERE status = 'skipped';

CREATE TRIGGER IF NOT EXISTS embedding_versions_work_insert AFTER INSERT ON embedding_versions WHEN (NEW.type <> 'session' OR EXISTS (SELECT 1 FROM sessions
      WHERE project_id=NEW.project_id AND session_id=NEW.record_id AND summary IS NOT NULL AND trim(summary) <> '')
      OR EXISTS (SELECT 1 FROM embedding_receipts WHERE project_id=NEW.project_id AND type='session' AND record_id=NEW.record_id)) BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (NEW.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_versions_work_update AFTER UPDATE OF project_id,type,record_id,revision ON embedding_versions WHEN (OLD.type <> 'session' OR EXISTS (SELECT 1 FROM sessions
      WHERE project_id=OLD.project_id AND session_id=OLD.record_id AND summary IS NOT NULL AND trim(summary) <> '')
      OR EXISTS (SELECT 1 FROM embedding_receipts WHERE project_id=OLD.project_id AND type='session' AND record_id=OLD.record_id)) OR (NEW.type <> 'session' OR EXISTS (SELECT 1 FROM sessions
      WHERE project_id=NEW.project_id AND session_id=NEW.record_id AND summary IS NOT NULL AND trim(summary) <> '')
      OR EXISTS (SELECT 1 FROM embedding_receipts WHERE project_id=NEW.project_id AND type='session' AND record_id=NEW.record_id)) BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id,NEW.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_versions_work_delete AFTER DELETE ON embedding_versions WHEN (OLD.type <> 'session' OR EXISTS (SELECT 1 FROM sessions
      WHERE project_id=OLD.project_id AND session_id=OLD.record_id AND summary IS NOT NULL AND trim(summary) <> '')
      OR EXISTS (SELECT 1 FROM embedding_receipts WHERE project_id=OLD.project_id AND type='session' AND record_id=OLD.record_id)) BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_receipts_work_insert AFTER INSERT ON embedding_receipts  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (NEW.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_receipts_work_update AFTER UPDATE OF project_id,model_key,id,type,record_id,revision,ready,updated_at,rewrites ON embedding_receipts  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id,NEW.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_receipts_work_delete AFTER DELETE ON embedding_receipts  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_source_failures_work_insert AFTER INSERT ON embedding_source_failures  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (NEW.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_source_failures_work_update AFTER UPDATE ON embedding_source_failures  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id,NEW.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_source_failures_work_delete AFTER DELETE ON embedding_source_failures  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS processed_resources_work_insert AFTER INSERT ON processed_resources WHEN NEW.kind = 'plan' BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (NEW.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS processed_resources_work_update AFTER UPDATE ON processed_resources WHEN OLD.kind = 'plan' OR NEW.kind = 'plan' BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id,NEW.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS processed_resources_work_delete AFTER DELETE ON processed_resources WHEN OLD.kind = 'plan' BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id) AND kind IN ('embedding','hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_hubness_members_work_insert AFTER INSERT ON embedding_hubness_members  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (NEW.project_id) AND kind IN ('hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_hubness_members_work_update AFTER UPDATE ON embedding_hubness_members  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id,NEW.project_id) AND kind IN ('hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_hubness_members_work_delete AFTER DELETE ON embedding_hubness_members  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id) AND kind IN ('hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_cursors_work_insert AFTER INSERT ON embedding_cursors  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (NEW.project_id) AND kind IN ('hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_cursors_work_update AFTER UPDATE OF hubness_model,hubness_count,hubness_cursor ON embedding_cursors  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id,NEW.project_id) AND kind IN ('hubness'); END;

CREATE TRIGGER IF NOT EXISTS embedding_cursors_work_delete AFTER DELETE ON embedding_cursors  BEGIN
      UPDATE embedding_work_state SET revision=revision+1,pending=1,wake_at=NULL,sweep_cursor=NULL,idle_rounds=0
        WHERE project_id IN (OLD.project_id) AND kind IN ('hubness'); END;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '82');
