// Codegen: packages/myco/src/symbionts/skills.generated.ts
//
// Embeds every file under packages/myco/skills/<name>/ as a nested map
// `Record<skillName, Record<relPath, content>>`. The daemon writes this bundle
// to `<mycoHome>/skills` (ensureManagedSkills) so global skill symlinks resolve
// to a stable managed location — needed because the Bun-compiled binary can't
// fs.readFileSync paths inside the /$bunfs/ virtual filesystem, and no install
// kind ships a skills/ dir under ~/.myco otherwise. The map is nested rather
// than flat (like templates.generated.ts) because the consumer installs and
// links per-skill-directory.
//
// Run manually: node packages/myco/scripts/gen-skills.mjs
// Check sync (CI / test guard): node packages/myco/scripts/gen-skills.mjs --check
// Wired into `npm run codegen`.

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { walk, readTextFile, listSkillDirs, emitBundle } from './codegen-bundle.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(__dirname, '..');
const SKILLS_DIR = path.resolve(PKG_ROOT, 'skills');
const OUTPUT = path.resolve(PKG_ROOT, 'src/symbionts/skills.generated.ts');

/**
 * Build the skills.generated.ts content in memory. Both the write mode and the
 * --check guard call this so the committed bundle and the freshly-generated
 * bundle are compared byte-for-byte against one source of truth. Skills are
 * serialized NESTED: `Record<skillName, Record<relPath, content>>` because the
 * consumer installs and links per-skill-directory.
 */
function buildBundle() {
  const skillNames = listSkillDirs(SKILLS_DIR);
  let fileCount = 0;
  const skillBlocks = skillNames.map((name) => {
    const skillDir = path.join(SKILLS_DIR, name);
    const files = walk(skillDir).sort();
    const fileEntries = files
      .map((abs) => {
        const rel = path.relative(skillDir, abs).split(path.sep).join('/');
        const body = readTextFile(abs);
        fileCount += 1;
        return `    ${JSON.stringify(rel)}: ${JSON.stringify(body)},`;
      })
      .join('\n');
    return `  ${JSON.stringify(name)}: {\n${fileEntries}\n  },`;
  });

  const serialized = skillBlocks.join('\n');

  const content = `// AUTO-GENERATED by scripts/gen-skills.mjs — DO NOT EDIT.
// Regenerate via \`npm run codegen\`.

export const BUNDLED_SKILLS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
${serialized}
};
`;

  return { content, skills: skillNames.length, files: fileCount };
}

const { content, skills, files } = buildBundle();
emitBundle({
  outputPath: OUTPUT,
  pkgRoot: PKG_ROOT,
  content,
  count: `${skills} skills, ${files} files`,
  label: 'gen-skills',
  checkMode: process.argv.includes('--check'),
});
