import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(__dirname, '..');
const UI_DIR = path.resolve(PACKAGE_ROOT, 'dist/ui');
const OUTPUT_PATH = path.resolve(PACKAGE_ROOT, 'src/ui-assets.generated.ts');

/**
 * Recursively walk a directory, returning every file's path relative to the
 * walk root, using forward slashes (the keys callers look up at serve time).
 */
function walkFiles(root: string, dir: string = root): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walkFiles(root, abs));
    } else if (entry.isFile()) {
      out.push(path.relative(root, abs).split(path.sep).join('/'));
    }
  }
  return out;
}

function readUiAssetMap(): Record<string, string> {
  if (!fs.existsSync(UI_DIR)) {
    process.stderr.write(
      `[gen-ui-assets] WARNING: ${path.relative(PACKAGE_ROOT, UI_DIR)} is absent — emitting empty map. ` +
        `Run \`npm run build:ui\` before codegen to embed the dashboard.\n`,
    );
    return {};
  }
  return Object.fromEntries(
    walkFiles(UI_DIR).map((rel) => [rel, fs.readFileSync(path.join(UI_DIR, rel)).toString('base64')]),
  );
}

function main(): void {
  const assets = readUiAssetMap();

  const output = `// AUTO-GENERATED by scripts/gen-ui-assets.ts — DO NOT EDIT.
// Run \`npm run codegen\` to regenerate.
//
// Dashboard UI bundle (from \`dist/ui/\`) base64-encoded and bundled into code
// for the Bun-compiled binary path. The standalone binary ships without an
// adjacent \`dist/ui/\` tree, so it cannot rely on runtime filesystem reads;
// keys are file paths relative to \`dist/ui/\` (forward slashes, no leading
// slash) and values are base64 strings.

export const BUNDLED_UI: Readonly<Record<string, string>> = ${JSON.stringify(assets, null, 2)} as const;
`;

  fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');
  process.stdout.write(
    `[gen-ui-assets] wrote ${path.relative(PACKAGE_ROOT, OUTPUT_PATH)} (${Object.keys(assets).length} files)\n`,
  );
}

main();
