/**
 * Embeds the Cloudflare Worker bundle the binary deploys.
 *
 * Provisioning holds no repository checkout, so the Worker travels inside the
 * binary as base64. Wrangler produces the bundle — the same bundler a deploy
 * from source would use — through `deploy --dry-run --outdir`, and the deploy
 * ships it unchanged under `no_bundle`.
 *
 * The output is not committed. It is regenerated by `codegen`, and by the
 * `prelint`/`pretest` hooks so a fresh clone has it before anything reads it.
 * Regeneration is skipped when every input is older than the module, which
 * makes those hooks free on an unchanged tree.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..', '..', '..');
const WORKER_DIR = path.join(REPO_ROOT, 'packages', 'myco-server');
const OUTPUT_PATH = path.join(REPO_ROOT, 'packages', 'myco', 'src', 'worker-bundle.generated.ts');
const EXPORT_NAME = 'BUNDLED_WORKER';
const VERSION_EXPORT_NAME = 'BUNDLED_WORKER_WRANGLER';

/** A dangling source-map reference: the map is not carried, so the comment names a file no deploy ships. */
const SOURCE_MAP_COMMENT = /\n\/\/# sourceMappingURL=[^\n]*\n?$/;

/**
 * Everything the bundle is built from. A change to any of these can change the
 * output, so any one being newer than the module means the module is stale.
 */
const INPUTS = [
  path.join(WORKER_DIR, 'src'),
  path.join(WORKER_DIR, 'wrangler.toml'),
  path.join(REPO_ROOT, 'packages', 'myco-shared', 'src'),
  path.join(REPO_ROOT, 'packages', 'myco-shared', 'dist'),
  path.join(REPO_ROOT, 'package-lock.json'),
  path.join(HERE, 'gen-worker-bundle.ts'),
];

/** The newest modification time under a file or directory, or 0 when it is absent. */
export function newestMtime(target: string): number {
  if (!existsSync(target)) return 0;
  const stat = statSync(target);
  if (!stat.isDirectory()) return stat.mtimeMs;
  let newest = stat.mtimeMs;
  for (const entry of readdirSync(target, { withFileTypes: true })) {
    newest = Math.max(newest, newestMtime(path.join(target, entry.name)));
  }
  return newest;
}

/**
 * Whether the module must be rebuilt: it is absent, or an input is at least as
 * new as it is. Equal times count as stale, so the answer errs toward building
 * a bundle that was already current rather than shipping one that was not.
 */
export function bundleIsStale(outputPath: string = OUTPUT_PATH, inputs: readonly string[] = INPUTS): boolean {
  if (!existsSync(outputPath)) return true;
  const built = statSync(outputPath).mtimeMs;
  return inputs.some((input) => newestMtime(input) >= built);
}

/** The wrangler the lockfile pins for the Worker package; the bundle's shape is that version's. */
export function pinnedWranglerVersion(): string {
  const lock = JSON.parse(readFileSync(path.join(REPO_ROOT, 'package-lock.json'), 'utf-8')) as {
    packages: Record<string, { version?: string }>;
  };
  const pinned = lock.packages['packages/myco-server/node_modules/wrangler']?.version;
  if (pinned === undefined) throw new Error('package-lock.json pins no wrangler for packages/myco-server; the bundle has no known bundler version');
  return pinned;
}

/** The wrangler that answers in the Worker package, which is the one that must build the bundle. */
function installedWranglerVersion(): string {
  const printed = execFileSync('npx', ['--no-install', 'wrangler', '--version'], { cwd: WORKER_DIR, encoding: 'utf-8' });
  const version = /(\d+\.\d+\.\d+)/.exec(printed)?.[1];
  if (version === undefined) throw new Error(`wrangler did not print a version in ${WORKER_DIR}:\n${printed}`);
  return version;
}

/** The config wrangler bundles against, in the Worker package so `main` resolves. */
const BUNDLE_CONFIG_NAME = 'wrangler.bundle.toml';

/**
 * The committed configuration without its `[assets]` table.
 *
 * Assets are uploaded beside the script rather than bundled into it, so they
 * change no byte of the output — but wrangler refuses to run at all when the
 * directory the table names is absent, which it is on any tree that has not
 * built the dashboard. Dropping the table lets the bundle be built from source
 * alone; the deploy's own config carries the table and the staged dashboard.
 */
export function bundleConfig(toml: string): string {
  const kept: string[] = [];
  let inAssets = false;
  for (const line of toml.split('\n')) {
    const trimmed = line.trim();
    if (trimmed.startsWith('[')) inAssets = trimmed === '[assets]';
    if (!inAssets) kept.push(line);
  }
  if (kept.length === toml.split('\n').length) throw new Error('wrangler.toml carries no [assets] table; gen-worker-bundle and the configuration have drifted');
  return kept.join('\n');
}

/** Build the bundle and answer its bytes, with the dangling map reference removed. */
export function assertWranglerPinned(): string {
  const pinned = pinnedWranglerVersion();
  const installed = installedWranglerVersion();
  if (installed !== pinned) {
    throw new Error(`wrangler ${installed} is installed but package-lock.json pins ${pinned}; run npm ci before generating the Worker bundle`);
  }
  return pinned;
}

export function buildWorkerBundle(): string {
  const out = mkdtempSync(path.join(tmpdir(), 'myco-worker-bundle-'));
  const config = path.join(WORKER_DIR, BUNDLE_CONFIG_NAME);
  try {
    writeFileSync(config, bundleConfig(readFileSync(path.join(WORKER_DIR, 'wrangler.toml'), 'utf-8')), 'utf-8');
    execFileSync('npx', ['--no-install', 'wrangler', 'deploy', '--dry-run', '--outdir', out, '-c', BUNDLE_CONFIG_NAME], {
      cwd: WORKER_DIR,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    const built = path.join(out, 'index.js');
    if (!existsSync(built)) throw new Error(`wrangler wrote no bundle to ${out}`);
    return readFileSync(built, 'utf-8').replace(SOURCE_MAP_COMMENT, '\n');
  } finally {
    rmSync(out, { recursive: true, force: true });
    rmSync(config, { force: true });
  }
}

/** Write the module. Answers the bundle's byte length. */
export function emitWorkerBundle(outputPath: string = OUTPUT_PATH, wranglerVersion?: string): number {
  const version = wranglerVersion ?? assertWranglerPinned();
  const bundle = buildWorkerBundle();
  if (bundle.trim() === '') throw new Error('the Worker bundle is empty; a deploy from it would serve nothing');
  writeFileSync(outputPath, [
    '// GENERATED FILE — do not edit.',
    '// Written by packages/myco/scripts/gen-worker-bundle.ts from the Cloudflare Worker',
    '// source, so provisioning can deploy without a repository checkout.',
    '',
    `export const ${VERSION_EXPORT_NAME}: string = ${JSON.stringify(version)};`,
    '',
    `export const ${EXPORT_NAME}: string = ${JSON.stringify(Buffer.from(bundle, 'utf-8').toString('base64'))};`,
    '',
  ].join('\n'), 'utf-8');
  return Buffer.byteLength(bundle, 'utf-8');
}

function main(): void {
  // Before the staleness check: a bundler bump has to fail on the next command,
  // not on the next command that happens to rebuild.
  const version = assertWranglerPinned();
  if (!bundleIsStale()) return;
  const bytes = emitWorkerBundle(OUTPUT_PATH, version);
  process.stdout.write(`worker-bundle.generated.ts (${bytes} bytes of Worker)\n`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
