/** Channel eligibility and numeric SemVer ordering, shared with the generated POSIX installer. */
export const RELEASE_POLICY = {
  versionPattern: '^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(-(alpha|beta|rc)[.](0|[1-9][0-9]*))?$',
  developmentPattern: '^0[.]0[.]0(-dev)?([+][0-9A-Za-z.-]+)?$',
  phases: { alpha: 1, beta: 2, rc: 3, stable: 4 },
  channels: { alpha: ['alpha', 'beta', 'stable'], beta: ['beta', 'stable'], stable: ['stable'] },
  order: ['major', 'minor', 'patch', 'phase', 'iteration'],
  minimumMajor: 2,
  rejectDrafts: true,
  rejectFlaggedStable: true,
  requireCompleteAssets: true,
  neverDowngrade: true,
  maximumComponent: Number.MAX_SAFE_INTEGER,
};

/** Placeholder builds belong to the 2.0 source tree and update only explicitly. */
export function isDevelopmentVersion(version) {
  return new RegExp(RELEASE_POLICY.developmentPattern).test(version);
}

export function isV2Version(version) {
  return isDevelopmentVersion(version) || Number(/^([0-9]+)[.]/.exec(version)?.[1] ?? 0) >= RELEASE_POLICY.minimumMajor;
}

export function releaseKey(version) {
  const match = new RegExp(RELEASE_POLICY.versionPattern).exec(version);
  if (!match || match[0] !== version) return null;
  const phase = match[5] ?? 'stable';
  const values = { major: Number(match[1]), minor: Number(match[2]), patch: Number(match[3]),
    phase: RELEASE_POLICY.phases[phase], iteration: Number(match[6] ?? 0) };
  if (Object.values(values).some(n => n > RELEASE_POLICY.maximumComponent)) return null;
  return { phase, key: RELEASE_POLICY.order.map(field => values[field]) };
}

export function compareReleaseVersions(a, b) {
  const left = releaseKey(a), right = releaseKey(b);
  if (!left || !right) throw new Error('Invalid release version');
  for (let i = 0; i < left.key.length; i++) {
    if (left.key[i] !== right.key[i]) return left.key[i] > right.key[i] ? 1 : -1;
  }
  return 0;
}

export function selectChannelRelease(releases, channel, options = {}) {
  const allowed = RELEASE_POLICY.channels[channel];
  if (!allowed) throw new Error('Invalid release channel');
  const { asset, currentVersion, minimumMajor = RELEASE_POLICY.minimumMajor, maximumMajor = Infinity } = options;
  let best = null;
  for (const release of releases) {
    if ((RELEASE_POLICY.rejectDrafts && release.draft) || !release.tag_name.startsWith('myco/v')) continue;
    const version = release.tag_name.slice(6), parsed = releaseKey(version);
    if (!parsed || parsed.key[0] < minimumMajor || parsed.key[0] > maximumMajor || !allowed.includes(parsed.phase)) continue;
    if (RELEASE_POLICY.rejectFlaggedStable && parsed.phase === 'stable' && release.prerelease) continue;
    if (RELEASE_POLICY.requireCompleteAssets && asset && (!release.assets?.some(a => a.name === asset) || !release.assets?.some(a => a.name === 'SHA256SUMS'))) continue;
    if (!best || compareReleaseVersions(version, best.tag_name.slice(6)) > 0) best = release;
  }
  if (RELEASE_POLICY.neverDowngrade && best && currentVersion && !isDevelopmentVersion(currentVersion)) {
    if (!releaseKey(currentVersion) || compareReleaseVersions(best.tag_name.slice(6), currentVersion) < 0) return null;
  }
  return best;
}

/** Render the policy into awk; JSON decoding is the installer's input adapter. */
export function renderReleaseSelector() {
  const p = RELEASE_POLICY;
  const ranks = Object.entries(p.phases).map(([phase, rank]) => `rank["${phase}"]=${rank}`).join('; ');
  const allowed = Object.entries(p.channels).flatMap(([ch, phases]) => phases.map(phase => `allowed["${ch}","${phase}"]=1`)).join('; ');
  const fields = { major: 'c[1]+0', minor: 'c[2]+0', patch: 'c[3]+0', phase: 'rank[phase]', iteration: 'iteration+0' };
  const keys = p.order.map((field, i) => `key[${i + 1}]=${fields[field]}`).join('; ');
  return `# Generated by packages/myco/scripts/gen-release-selector.mjs from release-policy.mjs.
is_development_version() {
  awk -v version="$1" 'BEGIN { exit !(version ~ /${p.developmentPattern}/) }'
}
valid_version() {
  is_development_version "$1" || awk -v version="$1" 'BEGIN {
    if (version !~ /${p.versionPattern}/) exit 1
    gsub(/[.-]/," ",version); n=split(version,parts," ")
    for (i=1;i<=n;i++) if (parts[i]+0>${p.maximumComponent}) exit 1
    exit 0
  }'
}
pick_tag() {
  awk -F '\\t' -v channel="$1" -v current="$2" -v min="\${3:-${p.minimumMajor}}" -v max="\${4:-0}" '
    function parse(v, key, c, parts, phase, iteration, core, dash, i) {
      if (v !~ /${p.versionPattern}/) return 0
      dash=index(v,"-"); core=dash ? substr(v,1,dash-1) : v
      split(core,c,"."); phase="stable"; iteration=0
      if (dash) { split(substr(v,dash+1),parts,"."); phase=parts[1]; iteration=parts[2] }
      ${keys}
      for (i=1;i<=${p.order.length};i++) if (key[i]>${p.maximumComponent}) return 0
      parsed_phase=phase; return 1
    }
    function compare(a,b, i) {
      for (i=1;i<=${p.order.length};i++) if (a[i]!=b[i]) return a[i]>b[i] ? 1 : -1
      return 0
    }
    BEGIN { ${ranks}; ${allowed} }
    {
      if ($1 !~ /^myco\\/v/${p.rejectDrafts ? ' || $3=="true"' : ''}${p.requireCompleteAssets ? ' || $4!=1 || $5!=1' : ''}) next
      v=substr($1,7)
      if (!parse(v,key) || key[1]<min || (max>0 && key[1]>max) || !allowed[channel,parsed_phase]) next
      ${p.rejectFlaggedStable ? 'if (parsed_phase=="stable" && $2=="true") next' : ''}
      if (best=="" || compare(key,bestkey)>0) {
        best=$1; for (i=1;i<=${p.order.length};i++) bestkey[i]=key[i]
      }
    }
    END {
      ${p.neverDowngrade ? `if (best!="" && current!="" && current !~ /${p.developmentPattern}/ && (!parse(current,currentkey) || compare(bestkey,currentkey)<0)) print "stay-put"\n      else ` : ''}if (best!="") print best
    }' "$RELEASES_FILE"
}
`;
}

/** Render the shared release policy for the standalone Windows installer. */
export function renderPowerShellReleaseSelector() {
  const p = RELEASE_POLICY;
  return `# Generated by packages/myco/scripts/gen-release-selector.mjs from release-policy.mjs.
function Get-MycoReleaseKey {
    param([string]$Version)
    $match = [regex]::Match($Version, '${p.versionPattern}')
    if (-not $match.Success -or $match.Value -cne $Version) { return $null }
    $phase = if ($match.Groups[5].Success) { $match.Groups[5].Value } else { 'stable' }
    $ranks = @{ ${Object.entries(p.phases).map(([phase, rank]) => `${phase} = ${rank}`).join('; ')} }
    $key = @([double]$match.Groups[1].Value, [double]$match.Groups[2].Value, [double]$match.Groups[3].Value, $ranks[$phase], [double]$match.Groups[6].Value)
    if (@($key | Where-Object { $_ -gt ${p.maximumComponent} }).Count) { return $null }
    return [PSCustomObject]@{ Phase = $phase; Key = $key }
}

function Compare-MycoReleaseKeys {
    param($Left, $Right)
    for ($i = 0; $i -lt ${p.order.length}; $i++) {
        if ($Left[$i] -ne $Right[$i]) { if ($Left[$i] -gt $Right[$i]) { return 1 } else { return -1 } }
    }
    return 0
}

function Select-MycoRelease {
    param([object[]]$Releases, [string]$Channel, [string]$CurrentVersion = '', [int]$MinMajor = ${p.minimumMajor}, [int]$MaxMajor = 0)
    $allowed = @{ ${Object.entries(p.channels).map(([channel, phases]) => `${channel} = @(${phases.map(phase => `'${phase}'`).join(', ')})`).join('; ')} }
    $best = $null
    $bestKey = $null
    foreach ($release in $Releases) {
        if ($release.draft -or $release.tag_name -cnotmatch '^myco/v') { continue }
        $version = $release.tag_name.Substring(6)
        $parsed = Get-MycoReleaseKey $version
        if (-not $parsed -or $parsed.Key[0] -lt $MinMajor -or ($MaxMajor -gt 0 -and $parsed.Key[0] -gt $MaxMajor)) { continue }
        if ($allowed[$Channel] -cnotcontains $parsed.Phase -or ($parsed.Phase -eq 'stable' -and $release.prerelease)) { continue }
        if (@($release.assets | Where-Object { $_.name -ceq $Asset }).Count -eq 0 -or @($release.assets | Where-Object { $_.name -ceq 'SHA256SUMS' }).Count -eq 0) { continue }
        if (-not $best -or (Compare-MycoReleaseKeys $parsed.Key $bestKey) -gt 0) { $best = $release.tag_name; $bestKey = $parsed.Key }
    }
    if ($best -and $CurrentVersion -and $CurrentVersion -cnotmatch '${p.developmentPattern}') {
        $current = Get-MycoReleaseKey $CurrentVersion
        if (-not $current -or (Compare-MycoReleaseKeys $bestKey $current.Key) -lt 0) { return 'stay-put' }
    }
    return $best
}
`;
}
