/**
 * Binary resolution for the npm dispatch shim (`bin/myco.cjs`).
 *
 * Regression origin: `vendor/resolved.json` is generated by the postinstall
 * and absent from the published tarball, yet it was the shim's ONLY source.
 * A routine `npm update -g` re-extracts the package (deleting the generated
 * file) without re-running postinstall, so every `myco` invocation hard-exited
 * while a healthy binary sat both in the platform package and at the managed
 * path. These tests pin the fallback order that makes that unreachable.
 */

import { afterEach, beforeEach, describe, it, expect } from 'bun:test';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { managedBinaryPath } from '../../packages/myco/scripts/managed-paths.mjs';

const SHIM_SOURCE = path.resolve('packages/myco/bin/myco.cjs');
const REDIRECT_SOURCE = path.resolve('packages/myco/bin/runtime-redirect.cjs');

/** The platform target the shim computes for this host. */
function hostTarget(): string {
  if (process.platform === 'darwin') return process.arch === 'arm64' ? 'darwin-arm64' : 'darwin-x64';
  if (process.platform === 'linux') return process.arch === 'arm64' ? 'linux-arm64' : 'linux-x64';
  return 'windows-x64';
}

let tmpRoot: string;

beforeEach(() => {
  tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'myco-shim-'));
});

afterEach(() => {
  fs.rmSync(tmpRoot, { recursive: true, force: true });
});

/** A fake myco binary that identifies which source it came from. */
function writeStubBinary(target: string, marker: string): void {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, `#!/bin/sh\nprintf '${marker}:%s' "$*"\n`, { mode: 0o755 });
}

/** A package fixture holding the real shim, with no resolution sources yet. */
function makeFixture(): { shimPath: string; pkgRoot: string; mycoHome: string } {
  const pkgRoot = path.join(tmpRoot, 'pkg');
  fs.mkdirSync(path.join(pkgRoot, 'bin'), { recursive: true });
  const shimPath = path.join(pkgRoot, 'bin', 'myco.cjs');
  fs.copyFileSync(SHIM_SOURCE, shimPath);
  fs.copyFileSync(REDIRECT_SOURCE, path.join(pkgRoot, 'bin', 'runtime-redirect.cjs'));

  // A myco-home with no runtime.command, so the pin never short-circuits
  // resolution and each test exercises the source it set up.
  const mycoHome = path.join(tmpRoot, 'home');
  fs.mkdirSync(mycoHome, { recursive: true });
  return { shimPath, pkgRoot, mycoHome };
}

/**
 * Spawn under `node`, not `process.execPath`.
 *
 * The shim is a `#!/usr/bin/env node` script and node is its only real
 * runtime. `process.execPath` inside this suite is bun, whose resolver reaches
 * into its own global install cache — `require.resolve` there finds a real
 * `@goondocks/myco-<target>` outside the fixture and silently satisfies source
 * 2, making the later fallbacks untestable.
 */
function runShim(shimPath: string, mycoHome: string) {
  return spawnSync('node', [shimPath, 'doctor', '--json'], {
    cwd: tmpRoot,
    encoding: 'utf-8',
    env: { ...process.env, MYCO_HOME: mycoHome, MYCO_REDIRECTED: undefined } as NodeJS.ProcessEnv,
  });
}

describe('myco.cjs binary resolution', () => {
  it('prefers vendor/resolved.json when the postinstall has run', () => {
    const { shimPath, pkgRoot, mycoHome } = makeFixture();
    const vendored = path.join(tmpRoot, 'vendored-myco');
    writeStubBinary(vendored, 'VENDOR');
    fs.mkdirSync(path.join(pkgRoot, 'vendor'), { recursive: true });
    fs.writeFileSync(
      path.join(pkgRoot, 'vendor', 'resolved.json'),
      JSON.stringify({ target: hostTarget(), binaryPath: vendored }),
    );
    writeStubBinary(path.join(mycoHome, 'bin', 'myco'), 'MANAGED');

    const res = runShim(shimPath, mycoHome);

    expect(res.status).toBe(0);
    expect(res.stdout).toBe('VENDOR:doctor --json');
  });

  it('falls back to the platform package when the generated file is gone', () => {
    // This is `npm update -g` exactly: the package was re-extracted, so the
    // generated vendor/ never came back, but the optional dependency is there.
    const { shimPath, pkgRoot, mycoHome } = makeFixture();
    const platformBinary = path.join(
      pkgRoot, 'node_modules', '@goondocks', `myco-${hostTarget()}`, 'bin', 'myco',
    );
    writeStubBinary(platformBinary, 'PLATFORM');

    const res = runShim(shimPath, mycoHome);

    expect(res.status).toBe(0);
    expect(res.stdout).toBe('PLATFORM:doctor --json');
  });

  it('falls back to the managed binary when the platform package is gone too', () => {
    // Also the agreement gate for the layout the shim duplicates: the binary
    // is planted at the path `managedBinaryPath()` computes, so the shim only
    // finds it if its inlined copy of that layout still matches.
    const { shimPath, mycoHome } = makeFixture();
    const managed = managedBinaryPath(mycoHome, process.platform, process.env.LOCALAPPDATA);
    writeStubBinary(managed, 'MANAGED');

    const res = runShim(shimPath, mycoHome);

    expect(res.status).toBe(0);
    expect(res.stdout).toBe('MANAGED:doctor --json');
  });

  it('ignores a resolved.json pointing at a deleted binary', () => {
    // The stale-pointer shape: the file survives but its target does not.
    const { shimPath, pkgRoot, mycoHome } = makeFixture();
    fs.mkdirSync(path.join(pkgRoot, 'vendor'), { recursive: true });
    fs.writeFileSync(
      path.join(pkgRoot, 'vendor', 'resolved.json'),
      JSON.stringify({ target: hostTarget(), binaryPath: path.join(tmpRoot, 'gone', 'myco') }),
    );
    writeStubBinary(path.join(mycoHome, 'bin', 'myco'), 'MANAGED');

    const res = runShim(shimPath, mycoHome);

    expect(res.status).toBe(0);
    expect(res.stdout).toBe('MANAGED:doctor --json');
  });

  it('skips a present-but-not-executable candidate instead of dead-ending on it', () => {
    // Observed on a real install: `npm update -g` re-extracted the platform
    // package at mode 0644 and postinstall — which is what chmods it to 0755 —
    // never ran. Accepting it on existence alone exec'd a binary that could
    // not run, and EACCES surfaced as a silent exit 1.
    const { shimPath, pkgRoot, mycoHome } = makeFixture();
    const platformBinary = path.join(
      pkgRoot, 'node_modules', '@goondocks', `myco-${hostTarget()}`, 'bin', 'myco',
    );
    writeStubBinary(platformBinary, 'PLATFORM');
    fs.chmodSync(platformBinary, 0o644);
    writeStubBinary(path.join(mycoHome, 'bin', 'myco'), 'MANAGED');

    const res = runShim(shimPath, mycoHome);

    expect(res.status).toBe(0);
    expect(res.stdout).toBe('MANAGED:doctor --json');
  });

  it('reports a spawn failure instead of exiting silently', () => {
    // Every candidate unusable except one that cannot be spawned at all.
    const { shimPath, mycoHome } = makeFixture();
    const managed = path.join(mycoHome, 'bin', 'myco');
    fs.mkdirSync(path.dirname(managed), { recursive: true });
    // Executable bit set, but the interpreter does not exist → ENOENT on spawn.
    fs.writeFileSync(managed, '#!/nonexistent/interpreter\n', { mode: 0o755 });

    const res = runShim(shimPath, mycoHome);

    expect(res.status).toBe(1);
    expect(res.stderr).toContain('could not execute');
    expect(res.stderr).toContain(managed);
  });

  it('fails with every attempted source named when nothing resolves', () => {
    const { shimPath, mycoHome } = makeFixture();

    const res = runShim(shimPath, mycoHome);

    expect(res.status).toBe(1);
    expect(res.stderr).toContain('no myco binary found');
    // An operator has to be able to see which sources were consulted.
    expect(res.stderr).toContain(`@goondocks/myco-${hostTarget()}`);
    expect(res.stderr).toContain(path.join(mycoHome, 'bin', 'myco'));
    expect(res.stderr).toContain('install.sh');
  });

  it('forwards the child exit code rather than masking it', () => {
    const { shimPath, mycoHome } = makeFixture();
    const managed = path.join(mycoHome, 'bin', 'myco');
    fs.mkdirSync(path.dirname(managed), { recursive: true });
    fs.writeFileSync(managed, '#!/bin/sh\nexit 42\n', { mode: 0o755 });

    const res = runShim(shimPath, mycoHome);

    expect(res.status).toBe(42);
  });
});
