/**
 * Shared composition for Cortex instruction injection surfaces.
 *
 * The managed Cortex instruction artifact is generated by the Myco agent and
 * remains the source of truth. Event-specific injection paths may wrap that
 * artifact with a small stable frame, but they should not fork their own
 * instruction content.
 */

export const SUBAGENT_CORTEX_GUIDANCE = [
  'You are a delegated subagent working inside a Myco-connected project.',
  'Follow these managed Cortex instructions as current project guidance.',
  'Apply them to your assigned task, and defer broad orchestration decisions back to the parent agent.',
].join('\n');

export type CortexInjectionSurface = 'session-start' | 'subagent-start';

export interface CortexInjectionContext {
  surface: CortexInjectionSurface;
  text: string;
}

export function composeCortexInstructionInjection(
  cortexContent: string,
  surface: CortexInjectionSurface,
): CortexInjectionContext | null {
  const trimmed = cortexContent.trim();
  if (!trimmed) return null;

  if (surface === 'subagent-start') {
    return {
      surface,
      text: `${SUBAGENT_CORTEX_GUIDANCE}\n\n${trimmed}`,
    };
  }

  return { surface, text: trimmed };
}
