// AUTO-GENERATED by scripts/gen-hook-config.ts — DO NOT EDIT.
// What the launch preamble reads from the manifests before a hook runs, kept apart from the hook config so the
// preamble loads no more than it reads.

/** Each harness's environment variable naming its project directory for a hook (its manifest's `projectDirEnvVar`). */
export const PROJECT_DIR_ENV_VARS: Readonly<Record<string, string>> = {
  "claude-code": "CLAUDE_PROJECT_DIR",
  "cursor": "CURSOR_PROJECT_DIR",
  "windsurf": "WINDSURF_PROJECT_DIR"
};

/** Each harness that names its workspace only in the hook payload, and the payload field (`hookInput.workspaceFromStdin`). */
export const STDIN_WORKSPACE_FIELDS: Readonly<Record<string, string>> = {
  "antigravity": "workspacePaths"
};
