// AUTO-GENERATED by scripts/gen-hook-config.ts — DO NOT EDIT.
// Run `npm run codegen` to regenerate.
//
// Full parsed symbiont manifests bundled for the compiled binary path.
// loadManifests() in symbionts/detect.ts prefers the filesystem candidates
// (source/dist layouts) when they're populated and falls back to this array
// for the compiled-Bun case where manifest YAMLs aren't enumerable on disk.

import type { SymbiontManifest } from './manifest-schema.js';

export const BUNDLED_MANIFESTS: readonly SymbiontManifest[] = [
  {
    "name": "antigravity",
    "displayName": "Google Antigravity",
    "binary": "antigravity",
    "configDir": ".agents/plugins/myco",
    "detectionDir": "~/.gemini",
    "pluginRootEnvVar": "ANTIGRAVITY_PLUGIN_ROOT",
    "hookFields": {
      "sessionId": "conversationId",
      "transcriptPath": "transcriptPath",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "toolCall.name",
      "toolInput": "toolCall.args",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "hookInput": {
      "workspaceFromStdin": "workspacePaths"
    },
    "capture": {
      "planDirs": [
        ".agents/plugins/myco/plans/"
      ],
      "planTags": [],
      "rules": [],
      "transcriptDiscovery": {
        "roots": [
          "~/.gemini/antigravity-cli",
          "~/.gemini/antigravity",
          "~/.gemini/antigravity-ide"
        ],
        "patterns": [
          "brain/{sessionId}/.system_generated/logs/transcript_full.jsonl"
        ],
        "retention": "harness"
      },
      "promptsFromTranscript": true
    },
    "registration": {
      "hooksTarget": ".agents/plugins/myco/hooks.json",
      "globalHooksTarget": "~/.gemini/config/plugins/myco/hooks.json",
      "globalMcpTarget": [
        {
          "path": "~/.gemini/config/plugins/myco/mcp_config.json"
        }
      ],
      "globalSkillsTarget": "~/.agents/skills",
      "retiredGlobalSkillsTargets": [
        "~/.gemini/antigravity/skills"
      ],
      "pluginManifestTarget": ".agents/plugins/myco/plugin.json",
      "globalPluginManifestTarget": "~/.gemini/config/plugins/myco/plugin.json",
      "hooksFormat": "plugin-file",
      "hooksTemplateFile": "hooks.json",
      "hookResponse": {
        "format": "antigravity-inject-steps"
      },
      "mcpTarget": ".agents/plugins/myco/mcp_config.json",
      "mcpFormat": "json",
      "mcpServersKey": "mcpServers",
      "settingsFormat": "json"
    },
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false,
      "postToolUseInjection": false,
      "turnRowSource": "hook",
      "transcriptFidelity": "full",
      "canopyReadTools": [],
      "pathBearingTools": [
        {
          "tool": "view_file",
          "pathField": "AbsolutePath",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "write_to_file",
          "pathField": "TargetFile",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "read_file",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "replace",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "run_shell_command",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        }
      ]
    },
    "hooks": {},
    "runner": {
      "order": 5,
      "asking": {
        "kind": "unheld"
      },
      "credential": {
        "provider": "google",
        "slot": null,
        "variables": [
          "GEMINI_API_KEY"
        ]
      },
      "profile": {
        "models": {
          "low": null,
          "default": null,
          "high": null
        },
        "efforts": {
          "low": "low",
          "default": "medium",
          "high": "high"
        },
        "allowedEfforts": [],
        "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$",
        "modelHint": "Model selection is unavailable for this agent."
      },
      "worker": {
        "binary": "agy",
        "launch": {
          "kind": "sidecar",
          "binary": "agy_acp_server.par"
        },
        "login": {
          "kind": "file",
          "path": "~/.gemini/antigravity-cli/settings.json",
          "requires": []
        },
        "isolation": {
          "kind": "additive"
        },
        "sourceGit": "none",
        "modelSetting": "none",
        "steps": [
          {
            "category": "read",
            "kind": "read",
            "target": [
              "locations.0.path",
              "rawInput.path",
              "rawInput.filePath",
              "rawInput.file_path"
            ]
          },
          {
            "category": "search",
            "kind": "search",
            "target": [
              "locations.0.path",
              "rawInput.path"
            ]
          },
          {
            "category": "edit",
            "kind": "edit",
            "target": [
              "locations.0.path",
              "rawInput.path",
              "rawInput.filePath",
              "rawInput.file_path"
            ]
          },
          {
            "category": "delete",
            "kind": "edit",
            "target": [
              "locations.0.path",
              "rawInput.path"
            ]
          },
          {
            "category": "move",
            "kind": "edit",
            "target": [
              "locations.0.path",
              "rawInput.path"
            ]
          },
          {
            "category": "execute",
            "kind": "command",
            "target": [
              "rawInput.command",
              "rawInput.cmd"
            ]
          },
          {
            "category": "fetch",
            "kind": "fetch",
            "target": [
              "rawInput.url",
              "rawInput.query"
            ]
          }
        ],
        "stepTool": "category",
        "accounting": {
          "reported": "acp-session",
          "modelSources": [
            "session.models",
            "session.configOptions",
            "session.currentModelId"
          ],
          "launchFallback": "none",
          "zeroDollars": "unavailable",
          "provider": {
            "kind": "unavailable"
          },
          "tokenScope": "unverified"
        }
      }
    }
  },
  {
    "name": "claude-code",
    "displayName": "Claude Code",
    "binary": "claude",
    "configDir": ".claude",
    "detectionDir": "~/.claude",
    "pluginRootEnvVar": "CLAUDE_PLUGIN_ROOT",
    "settingsPath": ".claude/settings.json",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "projectDirEnvVar": "CLAUDE_PROJECT_DIR",
    "resumeCommand": "claude --resume {sessionId}",
    "capture": {
      "planDirs": [
        "~/.claude/plans/",
        ".claude/plans/"
      ],
      "planTags": [
        "ultraplan"
      ],
      "rules": [
        {
          "event": "session_start",
          "scope": "this_agent",
          "when": {
            "transcript_meta_field_equals": {
              "path": "entrypoint",
              "value": "sdk-py"
            }
          },
          "action": "drop",
          "reason": "noninteractive-sdk",
          "trim": true
        },
        {
          "event": "session_start",
          "scope": "this_agent",
          "when": {
            "transcript_meta_field_equals": {
              "path": "entrypoint",
              "value": "sdk-ts"
            }
          },
          "action": "drop",
          "reason": "noninteractive-sdk",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "transcript_meta_field_equals": {
              "path": "entrypoint",
              "value": "sdk-py"
            }
          },
          "action": "drop",
          "reason": "noninteractive-sdk",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "transcript_meta_field_equals": {
              "path": "entrypoint",
              "value": "sdk-ts"
            }
          },
          "action": "drop",
          "reason": "noninteractive-sdk",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_starts_with": "<command-message>"
          },
          "action": "drop",
          "reason": "claude-code-slash-command-dispatch",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_starts_with": "<command-name>"
          },
          "action": "drop",
          "reason": "claude-code-builtin-command-dispatch",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_starts_with": "<local-command-stdout>"
          },
          "action": "drop",
          "reason": "claude-code-builtin-command-stdout",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_starts_with": "<<autonomous-loop"
          },
          "action": "classify",
          "reason": "claude-code-autonomous-loop",
          "trim": true,
          "set_origin": "system"
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_envelope_tag_in": [
              "agent-message",
              "teammate-message"
            ]
          },
          "action": "classify",
          "reason": "claude-code-agent-envelope",
          "trim": true,
          "set_origin": "agent_dispatch"
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_envelope_tag_in": [
              "task-notification",
              "system-reminder",
              "skill",
              "environment_context",
              "persisted-output",
              "local-command-caveat"
            ]
          },
          "action": "classify",
          "reason": "claude-code-system-envelope",
          "trim": true,
          "set_origin": "system"
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "record_field_equals": {
              "path": "isCompactSummary",
              "value": true
            }
          },
          "action": "classify",
          "reason": "claude-code-compact-continuation-summary",
          "trim": true,
          "set_origin": "system"
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_is_enclosing_envelope": true
          },
          "action": "classify",
          "reason": "claude-code-unknown-envelope",
          "trim": true,
          "set_origin": "system"
        }
      ],
      "prompts": {
        "shapes": [
          {
            "name": "agent_message",
            "match": {
              "type": "user",
              "fieldNotEquals": {
                "isMeta": true
              }
            },
            "textAt": "message.content",
            "textStartsWith": "<agent-message",
            "dedupeBy": "uuid"
          },
          {
            "name": "teammate_message",
            "match": {
              "type": "user",
              "fieldNotEquals": {
                "isMeta": true
              }
            },
            "textAt": "message.content",
            "textStartsWith": "<teammate-message",
            "dedupeBy": "uuid"
          },
          {
            "name": "user_prompt",
            "match": {
              "type": "user",
              "hasField": "promptId",
              "fieldNotEquals": {
                "isMeta": true
              }
            },
            "textAt": "message.content",
            "dedupeBy": "promptId"
          },
          {
            "name": "queued_command",
            "match": {
              "type": "attachment",
              "fieldEquals": {
                "attachment.type": "queued_command"
              }
            },
            "textAt": "attachment.prompt",
            "dedupeBy": "uuid"
          }
        ],
        "resetBoundaries": [
          {
            "match": {
              "type": "assistant",
              "fieldEquals": {
                "message.stop_reason": "end_turn"
              }
            }
          }
        ],
        "interruptMarker": "[Request interrupted by user for tool use]"
      },
      "transcriptDiscovery": {
        "roots": [
          "~/.claude/projects"
        ],
        "patterns": [
          "*/{sessionId}.jsonl"
        ],
        "transcriptCwdPath": "cwd",
        "retention": "harness"
      },
      "subagentTranscripts": "{sessionId}/subagents/*.jsonl",
      "sessionContinuation": {
        "parentSessionIdPath": "session_id",
        "defaultReason": "fork",
        "markers": [
          {
            "recordFlagPath": "isCompactSummary",
            "reason": "compact continuation"
          }
        ]
      },
      "compactionStart": {
        "field": "source",
        "equals": "compact"
      },
      "anyAgentRules": true
    },
    "registration": {
      "hooksTarget": ".claude/settings.json",
      "memberHooksTarget": ".claude/settings.local.json",
      "globalHooksTarget": "~/.claude/settings.json",
      "globalMcpTarget": [
        {
          "path": "~/.claude.json"
        }
      ],
      "globalSkillsTarget": "~/.claude/skills",
      "globalSettingsTarget": "~/.claude/settings.json",
      "hooksFormat": "json",
      "mcpTarget": ".mcp.json",
      "mcpFormat": "json",
      "mcpServersKey": "mcpServers",
      "memberMcpHeadersHelperKey": "headersHelper",
      "skillsTarget": ".claude/skills",
      "settingsTarget": ".claude/settings.json",
      "settingsFormat": "json",
      "instructionsFile": "CLAUDE.md"
    },
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": true,
      "postToolUseInjection": false,
      "turnRowSource": "transcript",
      "transcriptFidelity": "full",
      "canopyReadTools": [
        {
          "tool": "Read",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": false
        }
      ],
      "pathBearingTools": [
        {
          "tool": "Read",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "Write",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "Edit",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "MultiEdit",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "NotebookEdit",
          "pathField": "notebook_path",
          "pathKind": "file",
          "mutates": true
        }
      ]
    },
    "hooks": {
      "Stop": {
        "phases": [
          "response",
          "transcript"
        ]
      }
    },
    "runner": {
      "order": 1,
      "asking": {
        "kind": "native"
      },
      "credential": {
        "provider": "anthropic",
        "slot": "anthropic",
        "variables": [
          "CLAUDE_CODE_OAUTH_TOKEN",
          "ANTHROPIC_API_KEY"
        ],
        "accepts": [
          "subscription",
          "api-key"
        ]
      },
      "profile": {
        "models": {
          "low": "haiku",
          "default": "sonnet",
          "high": "opus"
        },
        "efforts": {
          "low": "low",
          "default": "medium",
          "high": "high"
        },
        "allowedEfforts": [
          "low",
          "medium",
          "high",
          "xhigh"
        ],
        "modelPattern": "^(haiku|sonnet|opus|fable|claude-[A-Za-z0-9][A-Za-z0-9._-]{0,240})$",
        "modelHint": "Use haiku, sonnet, opus, fable, or a claude-* model ID.",
        "modelFamilies": [
          "haiku",
          "sonnet",
          "opus",
          "fable"
        ],
        "modelFamilyPrefix": "claude-"
      },
      "worker": {
        "binary": "claude",
        "launch": {
          "kind": "native"
        },
        "login": {
          "kind": "file-or-command",
          "path": "~/.claude/.credentials.json",
          "requires": [
            "claudeAiOauth",
            "accessToken"
          ],
          "args": [
            "auth",
            "status"
          ]
        },
        "isolation": {
          "kind": "flag",
          "args": [
            "--strict-mcp-config"
          ]
        },
        "sourceGit": "shim",
        "modelSetting": "flag",
        "models": {
          "kind": "exchange",
          "args": [
            "-p",
            "--input-format",
            "stream-json",
            "--output-format",
            "stream-json",
            "--verbose",
            "--strict-mcp-config",
            "--setting-sources",
            "project,local",
            "--no-session-persistence"
          ],
          "send": [
            {
              "type": "control_request",
              "request_id": "myco-models",
              "request": {
                "subtype": "initialize"
              }
            }
          ],
          "answer": {
            "where": {
              "type": "control_response",
              "response.request_id": "myco-models"
            },
            "list": "response.response.models"
          },
          "fields": {
            "id": "value",
            "label": "displayName",
            "resolvesTo": "resolvedModel",
            "efforts": "supportedEffortLevels"
          }
        },
        "steps": [
          {
            "tool": "Read",
            "kind": "read",
            "target": [
              "file_path"
            ]
          },
          {
            "tool": "LS",
            "kind": "read",
            "target": [
              "path"
            ]
          },
          {
            "tool": "NotebookRead",
            "kind": "read",
            "target": [
              "notebook_path"
            ]
          },
          {
            "tool": "Glob",
            "kind": "search",
            "target": [
              "path"
            ]
          },
          {
            "tool": "Grep",
            "kind": "search",
            "target": [
              "path"
            ]
          },
          {
            "tool": "Write",
            "kind": "edit",
            "target": [
              "file_path"
            ]
          },
          {
            "tool": "Edit",
            "kind": "edit",
            "target": [
              "file_path"
            ]
          },
          {
            "tool": "MultiEdit",
            "kind": "edit",
            "target": [
              "file_path"
            ]
          },
          {
            "tool": "NotebookEdit",
            "kind": "edit",
            "target": [
              "notebook_path"
            ]
          },
          {
            "tool": "Bash",
            "kind": "command",
            "target": [
              "command"
            ]
          },
          {
            "tool": "WebFetch",
            "kind": "fetch",
            "target": [
              "url"
            ]
          },
          {
            "tool": "WebSearch",
            "kind": "fetch",
            "target": [
              "query"
            ]
          },
          {
            "toolPrefix": "mcp__myco__",
            "kind": "myco",
            "target": [
              "op"
            ]
          }
        ],
        "stepTool": "name",
        "accounting": {
          "reported": "claude-stream",
          "modelSources": [
            "system.init.model",
            "assistant.message.model",
            "result.modelUsage"
          ],
          "launchFallback": "none",
          "primarySources": [
            "system.init.model"
          ],
          "modelVariants": [
            {
              "suffix": "[1m]",
              "context": "1m"
            }
          ],
          "zeroDollars": "reported",
          "provider": {
            "kind": "environment",
            "default": "anthropic",
            "selectors": [
              {
                "variable": "CLAUDE_CODE_USE_BEDROCK",
                "provider": "bedrock"
              },
              {
                "variable": "CLAUDE_CODE_USE_VERTEX",
                "provider": "vertex"
              },
              {
                "variable": "CLAUDE_CODE_USE_FOUNDRY",
                "provider": "foundry"
              }
            ],
            "unknownIfSet": [
              "ANTHROPIC_BASE_URL",
              "CLAUDE_CODE_CLIENT_DATA_URL"
            ]
          },
          "tokenScope": "attempt"
        }
      }
    }
  },
  {
    "name": "cline",
    "displayName": "Cline",
    "binary": "cline",
    "configDir": ".cline",
    "detectionDir": "~/.cline",
    "pluginRootEnvVar": "CLINE_PLUGIN_ROOT",
    "hookFields": {
      "sessionId": "conversationId",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": "tool_output"
    },
    "resumeCommand": "cline --id {sessionId}",
    "capture": {
      "planDirs": [],
      "planTags": [],
      "rules": [
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_starts_with": "<user_input mode=\"act\">"
          },
          "action": "rewrite_prompt",
          "reason": "strip Cline act user_input envelope",
          "strip_envelope": {
            "open": "<user_input mode=\"act\">",
            "close": "</user_input>"
          },
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_starts_with": "<user_input mode=\"plan\">"
          },
          "action": "rewrite_prompt",
          "reason": "strip Cline plan user_input envelope",
          "strip_envelope": {
            "open": "<user_input mode=\"plan\">",
            "close": "</user_input>"
          },
          "trim": true
        }
      ],
      "transcriptDiscovery": {
        "roots": [
          "@memberHome/member/transcripts/cline"
        ],
        "patterns": [
          "{sessionId}.jsonl"
        ],
        "transcriptCwdPath": "cwd",
        "retention": "member"
      }
    },
    "registration": {
      "hooksTarget": ".cline/plugins/myco.ts",
      "memberHooksTarget": ".cline/plugins/myco.ts",
      "globalHooksTarget": "~/.cline/plugins/myco.ts",
      "globalMcpTarget": [
        {
          "path": "~/.cline/data/settings/cline_mcp_settings.json"
        },
        {
          "path": "~/.cline/mcp.json"
        }
      ],
      "globalSkillsTarget": "~/.cline/skills",
      "hooksFormat": "plugin-file",
      "hookResponse": {
        "format": "json",
        "fieldNames": {
          "additionalContext": "additionalContext",
          "promptId": "promptId"
        }
      },
      "mcpTarget": ".cline/mcp.json",
      "mcpFormat": "json",
      "mcpServersKey": "mcpServers",
      "skillsTarget": ".cline/skills",
      "settingsFormat": "json"
    },
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false,
      "postToolUseInjection": false,
      "turnRowSource": "transcript",
      "transcriptFidelity": "full",
      "canopyReadTools": [],
      "pathBearingTools": [
        {
          "tool": "read_files",
          "pathField": "path",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "editor",
          "pathField": "path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "apply_patch",
          "pathField": "input",
          "extract": "patch",
          "mutates": true
        },
        {
          "tool": "run_commands",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        },
        {
          "tool": "run_commands",
          "pathField": "cmd",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        }
      ]
    },
    "hooks": {}
  },
  {
    "name": "codex",
    "displayName": "Codex",
    "binary": "codex",
    "configDir": ".codex",
    "detectionDir": "~/.codex",
    "pluginRootEnvVar": "CODEX_PLUGIN_ROOT",
    "settingsPath": ".codex/config.toml",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "resumeCommand": "codex resume {sessionId}",
    "capture": {
      "planDirs": [],
      "planTags": [
        "proposed_plan"
      ],
      "rules": [
        {
          "event": "session_start",
          "scope": "any_agent",
          "when": {
            "transcript_path_missing": true
          },
          "action": "drop",
          "reason": "ephemeral-sub-invocation",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "any_agent",
          "when": {
            "transcript_path_missing": true
          },
          "action": "drop",
          "reason": "ephemeral-sub-invocation",
          "trim": true
        },
        {
          "event": "session_start",
          "scope": "this_agent",
          "when": {
            "transcript_meta_field_exists": "source.subagent"
          },
          "action": "drop",
          "reason": "subagent-thread-spawn",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "transcript_meta_field_exists": "source.subagent"
          },
          "action": "drop",
          "reason": "subagent-thread-spawn",
          "trim": true
        },
        {
          "event": "session_start",
          "scope": "this_agent",
          "when": {
            "transcript_meta_field_equals": {
              "path": "source",
              "value": "exec"
            }
          },
          "action": "drop",
          "reason": "noninteractive-exec",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "transcript_meta_field_equals": {
              "path": "source",
              "value": "exec"
            }
          },
          "action": "drop",
          "reason": "noninteractive-exec",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_starts_with": "# AGENTS.md instructions"
          },
          "action": "drop",
          "reason": "agents-md-context-injection",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_contains": "# AGENTS.md instructions",
            "prompt_envelope_tag_in": [
              "recommended_plugins"
            ]
          },
          "action": "drop",
          "reason": "agents-md-context-injection-enveloped",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_envelope_tag_in": [
              "subagent_notification"
            ]
          },
          "action": "classify",
          "reason": "codex-agent-envelope",
          "trim": true,
          "set_origin": "agent_dispatch"
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_envelope_tag_in": [
              "environment_context",
              "skill"
            ]
          },
          "action": "classify",
          "reason": "codex-system-envelope",
          "trim": true,
          "set_origin": "system"
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_contains": "## My request for Codex:"
          },
          "action": "rewrite_prompt",
          "reason": "codex-desktop-file-preamble",
          "extract_after": "## My request for Codex:\n",
          "trim": true
        },
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_is_enclosing_envelope": true
          },
          "action": "classify",
          "reason": "codex-unknown-envelope",
          "trim": true,
          "set_origin": "system"
        }
      ],
      "prompts": {
        "shapes": [
          {
            "name": "user_message",
            "match": {
              "type": "response_item",
              "fieldEquals": {
                "payload.type": "message",
                "payload.role": "user"
              }
            },
            "textAt": "payload.content",
            "textExtraction": "joined_text_parts"
          }
        ],
        "resetBoundaries": [
          {
            "match": {
              "type": "turn_context"
            },
            "changeOn": "payload.turn_id"
          }
        ],
        "interruptMarker": "<turn_aborted>"
      },
      "transcriptDiscovery": {
        "roots": [
          "~/.codex/sessions"
        ],
        "patterns": [
          "*/*/*/rollout-*-{sessionId}.jsonl"
        ],
        "sessionIdPattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
        "transcriptCwdPath": "payload.cwd",
        "transcriptRepositoryPath": "payload.git.repository_url",
        "retention": "harness"
      },
      "subagentParentPath": "source.subagent.thread_spawn.parent_thread_id",
      "subagentThreadIdPath": "id",
      "subagentLabelPath": "source.subagent.thread_spawn"
    },
    "registration": {
      "hooksTarget": ".codex/hooks.json",
      "memberHooksTarget": ".codex/hooks.json",
      "globalHooksTarget": "~/.codex/hooks.json",
      "globalMcpTarget": [
        {
          "path": "~/.codex/config.toml"
        }
      ],
      "globalSkillsTarget": "~/.agents/skills",
      "retiredGlobalSkillsTargets": [
        "~/.codex/skills"
      ],
      "globalSettingsTarget": "~/.codex/config.toml",
      "hooksFormat": "json",
      "mcpTarget": ".codex/config.toml",
      "mcpFormat": "toml",
      "mcpServersKey": "mcpServers",
      "memberMcpHeadersHelperKey": "http_headers_helper",
      "memberMcpGlobalMerge": true,
      "skillsTarget": ".agents/skills",
      "settingsTarget": ".codex/config.toml",
      "settingsFormat": "toml"
    },
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": true,
      "postToolUseInjection": false,
      "turnRowSource": "transcript",
      "transcriptFidelity": "no_tool_results",
      "canopyReadTools": [
        {
          "tool": "Bash",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        }
      ],
      "pathBearingTools": [
        {
          "tool": "Bash",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        },
        {
          "tool": "apply_patch",
          "pathField": "command",
          "extract": "patch",
          "mutates": true
        }
      ]
    },
    "hooks": {
      "Stop": {
        "phases": [
          "response",
          "transcript"
        ]
      }
    },
    "runner": {
      "order": 2,
      "asking": {
        "kind": "sandbox"
      },
      "credential": {
        "provider": "openai",
        "slot": "own",
        "ownSlotLabel": "Codex (OpenAI)",
        "variables": [
          "OPENAI_API_KEY"
        ]
      },
      "profile": {
        "models": {
          "low": null,
          "default": null,
          "high": null
        },
        "efforts": {
          "low": "low",
          "default": "medium",
          "high": "high"
        },
        "allowedEfforts": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ],
        "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$",
        "modelHint": "Use a Codex model ID. An unset model holds runs at this tier."
      },
      "worker": {
        "binary": "codex",
        "launch": {
          "kind": "native"
        },
        "login": {
          "kind": "file",
          "path": "~/.codex/auth.json",
          "requires": [
            "OPENAI_API_KEY",
            "tokens",
            "personal_access_token"
          ]
        },
        "isolation": {
          "kind": "home",
          "env": "CODEX_HOME"
        },
        "sourceGit": "none",
        "modelSetting": "config",
        "models": {
          "kind": "exchange",
          "args": [
            "app-server"
          ],
          "send": [
            {
              "jsonrpc": "2.0",
              "id": 1,
              "method": "initialize",
              "params": {
                "clientInfo": {
                  "name": "myco",
                  "version": "1"
                }
              }
            },
            {
              "jsonrpc": "2.0",
              "method": "initialized"
            },
            {
              "jsonrpc": "2.0",
              "id": 2,
              "method": "model/list",
              "params": {}
            }
          ],
          "answer": {
            "where": {
              "id": 2
            },
            "list": "result.data"
          },
          "page": {
            "cursor": "result.nextCursor",
            "param": "params.cursor"
          },
          "fields": {
            "id": "id",
            "label": "displayName",
            "isDefault": "isDefault",
            "upgrade": "upgrade",
            "efforts": "supportedReasoningEfforts[].reasoningEffort"
          }
        },
        "steps": [
          {
            "tool": "command_execution",
            "kind": "command",
            "target": [
              "command"
            ]
          },
          {
            "tool": "file_change",
            "kind": "edit",
            "target": [
              "changes.0.path"
            ]
          },
          {
            "tool": "web_search",
            "kind": "fetch",
            "target": [
              "query"
            ]
          },
          {
            "category": "mcp",
            "kind": "myco",
            "target": [
              "op"
            ]
          }
        ],
        "stepTool": "name",
        "accounting": {
          "reported": "codex-session",
          "modelSources": [
            "session.turn_context.model"
          ],
          "launchFallback": "resolved-config",
          "provider": {
            "kind": "session-config",
            "default": "openai"
          },
          "tokenScope": "attempt"
        }
      }
    }
  },
  {
    "name": "copilot",
    "displayName": "GitHub Copilot",
    "binary": "copilot",
    "configDir": ".vscode",
    "detectionDir": "~/.copilot",
    "pluginRootEnvVar": "COPILOT_PLUGIN_ROOT",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": "tool_response"
    },
    "capture": {
      "planDirs": [],
      "planTags": [],
      "rules": [],
      "transcriptDiscovery": {
        "roots": [
          "~/.copilot/session-state"
        ],
        "patterns": [
          "{sessionId}/events.jsonl"
        ],
        "retention": "harness"
      }
    },
    "registration": {
      "hooksTarget": ".github/hooks/myco-hooks.json",
      "globalHooksTarget": "~/.copilot/hooks/myco-hooks.json",
      "globalMcpTarget": [
        {
          "path": "~/.copilot/mcp-config.json",
          "serversKey": "mcpServers"
        },
        {
          "path": "~/Library/Application Support/Code/User/mcp.json",
          "serversKey": "servers"
        }
      ],
      "globalSkillsTarget": "~/.agents/skills",
      "retiredGlobalSkillsTargets": [
        "~/.copilot/skills"
      ],
      "globalSettingsTarget": "~/.copilot/hooks/myco-hooks.json",
      "hooksFormat": "json",
      "hookResponse": {
        "format": "plain-text",
        "shapes": {
          "SubagentStart": "flat"
        }
      },
      "mcpTarget": ".vscode/mcp.json",
      "mcpFormat": "json",
      "mcpServersKey": "mcpServers",
      "skillsTarget": ".agents/skills",
      "settingsTarget": ".vscode/settings.json",
      "settingsFormat": "json",
      "instructionsFile": ".github/copilot-instructions.md"
    },
    "capabilities": {
      "preToolUseInjection": true,
      "sessionStartInjection": true,
      "subagentStartInjection": true,
      "postToolUseInjection": false,
      "turnRowSource": "hook",
      "transcriptFidelity": "full",
      "canopyReadTools": [
        {
          "tool": "read_file",
          "pathField": "filePath",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "run_in_terminal",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        },
        {
          "tool": "view",
          "pathField": "path",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "bash",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        },
        {
          "tool": "powershell",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl",
            "Get-Content",
            "gc"
          ],
          "mutates": false
        },
        {
          "tool": "grep",
          "pathField": "path",
          "pathKind": "file",
          "mutates": false
        }
      ],
      "pathBearingTools": [
        {
          "tool": "read_file",
          "pathField": "filePath",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "run_in_terminal",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        },
        {
          "tool": "replace_string_in_file",
          "pathField": "filePath",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "create_file",
          "pathField": "filePath",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "apply_patch",
          "pathField": "filePath",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "view",
          "pathField": "path",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "bash",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        },
        {
          "tool": "powershell",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl",
            "Get-Content",
            "gc"
          ],
          "mutates": false
        },
        {
          "tool": "edit",
          "pathField": "path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "create",
          "pathField": "path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "grep",
          "pathField": "path",
          "pathKind": "file",
          "mutates": false
        }
      ]
    },
    "hooks": {
      "Stop": {
        "phases": [
          "response",
          "transcript"
        ]
      }
    }
  },
  {
    "name": "cursor",
    "displayName": "Cursor",
    "binary": "cursor",
    "configDir": ".cursor",
    "detectionDir": "~/.cursor",
    "pluginRootEnvVar": "CURSOR_PLUGIN_ROOT",
    "settingsPath": ".cursor/mcp.json",
    "hookFields": {
      "sessionId": [
        "conversation_id",
        "session_id"
      ],
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ],
      "sessionIdFromTranscriptPath": [
        "/agent-transcripts/([^/]+)/\\1\\.jsonl$",
        "(?:^|/)([^/.]+)\\.txt$"
      ]
    },
    "projectDirEnvVar": "CURSOR_PROJECT_DIR",
    "capture": {
      "planDirs": [
        "~/.cursor/plans/",
        ".cursor/plans/"
      ],
      "planTags": [],
      "rules": [
        {
          "event": "user_prompt",
          "scope": "this_agent",
          "when": {
            "prompt_starts_with": "<user_query>"
          },
          "action": "rewrite_prompt",
          "reason": "strip Cursor user_query envelope",
          "strip_envelope": {
            "open": "<user_query>",
            "close": "</user_query>"
          },
          "trim": true
        }
      ],
      "transcriptDiscovery": {
        "roots": [
          "~/.cursor/projects"
        ],
        "patterns": [
          "*/agent-transcripts/{sessionId}.txt",
          "*/agent-transcripts/{sessionId}/{sessionId}.jsonl"
        ],
        "retention": "harness"
      }
    },
    "registration": {
      "hooksTarget": ".cursor/hooks.json",
      "memberHooksTarget": ".cursor/hooks.json",
      "globalHooksTarget": "~/.cursor/hooks.json",
      "globalMcpTarget": [
        {
          "path": "~/.cursor/mcp.json"
        }
      ],
      "globalSkillsTarget": "~/.agents/skills",
      "retiredGlobalSkillsTargets": [
        "~/.cursor/skills"
      ],
      "globalSettingsTarget": "~/.cursor/hooks.json",
      "hooksFormat": "json",
      "hooksConfigVersion": 1,
      "hookResponse": {
        "format": "json",
        "fieldNames": {
          "additionalContext": "additional_context",
          "continue": "continue",
          "stopReason": "stop_reason",
          "userMessage": "user_message",
          "followupMessage": "followup_message",
          "systemMessage": "system_message"
        }
      },
      "mcpTarget": ".cursor/mcp.json",
      "mcpFormat": "json",
      "mcpServersKey": "mcpServers",
      "skillsTarget": ".agents/skills",
      "retiredSkillsTargets": [
        ".cursor/skills"
      ],
      "settingsTarget": ".cursor/settings.json",
      "settingsFormat": "json"
    },
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false,
      "postToolUseInjection": true,
      "turnRowSource": "transcript",
      "transcriptFidelity": "no_tool_results",
      "canopyReadTools": [],
      "pathBearingTools": [
        {
          "tool": "Read",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "Write",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "Edit",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "MultiEdit",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "Delete",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "Grep",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "Shell",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        }
      ]
    },
    "hooks": {},
    "runner": {
      "order": 4,
      "asking": {
        "kind": "run-home",
        "env": "CURSOR_CONFIG_DIR"
      },
      "credential": {
        "provider": "anthropic",
        "slot": "anthropic",
        "variables": [
          "ANTHROPIC_API_KEY"
        ]
      },
      "profile": {
        "models": {
          "low": null,
          "default": null,
          "high": null
        },
        "efforts": {
          "low": "low",
          "default": "medium",
          "high": "high"
        },
        "allowedEfforts": [],
        "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$",
        "modelHint": "Model selection is unavailable for this agent."
      },
      "worker": {
        "binary": "cursor-agent",
        "launch": {
          "kind": "subcommand",
          "args": [
            "acp"
          ]
        },
        "login": {
          "kind": "command",
          "args": [
            "status"
          ]
        },
        "isolation": {
          "kind": "additive"
        },
        "sourceGit": "none",
        "modelSetting": "none",
        "steps": [
          {
            "category": "read",
            "kind": "read",
            "target": [
              "locations.0.path",
              "rawInput.path",
              "rawInput.filePath",
              "rawInput.file_path"
            ]
          },
          {
            "category": "search",
            "kind": "search",
            "target": [
              "locations.0.path",
              "rawInput.path"
            ]
          },
          {
            "category": "edit",
            "kind": "edit",
            "target": [
              "locations.0.path",
              "rawInput.path",
              "rawInput.filePath",
              "rawInput.file_path"
            ]
          },
          {
            "category": "delete",
            "kind": "edit",
            "target": [
              "locations.0.path",
              "rawInput.path"
            ]
          },
          {
            "category": "move",
            "kind": "edit",
            "target": [
              "locations.0.path",
              "rawInput.path"
            ]
          },
          {
            "category": "execute",
            "kind": "command",
            "target": [
              "rawInput.command",
              "rawInput.cmd"
            ]
          },
          {
            "category": "fetch",
            "kind": "fetch",
            "target": [
              "rawInput.url",
              "rawInput.query"
            ]
          }
        ],
        "stepTool": "category",
        "accounting": {
          "reported": "acp-session",
          "modelSources": [
            "session.models",
            "session.configOptions",
            "session.currentModelId"
          ],
          "launchFallback": "none",
          "zeroDollars": "unavailable",
          "provider": {
            "kind": "unavailable"
          },
          "tokenScope": "unverified"
        }
      }
    }
  },
  {
    "name": "opencode",
    "displayName": "OpenCode",
    "binary": "opencode",
    "configDir": ".opencode",
    "detectionDir": "~/.config/opencode",
    "pluginRootEnvVar": "OPENCODE_PLUGIN_ROOT",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "resumeCommand": "opencode --session {sessionId}",
    "capture": {
      "planDirs": [
        ".opencode/plans/"
      ],
      "planTags": [],
      "rules": [],
      "transcriptDiscovery": {
        "roots": [
          "@memberHome/member/transcripts/opencode"
        ],
        "patterns": [
          "{sessionId}.jsonl"
        ],
        "transcriptCwdPath": "cwd",
        "retention": "member"
      }
    },
    "registration": {
      "hooksTarget": ".opencode/plugins/myco.ts",
      "memberHooksTarget": ".opencode/plugins/myco.ts",
      "globalHooksTarget": "~/.config/opencode/plugins/myco.ts",
      "globalMcpTarget": [
        {
          "path": "~/.config/opencode/opencode.json"
        }
      ],
      "globalSkillsTarget": "~/.agents/skills",
      "retiredGlobalSkillsTargets": [
        "~/.config/opencode/skills"
      ],
      "hooksFormat": "plugin-file",
      "hookResponse": {
        "format": "json",
        "fieldNames": {
          "additionalContext": "additionalContext",
          "promptId": "promptId"
        }
      },
      "pluginPackageTarget": ".opencode/package.json",
      "mcpTarget": "opencode.json",
      "mcpFormat": "json",
      "mcpServersKey": "mcp",
      "memberMcpGlobalMerge": true,
      "skillsTarget": ".agents/skills",
      "settingsTarget": "opencode.json",
      "settingsFormat": "json"
    },
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false,
      "postToolUseInjection": false,
      "turnRowSource": "transcript",
      "transcriptFidelity": "full",
      "canopyReadTools": [],
      "pathBearingTools": [
        {
          "tool": "read",
          "pathField": "filePath",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "write",
          "pathField": "filePath",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "edit",
          "pathField": "filePath",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "apply_patch",
          "pathField": "patchText",
          "extract": "patch",
          "mutates": true
        },
        {
          "tool": "bash",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        }
      ]
    },
    "hooks": {},
    "runner": {
      "order": 3,
      "asking": {
        "kind": "run-agent",
        "env": "OPENCODE_CONFIG_CONTENT",
        "extensionsOff": {
          "OPENCODE_PURE": "1"
        }
      },
      "credential": {
        "provider": "anthropic",
        "slot": "anthropic",
        "variables": [
          "ANTHROPIC_API_KEY"
        ]
      },
      "profile": {
        "models": {
          "low": null,
          "default": null,
          "high": null
        },
        "efforts": {
          "low": "low",
          "default": "medium",
          "high": "high"
        },
        "allowedEfforts": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ],
        "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._-]*/~?[A-Za-z0-9][A-Za-z0-9._:/-]{0,240}$",
        "modelHint": "Use provider/model. An unset model holds runs at this tier.",
        "providerAliasPattern": "^openrouter/~",
        "presets": [
          {
            "id": "openrouter-claude-latest",
            "provider": "openrouter",
            "label": "Newest Claude through OpenRouter",
            "description": "Haiku, Sonnet and Opus through OpenRouter, always the newest version.",
            "models": {
              "low": "openrouter/~anthropic/claude-haiku-latest",
              "default": "openrouter/~anthropic/claude-sonnet-latest",
              "high": "openrouter/~anthropic/claude-opus-latest"
            }
          }
        ]
      },
      "worker": {
        "binary": "opencode",
        "launch": {
          "kind": "subcommand",
          "args": [
            "acp"
          ]
        },
        "login": {
          "kind": "file",
          "path": "~/.local/share/opencode/auth.json",
          "requires": []
        },
        "isolation": {
          "kind": "additive"
        },
        "sourceGit": "shim",
        "modelSetting": "config",
        "models": {
          "kind": "command",
          "args": [
            "models"
          ],
          "format": "lines",
          "provider": "id-prefix"
        },
        "steps": [
          {
            "category": "read",
            "kind": "read",
            "target": [
              "locations.0.path",
              "rawInput.path",
              "rawInput.filePath",
              "rawInput.file_path"
            ]
          },
          {
            "category": "search",
            "kind": "search",
            "target": [
              "locations.0.path",
              "rawInput.path"
            ]
          },
          {
            "category": "edit",
            "kind": "edit",
            "target": [
              "locations.0.path",
              "rawInput.path",
              "rawInput.filePath",
              "rawInput.file_path"
            ]
          },
          {
            "category": "delete",
            "kind": "edit",
            "target": [
              "locations.0.path",
              "rawInput.path"
            ]
          },
          {
            "category": "move",
            "kind": "edit",
            "target": [
              "locations.0.path",
              "rawInput.path"
            ]
          },
          {
            "category": "execute",
            "kind": "command",
            "target": [
              "rawInput.command",
              "rawInput.cmd"
            ]
          },
          {
            "category": "fetch",
            "kind": "fetch",
            "target": [
              "rawInput.url",
              "rawInput.query"
            ]
          }
        ],
        "stepTool": "category",
        "accounting": {
          "reported": "acp-session",
          "modelSources": [
            "session.models",
            "session.configOptions",
            "session.currentModelId"
          ],
          "launchFallback": "none",
          "zeroDollars": "unavailable",
          "provider": {
            "kind": "model-prefix"
          },
          "tokenScope": "unverified",
          "lastResponseVersions": [
            "1.18.21",
            "1.18.29"
          ]
        }
      }
    }
  },
  {
    "name": "pi",
    "displayName": "Pi",
    "binary": "pi",
    "configDir": ".pi",
    "detectionDir": "~/.pi",
    "pluginRootEnvVar": "PI_PLUGIN_ROOT",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "capture": {
      "planDirs": [
        ".pi/plans/"
      ],
      "planTags": [],
      "rules": [],
      "transcriptDiscovery": {
        "roots": [
          "~/.pi/agent/sessions"
        ],
        "patterns": [
          "*/*_{sessionId}.jsonl"
        ],
        "sessionIdPattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
        "transcriptCwdPath": "cwd",
        "retention": "harness"
      }
    },
    "registration": {
      "hooksTarget": ".pi/extensions/myco/index.ts",
      "memberHooksTarget": ".pi/extensions/myco/index.ts",
      "memberProvisionNote": "Pi loads this project's Myco extension only after you trust the project in Pi (/trust).",
      "globalHooksTarget": "~/.pi/agent/extensions/myco/index.ts",
      "globalMcpTarget": null,
      "globalSkillsTarget": "~/.agents/skills",
      "retiredGlobalSkillsTargets": [
        "~/.pi/agent/skills"
      ],
      "hooksFormat": "plugin-file",
      "hookResponse": {
        "format": "json",
        "fieldNames": {
          "additionalContext": "additionalContext",
          "promptId": "promptId"
        }
      },
      "pluginPackageTarget": ".pi/extensions/myco/package.json",
      "mcpFormat": "json",
      "mcpServersKey": "mcpServers",
      "skillsTarget": ".agents/skills",
      "settingsFormat": "json"
    },
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false,
      "postToolUseInjection": false,
      "turnRowSource": "transcript",
      "transcriptFidelity": "full",
      "canopyReadTools": [],
      "pathBearingTools": [
        {
          "tool": "read",
          "pathField": "path",
          "pathKind": "file",
          "mutates": false
        },
        {
          "tool": "write",
          "pathField": "path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "edit",
          "pathField": "path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "bash",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        }
      ]
    },
    "hooks": {}
  },
  {
    "name": "windsurf",
    "displayName": "Windsurf",
    "binary": "windsurf",
    "configDir": ".windsurf",
    "detectionDir": "~/.codeium/windsurf",
    "pluginRootEnvVar": "WINDSURF_PLUGIN_ROOT",
    "hookFields": {
      "sessionId": "trajectory_id",
      "transcriptPath": "tool_info.transcript_path",
      "lastResponse": "tool_info.response",
      "prompt": "tool_info.user_prompt",
      "toolName": "agent_action_name",
      "toolInput": "tool_info",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "projectDirEnvVar": "WINDSURF_PROJECT_DIR",
    "capture": {
      "planDirs": [
        "~/.windsurf/plans/"
      ],
      "planTags": [],
      "rules": [],
      "transcriptDiscovery": {
        "roots": [
          "~/.windsurf/transcripts"
        ],
        "patterns": [
          "{sessionId}.jsonl"
        ],
        "retention": "harness"
      }
    },
    "registration": {
      "hooksTarget": ".windsurf/hooks.json",
      "globalHooksTarget": "~/.codeium/windsurf/hooks.json",
      "globalMcpTarget": [
        {
          "path": "~/.codeium/windsurf/mcp_config.json"
        }
      ],
      "globalSkillsTarget": "~/.agents/skills",
      "retiredGlobalSkillsTargets": [
        "~/.codeium/windsurf/skills"
      ],
      "globalSettingsTarget": null,
      "hooksFormat": "json",
      "mcpFormat": "json",
      "mcpServersKey": "mcpServers",
      "skillsTarget": ".agents/skills",
      "settingsTarget": ".windsurf/settings.json",
      "settingsFormat": "json"
    },
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": false,
      "subagentStartInjection": false,
      "postToolUseInjection": false,
      "turnRowSource": "hook",
      "transcriptFidelity": "full",
      "canopyReadTools": [],
      "pathBearingTools": [
        {
          "tool": "post_write_code",
          "pathField": "file_path",
          "pathKind": "file",
          "mutates": true
        },
        {
          "tool": "post_run_command",
          "pathField": "command",
          "extract": "shell-arg",
          "readCommands": [
            "cat",
            "head",
            "tail",
            "less",
            "more",
            "bat",
            "wc",
            "file",
            "nl",
            "sed",
            "awk",
            "grep",
            "rg",
            "perl"
          ],
          "mutates": false
        }
      ]
    },
    "hooks": {
      "post_cascade_response": {
        "phases": [
          "response"
        ]
      },
      "post_cascade_response_with_transcript": {
        "phases": [
          "transcript"
        ]
      }
    }
  }
] as const;
