// AUTO-GENERATED by scripts/gen-plugin-bundle.ts — DO NOT EDIT.
// Run `npm run codegen` after changing packages/myco/skills/.
export { SHIPPED_SKILL_FILES as BUNDLED_SKILLS } from '@goondocks/myco-shared/skills';
