// AUTO-GENERATED by scripts/gen-hook-config.ts — DO NOT EDIT.
import type { HarnessFacts } from './harnesses.js';

/** How a worker runs each harness, in the order it ranks them, as each manifest's `runner.worker` declares it. */
export const HARNESS_FACTS: readonly HarnessFacts[] = [
  {
    "id": "claude-code",
    "binary": "claude",
    "launch": {
      "kind": "native"
    },
    "isolation": {
      "kind": "flag",
      "args": [
        "--strict-mcp-config"
      ]
    },
    "sourceGit": "shim",
    "modelSetting": "flag",
    "models": {
      "kind": "exchange",
      "args": [
        "-p",
        "--input-format",
        "stream-json",
        "--output-format",
        "stream-json",
        "--verbose",
        "--strict-mcp-config",
        "--setting-sources",
        "project,local",
        "--no-session-persistence"
      ],
      "send": [
        {
          "type": "control_request",
          "request_id": "myco-models",
          "request": {
            "subtype": "initialize"
          }
        }
      ],
      "answer": {
        "where": {
          "type": "control_response",
          "response.request_id": "myco-models"
        },
        "list": "response.response.models"
      },
      "fields": {
        "id": "value",
        "label": "displayName",
        "resolvesTo": "resolvedModel",
        "efforts": "supportedEffortLevels"
      }
    },
    "steps": [
      {
        "tool": "Read",
        "kind": "read",
        "target": [
          "file_path"
        ]
      },
      {
        "tool": "LS",
        "kind": "search",
        "target": [
          "path"
        ]
      },
      {
        "tool": "NotebookRead",
        "kind": "read",
        "target": [
          "notebook_path"
        ]
      },
      {
        "tool": "Glob",
        "kind": "search",
        "target": [
          "path"
        ]
      },
      {
        "tool": "Grep",
        "kind": "search",
        "target": [
          "path"
        ]
      },
      {
        "tool": "Write",
        "kind": "edit",
        "target": [
          "file_path"
        ]
      },
      {
        "tool": "Edit",
        "kind": "edit",
        "target": [
          "file_path"
        ]
      },
      {
        "tool": "MultiEdit",
        "kind": "edit",
        "target": [
          "file_path"
        ]
      },
      {
        "tool": "NotebookEdit",
        "kind": "edit",
        "target": [
          "notebook_path"
        ]
      },
      {
        "tool": "Bash",
        "kind": "command",
        "target": [
          "command"
        ]
      },
      {
        "tool": "WebFetch",
        "kind": "fetch",
        "target": [
          "url"
        ]
      },
      {
        "tool": "WebSearch",
        "kind": "fetch",
        "target": [
          "query"
        ]
      },
      {
        "toolPrefix": "mcp__myco__",
        "kind": "myco",
        "target": [
          "op"
        ]
      },
      {
        "tool": "ToolSearch",
        "kind": "tool",
        "target": [],
        "words": "Looked up a tool"
      },
      {
        "tool": "TodoWrite",
        "kind": "tool",
        "target": [],
        "words": "Updated its to-do list"
      }
    ],
    "stepTool": "name",
    "notSteps": [
      "system/thinking_tokens",
      "rate_limit_event",
      "system/commands_changed",
      "system/status",
      "system/compact_boundary",
      "system/hook_started",
      "system/hook_progress",
      "system/hook_response"
    ],
    "accounting": {
      "reported": "claude-stream",
      "modelSources": [
        "system.init.model",
        "assistant.message.model",
        "result.modelUsage"
      ],
      "launchFallback": "none",
      "primarySources": [
        "system.init.model"
      ],
      "modelVariants": [
        {
          "suffix": "[1m]",
          "context": "1m"
        }
      ],
      "zeroDollars": "reported",
      "provider": {
        "kind": "environment",
        "default": "anthropic",
        "selectors": [
          {
            "variable": "CLAUDE_CODE_USE_BEDROCK",
            "provider": "bedrock"
          },
          {
            "variable": "CLAUDE_CODE_USE_VERTEX",
            "provider": "vertex"
          },
          {
            "variable": "CLAUDE_CODE_USE_FOUNDRY",
            "provider": "foundry"
          }
        ],
        "unknownIfSet": [
          "ANTHROPIC_BASE_URL",
          "CLAUDE_CODE_CLIENT_DATA_URL"
        ]
      },
      "tokenScope": "attempt"
    },
    "credential": {
      "kind": "file-or-command",
      "path": "~/.claude/.credentials.json",
      "requires": [
        "claudeAiOauth",
        "accessToken"
      ],
      "args": [
        "auth",
        "status"
      ]
    }
  },
  {
    "id": "codex",
    "binary": "codex",
    "launch": {
      "kind": "native"
    },
    "isolation": {
      "kind": "home",
      "env": "CODEX_HOME"
    },
    "sourceGit": "none",
    "modelSetting": "config",
    "models": {
      "kind": "exchange",
      "args": [
        "app-server"
      ],
      "send": [
        {
          "jsonrpc": "2.0",
          "id": 1,
          "method": "initialize",
          "params": {
            "clientInfo": {
              "name": "myco",
              "version": "1"
            }
          }
        },
        {
          "jsonrpc": "2.0",
          "method": "initialized"
        },
        {
          "jsonrpc": "2.0",
          "id": 2,
          "method": "model/list",
          "params": {}
        }
      ],
      "answer": {
        "where": {
          "id": 2
        },
        "list": "result.data"
      },
      "page": {
        "cursor": "result.nextCursor",
        "param": "params.cursor"
      },
      "fields": {
        "id": "id",
        "label": "displayName",
        "isDefault": "isDefault",
        "upgrade": "upgrade",
        "efforts": "supportedReasoningEfforts[].reasoningEffort"
      }
    },
    "steps": [
      {
        "tool": "command_execution",
        "kind": "command",
        "target": [
          "command"
        ]
      },
      {
        "tool": "file_change",
        "kind": "edit",
        "target": [
          "changes.0.path"
        ]
      },
      {
        "tool": "web_search",
        "kind": "fetch",
        "target": [
          "query"
        ]
      },
      {
        "category": "mcp",
        "kind": "myco",
        "target": [
          "op"
        ]
      }
    ],
    "stepTool": "name",
    "notSteps": [],
    "accounting": {
      "reported": "codex-session",
      "modelSources": [
        "session.turn_context.model"
      ],
      "launchFallback": "resolved-config",
      "provider": {
        "kind": "session-config",
        "default": "openai"
      },
      "tokenScope": "attempt"
    },
    "credential": {
      "kind": "file",
      "path": "~/.codex/auth.json",
      "requires": [
        "OPENAI_API_KEY",
        "tokens",
        "personal_access_token"
      ]
    }
  },
  {
    "id": "opencode",
    "binary": "opencode",
    "launch": {
      "kind": "subcommand",
      "args": [
        "acp"
      ]
    },
    "isolation": {
      "kind": "additive"
    },
    "sourceGit": "shim",
    "modelSetting": "config",
    "models": {
      "kind": "command",
      "args": [
        "models"
      ],
      "format": "lines",
      "provider": "id-prefix"
    },
    "steps": [
      {
        "toolPrefix": "mcp__myco__",
        "kind": "myco",
        "target": [
          "rawInput.op",
          "rawInput.args.op",
          "rawInput.arguments.op"
        ]
      },
      {
        "category": "read",
        "kind": "read",
        "target": [
          "locations.0.path",
          "rawInput.path",
          "rawInput.filePath",
          "rawInput.file_path"
        ]
      },
      {
        "category": "search",
        "kind": "search",
        "target": [
          "locations.0.path",
          "rawInput.path"
        ]
      },
      {
        "category": "edit",
        "kind": "edit",
        "target": [
          "locations.0.path",
          "rawInput.path",
          "rawInput.filePath",
          "rawInput.file_path"
        ]
      },
      {
        "category": "delete",
        "kind": "edit",
        "target": [
          "locations.0.path",
          "rawInput.path"
        ]
      },
      {
        "category": "move",
        "kind": "edit",
        "target": [
          "locations.0.path",
          "rawInput.path"
        ]
      },
      {
        "category": "execute",
        "kind": "command",
        "target": [
          "rawInput.command",
          "rawInput.cmd"
        ]
      },
      {
        "category": "fetch",
        "kind": "fetch",
        "target": [
          "rawInput.url",
          "rawInput.query"
        ]
      },
      {
        "category": "think",
        "kind": "tool",
        "target": [],
        "words": "Thought it through"
      },
      {
        "category": "switch_mode",
        "kind": "tool",
        "target": [],
        "words": "Switched its mode"
      }
    ],
    "stepTool": "category",
    "notSteps": [
      "session/update:plan",
      "session/update:available_commands_update",
      "session/update:current_mode_update",
      "session/update:user_message_chunk"
    ],
    "mycoCalls": {
      "names": [
        "mcp__myco__{tool}",
        "myco_{tool}"
      ],
      "input": {
        "server": "rawInput.providerIdentifier",
        "tool": "rawInput.toolName"
      }
    },
    "accounting": {
      "reported": "acp-session",
      "modelSources": [
        "session.models",
        "session.configOptions",
        "session.currentModelId"
      ],
      "launchFallback": "none",
      "zeroDollars": "unavailable",
      "provider": {
        "kind": "model-prefix"
      },
      "tokenScope": "unverified",
      "lastResponseVersions": [
        "1.18.21",
        "1.18.29"
      ]
    },
    "credential": {
      "kind": "file",
      "path": "~/.local/share/opencode/auth.json",
      "requires": []
    }
  },
  {
    "id": "cursor",
    "binary": "cursor-agent",
    "launch": {
      "kind": "subcommand",
      "args": [
        "acp"
      ]
    },
    "isolation": {
      "kind": "additive"
    },
    "sourceGit": "none",
    "modelSetting": "none",
    "steps": [
      {
        "toolPrefix": "mcp__myco__",
        "kind": "myco",
        "target": [
          "rawInput.op",
          "rawInput.args.op",
          "rawInput.arguments.op"
        ]
      },
      {
        "category": "read",
        "kind": "read",
        "target": [
          "locations.0.path",
          "rawInput.path",
          "rawInput.filePath",
          "rawInput.file_path"
        ]
      },
      {
        "category": "search",
        "kind": "search",
        "target": [
          "locations.0.path",
          "rawInput.path"
        ]
      },
      {
        "category": "edit",
        "kind": "edit",
        "target": [
          "locations.0.path",
          "rawInput.path",
          "rawInput.filePath",
          "rawInput.file_path"
        ]
      },
      {
        "category": "delete",
        "kind": "edit",
        "target": [
          "locations.0.path",
          "rawInput.path"
        ]
      },
      {
        "category": "move",
        "kind": "edit",
        "target": [
          "locations.0.path",
          "rawInput.path"
        ]
      },
      {
        "category": "execute",
        "kind": "command",
        "target": [
          "rawInput.command",
          "rawInput.cmd"
        ]
      },
      {
        "category": "fetch",
        "kind": "fetch",
        "target": [
          "rawInput.url",
          "rawInput.query"
        ]
      },
      {
        "category": "think",
        "kind": "tool",
        "target": [],
        "words": "Thought it through"
      },
      {
        "category": "switch_mode",
        "kind": "tool",
        "target": [],
        "words": "Switched its mode"
      }
    ],
    "stepTool": "category",
    "notSteps": [
      "session/update:plan",
      "session/update:available_commands_update",
      "session/update:current_mode_update",
      "session/update:user_message_chunk"
    ],
    "mycoCalls": {
      "names": [
        "mcp__myco__{tool}",
        "myco_{tool}"
      ],
      "input": {
        "server": "rawInput.providerIdentifier",
        "tool": "rawInput.toolName"
      }
    },
    "accounting": {
      "reported": "acp-session",
      "modelSources": [
        "session.models",
        "session.configOptions",
        "session.currentModelId"
      ],
      "launchFallback": "none",
      "zeroDollars": "unavailable",
      "provider": {
        "kind": "unavailable"
      },
      "tokenScope": "unverified"
    },
    "credential": {
      "kind": "command",
      "args": [
        "status"
      ]
    }
  },
  {
    "id": "antigravity",
    "binary": "agy",
    "launch": {
      "kind": "sidecar",
      "binary": "agy_acp_server.par"
    },
    "isolation": {
      "kind": "additive"
    },
    "sourceGit": "none",
    "modelSetting": "none",
    "steps": [
      {
        "toolPrefix": "mcp__myco__",
        "kind": "myco",
        "target": [
          "rawInput.op",
          "rawInput.args.op",
          "rawInput.arguments.op"
        ]
      },
      {
        "category": "read",
        "kind": "read",
        "target": [
          "locations.0.path",
          "rawInput.path",
          "rawInput.filePath",
          "rawInput.file_path"
        ]
      },
      {
        "category": "search",
        "kind": "search",
        "target": [
          "locations.0.path",
          "rawInput.path"
        ]
      },
      {
        "category": "edit",
        "kind": "edit",
        "target": [
          "locations.0.path",
          "rawInput.path",
          "rawInput.filePath",
          "rawInput.file_path"
        ]
      },
      {
        "category": "delete",
        "kind": "edit",
        "target": [
          "locations.0.path",
          "rawInput.path"
        ]
      },
      {
        "category": "move",
        "kind": "edit",
        "target": [
          "locations.0.path",
          "rawInput.path"
        ]
      },
      {
        "category": "execute",
        "kind": "command",
        "target": [
          "rawInput.command",
          "rawInput.cmd"
        ]
      },
      {
        "category": "fetch",
        "kind": "fetch",
        "target": [
          "rawInput.url",
          "rawInput.query"
        ]
      },
      {
        "category": "think",
        "kind": "tool",
        "target": [],
        "words": "Thought it through"
      },
      {
        "category": "switch_mode",
        "kind": "tool",
        "target": [],
        "words": "Switched its mode"
      }
    ],
    "stepTool": "category",
    "notSteps": [
      "session/update:plan",
      "session/update:available_commands_update",
      "session/update:current_mode_update",
      "session/update:user_message_chunk"
    ],
    "mycoCalls": {
      "names": [
        "mcp__myco__{tool}",
        "myco_{tool}"
      ],
      "input": {
        "server": "rawInput.providerIdentifier",
        "tool": "rawInput.toolName"
      }
    },
    "accounting": {
      "reported": "acp-session",
      "modelSources": [
        "session.models",
        "session.configOptions",
        "session.currentModelId"
      ],
      "launchFallback": "none",
      "zeroDollars": "unavailable",
      "provider": {
        "kind": "unavailable"
      },
      "tokenScope": "unverified"
    },
    "credential": {
      "kind": "file",
      "path": "~/.gemini/antigravity-cli/settings.json",
      "requires": []
    }
  }
];
