// AUTO-GENERATED by scripts/gen-hook-config.ts — DO NOT EDIT.
import type { HarnessFacts } from './harnesses.js';

/** How a worker runs each harness, in the order it ranks them, as each manifest's `runner.worker` declares it. */
export const HARNESS_FACTS: readonly HarnessFacts[] = [
  {
    "id": "claude-code",
    "binary": "claude",
    "launch": {
      "kind": "native"
    },
    "isolation": {
      "kind": "flag",
      "args": [
        "--strict-mcp-config"
      ]
    },
    "sourceGit": "shim",
    "modelSetting": "flag",
    "accounting": {
      "reported": "claude-stream",
      "modelSources": [
        "system.init.model",
        "assistant.message.model",
        "result.modelUsage"
      ],
      "launchFallback": "none",
      "primarySources": [
        "system.init.model"
      ],
      "modelVariants": [
        {
          "suffix": "[1m]",
          "context": "1m"
        }
      ],
      "zeroDollars": "reported",
      "provider": {
        "kind": "environment",
        "default": "anthropic",
        "selectors": [
          {
            "variable": "CLAUDE_CODE_USE_BEDROCK",
            "provider": "bedrock"
          },
          {
            "variable": "CLAUDE_CODE_USE_VERTEX",
            "provider": "vertex"
          },
          {
            "variable": "CLAUDE_CODE_USE_FOUNDRY",
            "provider": "foundry"
          }
        ],
        "unknownIfSet": [
          "ANTHROPIC_BASE_URL",
          "CLAUDE_CODE_CLIENT_DATA_URL"
        ]
      },
      "tokenScope": "attempt"
    },
    "credential": {
      "kind": "file-or-command",
      "path": "~/.claude/.credentials.json",
      "requires": [
        "claudeAiOauth",
        "accessToken"
      ],
      "args": [
        "auth",
        "status"
      ]
    }
  },
  {
    "id": "codex",
    "binary": "codex",
    "launch": {
      "kind": "native"
    },
    "isolation": {
      "kind": "home",
      "env": "CODEX_HOME"
    },
    "sourceGit": "none",
    "modelSetting": "config",
    "accounting": {
      "reported": "codex-session",
      "modelSources": [
        "session.turn_context.model"
      ],
      "launchFallback": "resolved-config",
      "provider": {
        "kind": "session-config",
        "default": "openai"
      },
      "tokenScope": "attempt"
    },
    "credential": {
      "kind": "file",
      "path": "~/.codex/auth.json",
      "requires": [
        "OPENAI_API_KEY",
        "tokens",
        "personal_access_token"
      ]
    }
  },
  {
    "id": "opencode",
    "binary": "opencode",
    "launch": {
      "kind": "subcommand",
      "args": [
        "acp"
      ]
    },
    "isolation": {
      "kind": "additive"
    },
    "sourceGit": "shim",
    "modelSetting": "config",
    "accounting": {
      "reported": "acp-session",
      "modelSources": [
        "session.models",
        "session.configOptions",
        "session.currentModelId"
      ],
      "launchFallback": "none",
      "zeroDollars": "unavailable",
      "provider": {
        "kind": "model-prefix"
      },
      "tokenScope": "unverified",
      "lastResponseVersions": [
        "1.18.21",
        "1.18.29"
      ]
    },
    "credential": {
      "kind": "file",
      "path": "~/.local/share/opencode/auth.json",
      "requires": []
    }
  },
  {
    "id": "cursor",
    "binary": "cursor-agent",
    "launch": {
      "kind": "subcommand",
      "args": [
        "acp"
      ]
    },
    "isolation": {
      "kind": "additive"
    },
    "sourceGit": "none",
    "modelSetting": "none",
    "accounting": {
      "reported": "acp-session",
      "modelSources": [
        "session.models",
        "session.configOptions",
        "session.currentModelId"
      ],
      "launchFallback": "none",
      "zeroDollars": "unavailable",
      "provider": {
        "kind": "unavailable"
      },
      "tokenScope": "unverified"
    },
    "credential": {
      "kind": "command",
      "args": [
        "status"
      ]
    }
  },
  {
    "id": "antigravity",
    "binary": "agy",
    "launch": {
      "kind": "sidecar",
      "binary": "agy_acp_server.par"
    },
    "isolation": {
      "kind": "additive"
    },
    "sourceGit": "none",
    "modelSetting": "none",
    "accounting": {
      "reported": "acp-session",
      "modelSources": [
        "session.models",
        "session.configOptions",
        "session.currentModelId"
      ],
      "launchFallback": "none",
      "zeroDollars": "unavailable",
      "provider": {
        "kind": "unavailable"
      },
      "tokenScope": "unverified"
    },
    "credential": {
      "kind": "file",
      "path": "~/.gemini/antigravity-cli/settings.json",
      "requires": []
    }
  }
];
