-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 4); do not edit.

CREATE INDEX IF NOT EXISTS idx_sessions_recent ON sessions (project_id, last_received_at);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '4');
