-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 5); do not edit.

DROP TABLE IF EXISTS _v5_guard_credential_machine_id;

CREATE TABLE _v5_guard_credential_machine_id (ok INTEGER NOT NULL CHECK (ok = 1));

INSERT INTO _v5_guard_credential_machine_id (ok)
     SELECT CASE WHEN EXISTS (SELECT 1 FROM member_tokens WHERE machine_id IS NULL) THEN 0 ELSE 1 END;

DROP TABLE _v5_guard_credential_machine_id;

CREATE TABLE IF NOT EXISTS members (
     id         TEXT PRIMARY KEY,
     label      TEXT,
     created_at INTEGER NOT NULL,
     revoked_at INTEGER);

CREATE TABLE IF NOT EXISTS enrollment_authorities (
     id                TEXT PRIMARY KEY,
     key_hash          TEXT NOT NULL,
     created_at        INTEGER NOT NULL,
     expires_at        INTEGER NOT NULL,
     used_at           INTEGER,
     used_by_runtime   TEXT,
     revoked_at        INTEGER,
     created_by_member TEXT);

CREATE UNIQUE INDEX IF NOT EXISTS idx_enrollment_authorities_hash ON enrollment_authorities (key_hash);

CREATE TABLE IF NOT EXISTS member_credentials (
     id                 TEXT PRIMARY KEY,
     member_id          TEXT NOT NULL REFERENCES members(id),
     token_hash         TEXT NOT NULL,
     machine_id         TEXT,
     runtime_label      TEXT,
     runtime_kind       TEXT,
     issued_at          INTEGER NOT NULL,
     expires_at         INTEGER NOT NULL,
     revoked_at         INTEGER,
     lineage_root       TEXT NOT NULL,
     lineage_started_at INTEGER NOT NULL,
     predecessor_id     TEXT,
     first_used_at      INTEGER,
     bytes_written      INTEGER NOT NULL DEFAULT 0,
     CONSTRAINT member_tokens_quota CHECK (bytes_written <= 1073741824));

CREATE UNIQUE INDEX IF NOT EXISTS idx_member_credentials_hash ON member_credentials (token_hash);

CREATE UNIQUE INDEX IF NOT EXISTS idx_member_credentials_live_successor
     ON member_credentials (predecessor_id) WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_member_credentials_lineage ON member_credentials (lineage_root);

CREATE INDEX IF NOT EXISTS idx_blob_reservations_credential ON blob_reservations (token_id, expires_at);

INSERT OR IGNORE INTO members (id, label, created_at, revoked_at)
     SELECT DISTINCT 'mem_' || machine_id, machine_id, 0, NULL FROM member_tokens WHERE machine_id IS NOT NULL;

INSERT OR IGNORE INTO member_credentials
     (id, member_id, token_hash, machine_id, runtime_label, runtime_kind, issued_at, expires_at,
      revoked_at, lineage_root, lineage_started_at, predecessor_id, first_used_at, bytes_written)
     SELECT t.id, 'mem_' || t.machine_id, t.token_hash, t.machine_id, NULL, NULL,
            t.lineage_started_at, t.expires_at,
            COALESCE(t.revoked_at, t.expires_at),
            t.lineage_root, t.lineage_started_at, t.predecessor_id, t.first_used_at, t.bytes_written
       FROM member_tokens t WHERE t.machine_id IS NOT NULL;

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '5');
