-- Generated by npm run migrations:emit from src/db/schema.ts (schema step 6); do not edit.

CREATE TABLE IF NOT EXISTS deployment_secrets (
     name        TEXT PRIMARY KEY,
     ciphertext  TEXT NOT NULL,
     iv          TEXT NOT NULL,
     key_version INTEGER NOT NULL,
     updated_at  INTEGER NOT NULL,
     updated_by  TEXT NOT NULL);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '6');
