import { HARNESS_MEMBER_ID } from '../constants.js';

/** Existing human memberships require an explicit owner selection; empty Deployments bootstrap at first link. */
export const V73_STATEMENTS: readonly string[] = [
  `ALTER TABLE deployment_ownership ADD COLUMN bootstrap_mode TEXT NOT NULL DEFAULT 'selection' CHECK (bootstrap_mode IN ('fresh', 'selection'))`,
  `UPDATE deployment_ownership SET bootstrap_mode = 'fresh' WHERE member_id IS NULL
    AND NOT EXISTS (SELECT 1 FROM members WHERE id <> '${HARNESS_MEMBER_ID}')`,
  `ALTER TABLE members ADD COLUMN role_revision INTEGER NOT NULL DEFAULT 0 CHECK (role_revision >= 0)`,
  `ALTER TABLE deployment_ownership_audit ADD COLUMN previous_member_id TEXT REFERENCES members(id)`,
  `ALTER TABLE deployment_ownership_audit ADD COLUMN operation TEXT NOT NULL DEFAULT 'bootstrap' CHECK (operation IN ('bootstrap', 'transfer'))`,
  `CREATE TABLE IF NOT EXISTS member_role_audit (
    member_id TEXT NOT NULL REFERENCES members(id), revision INTEGER NOT NULL,
    previous_role TEXT NOT NULL CHECK (previous_role IN ('admin', 'member')),
    role TEXT NOT NULL CHECK (role IN ('admin', 'member')),
    actor_id TEXT NOT NULL REFERENCES members(id), created_at INTEGER NOT NULL,
    PRIMARY KEY (member_id, revision))`,
  `CREATE INDEX IF NOT EXISTS idx_fk_member_tokens_project_id ON member_tokens (project_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_enrollment_authorities_project_id ON enrollment_authorities (project_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_enrollment_authorities_member_id ON enrollment_authorities (member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_agent_tasks_agent_id ON agent_tasks (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_agent_runs_agent_id ON agent_runs (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_agent_turns_agent_id ON agent_turns (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_agent_reports_agent_id ON agent_reports (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_agent_state_agent_id ON agent_state (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_spores_agent_id ON spores (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_resolution_events_agent_id ON resolution_events (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_skill_candidates_agent_id ON skill_candidates (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_skill_records_project_id_candidate_id ON skill_records (project_id, candidate_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_skill_records_agent_id ON skill_records (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_skill_usage_project_id_session_id ON skill_usage (project_id, session_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_digest_extracts_agent_id ON digest_extracts (agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_digest_extract_revisions_project_id_run_id ON digest_extract_revisions (project_id, run_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_digest_extract_revisions_parent_revision_id ON digest_extract_revisions (parent_revision_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_knowledge_git_provenance_project_id_session_id ON knowledge_git_provenance (project_id, session_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_knowledge_release_state_project_id_source_session_id ON knowledge_release_state (project_id, source_session_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_identity_link_authorities_member_id ON identity_link_authorities (member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_deployment_ownership_member_id ON deployment_ownership (member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_deployment_ownership_audit_previous_member_id ON deployment_ownership_audit (previous_member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_deployment_ownership_audit_actor_id ON deployment_ownership_audit (actor_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_deployment_ownership_audit_member_id ON deployment_ownership_audit (member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_raw_claims_owner_member_id ON raw_claims (owner_member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_raw_credentials_owner_member_id ON raw_credentials (owner_member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_raw_resources_claim_member_id ON raw_resources (claim_member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_raw_resources_owner_member_id ON raw_resources (owner_member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fk_member_role_audit_actor_id ON member_role_audit (actor_id)`,
  `CREATE TRIGGER IF NOT EXISTS member_role_audit_immutable BEFORE UPDATE ON member_role_audit BEGIN
    SELECT RAISE(ABORT, 'member role audit is immutable'); END`,
];
