/**
 * Runners: the Deployment's own execution identities, and the one module that issues, rotates, revokes and
 * controls them.
 *
 * A runner is not a member. Its bearer authenticates against `runner_credentials` alone, its authority is the
 * current `credential_epoch` of a runner row that is not removed, and nothing here reads a member role except the
 * owner or administrator who registers or controls one. Every bearer is generated by the runner's own client and
 * reaches this Deployment once, as the digest it stores: registration binds the candidate the client sent with its
 * device request, and a rotation binds the successor the client staged before asking.
 *
 * - Registration commits at the dashboard approval: one guarded batch creates the runner, binds the candidate as its
 *   first credential, records the audit and decides the device request, while the approver is a live owner or
 *   administrator. A poll mints nothing.
 * - Rotation follows the member cadence (seven-day credentials, the last quarter as the refresh window, a 90-day
 *   idle bound) with a separate lineage. Asking twice with the same candidate answers the same successor. A
 *   successor's first use moves the runner's live lease attribution to it and revokes its predecessor; presenting
 *   that predecessor to the rotation route afterwards ends every credential of the runner.
 * - Pause stops new claims and keeps everything else. Removal tombstones the runner and moves its epoch, which ends
 *   every credential and every run token minted under it at once.
 */
import { toBase64Url } from '../base64.js';
import type { PreparedStatement, RelationalStore } from '../core/adapters.js';
import { writeGuardBatch, writeGuardStore } from '../core/write-guard-store.js';
import { SQL_NOW_MS } from '../core/run-deadline.js';
import { SERVER_SCHEMA_VERSION } from '../constants.js';
import { sha256Hex } from '../hash.js';
import { SchemaMismatchError } from '../telemetry.js';
import { deploymentIdentity, type AuthorizationSubject } from './authorization.js';
import { MEMBER_LINEAGE_IDLE_MS, MEMBER_TOKEN_BYTES, MEMBER_TOKEN_REFRESH_WINDOW_MS, MEMBER_TOKEN_TTL_MS } from './tokens.js';

export const RUNNER_TOKEN_PREFIX = 'mycorun_';
/** Every runner bearer: the prefix and 32 random bytes as unpadded base64url. Disjoint from member tokens and grant keys. */
export const RUNNER_TOKEN_PATTERN = new RegExp(`^${RUNNER_TOKEN_PREFIX}[A-Za-z0-9_-]{${Math.ceil((MEMBER_TOKEN_BYTES * 4) / 3)}}$`);
export const RUNNER_ID_PREFIX = 'rn_';
export const RUNNER_CREDENTIAL_ID_PREFIX = 'rc_';
const RUNNER_ID_BYTES = 12;
/** A runner's display name: the identity grammar enrolled machines answer to. */
export const RUNNER_NAME_PATTERN = /^[A-Za-z0-9._-]{1,64}$/;
export const RUNNER_TOKEN_TTL_MS = MEMBER_TOKEN_TTL_MS;
export const RUNNER_TOKEN_REFRESH_WINDOW_MS = MEMBER_TOKEN_REFRESH_WINDOW_MS;
export const RUNNER_LINEAGE_IDLE_MS = MEMBER_LINEAGE_IDLE_MS;
/** The `revoked_by` of every credential a replayed rotation ended. */
export const RUNNER_REPLAY_REVOKER = 'runner-lineage-replay';
/** The `revoked_by` of every credential a removal ended. */
export const RUNNER_REMOVAL_REVOKER = 'runner-removed';

export type RunnerState = 'enabled' | 'paused' | 'removed';

/** A runner credential the pipeline authenticated. */
export interface RunnerAuth {
  runnerId: string;
  credentialId: string;
  epoch: number;
  state: Exclude<RunnerState, 'removed'>;
  name: string;
  issuedAt: number;
  expiresAt: number;
  predecessorId: string | null;
  firstUsedAt: number | null;
}

const newId = (prefix: string): string => `${prefix}${toBase64Url(crypto.getRandomValues(new Uint8Array(RUNNER_ID_BYTES)))}`;

/** The instant a runner credential's refresh window opens. */
export const runnerWindowOpensAt = (expiresAt: number): number => expiresAt - RUNNER_TOKEN_REFRESH_WINDOW_MS;

/**
 * The credential named by `alias` carries its runner's authority at `instant`: it is of the current epoch of a runner
 * that is not removed, it has not expired, and it is unrevoked — or its revocation is its own successor's first use,
 * which an already-admitted request on the predecessor completes under. Binds the instant once. Under `lapsed`, the
 * rotation route's admission, a credential past its expiry still holds within the lineage idle bound.
 */
export function runnerCredentialAuthority(alias: string, instant: string, expiry: 'live' | 'lapsed' = 'live'): string {
  return `EXISTS (SELECT 1 FROM runners authority_runner WHERE authority_runner.id = ${alias}.runner_id
      AND authority_runner.state <> 'removed' AND authority_runner.credential_epoch = ${alias}.epoch)
    AND ${expiry === 'live' ? `${alias}.expires_at` : `${alias}.issued_at + ${RUNNER_LINEAGE_IDLE_MS}`} > ${instant}
    AND (${alias}.revoked_at IS NULL OR (${alias}.revoked_by IS NULL AND EXISTS (SELECT 1 FROM runner_credentials authority_successor
      WHERE authority_successor.predecessor_id = ${alias}.id AND authority_successor.first_used_at IS NOT NULL
        AND authority_successor.revoked_at IS NULL AND authority_successor.runner_id = ${alias}.runner_id
        AND authority_successor.epoch = ${alias}.epoch)))`;
}

/**
 * The run row named by `alias` keeps its runner parent's authority: a member worker's run has none to lose, and a
 * runner's run holds only while its runner is not removed and the credential that leased it is of the runner's
 * current epoch. Run tokens, run reads and run writes all answer to this one predicate.
 */
export function runParentLive(alias = 'agent_runs'): string {
  return `(${alias}.leased_runner_id IS NULL OR EXISTS (SELECT 1 FROM runners parent_runner
    JOIN runner_credentials parent_credential ON parent_credential.runner_id = parent_runner.id
    WHERE parent_runner.id = ${alias}.leased_runner_id AND parent_credential.id = ${alias}.leased_runner_credential_id
      AND parent_runner.state <> 'removed' AND parent_credential.epoch = parent_runner.credential_epoch))`;
}

interface RunnerAuthRow {
  schema_version: string;
  id: string | null;
  runner_id: string | null;
  epoch: number | null;
  issued_at: number | null;
  expires_at: number | null;
  revoked_at: number | null;
  predecessor_id: string | null;
  first_used_at: number | null;
  state: RunnerState | null;
  credential_epoch: number | null;
  name: string | null;
}

/**
 * One read: the schema version, the credential for the digest and its runner. A revoked credential, one of an older
 * epoch, and one whose runner is removed never authenticate; an expired one authenticates only under `lapsed`, for
 * the rotation route, and only inside the lineage idle bound measured from its issue.
 */
export async function authenticateRunner(db: RelationalStore, digest: string, now: number, expiry: 'live' | 'lapsed' = 'live'): Promise<RunnerAuth | null> {
  const row = await db.prepare(`SELECT s.value AS schema_version, c.id, c.runner_id, c.epoch, c.issued_at, c.expires_at, c.revoked_at,
      c.predecessor_id, c.first_used_at, r.state, r.credential_epoch, r.name
    FROM schema_meta s
    LEFT JOIN runner_credentials c ON c.token_hash = ?
    LEFT JOIN runners r ON r.id = c.runner_id
    WHERE s.key = 'version'`).bind(digest).first<RunnerAuthRow>();
  if (!row) throw new SchemaMismatchError(SERVER_SCHEMA_VERSION, null);
  if (row.schema_version !== String(SERVER_SCHEMA_VERSION)) throw new SchemaMismatchError(SERVER_SCHEMA_VERSION, row.schema_version);
  if (row.id === null || row.runner_id === null || row.epoch === null || row.expires_at === null || row.issued_at === null) return null;
  if (row.revoked_at !== null || row.state === null || row.state === 'removed' || row.credential_epoch !== row.epoch) return null;
  if (expiry === 'live' ? row.expires_at <= now : row.issued_at + RUNNER_LINEAGE_IDLE_MS <= now) return null;
  return {
    runnerId: row.runner_id, credentialId: row.id, epoch: row.epoch, state: row.state, name: row.name ?? '',
    issuedAt: row.issued_at, expiresAt: row.expires_at, predecessorId: row.predecessor_id, firstUsedAt: row.first_used_at,
  };
}

/** The runner subject, resolved from the store at authorization time rather than carried from authentication. */
export async function runnerSubject(db: RelationalStore, auth: Pick<RunnerAuth, 'runnerId' | 'credentialId'>, now: number, expiry: 'live' | 'lapsed' = 'live'): Promise<AuthorizationSubject> {
  const row = await db.prepare(`SELECT c.id FROM runner_credentials c WHERE c.id = ? AND c.runner_id = ? AND ${runnerCredentialAuthority('c', '?', expiry)}`)
    .bind(auth.credentialId, auth.runnerId, now).first<{ id: string }>();
  return { kind: 'runner', deploymentId: await deploymentIdentity(db), transport: 'http', live: row !== null, runnerId: auth.runnerId, tokenId: auth.credentialId };
}

const RUNNER_WRITE_REFUSED = '$[myco_runner_write_refused]';

export class RunnerWriteRefused extends Error {
  constructor() { super('runner credential holds no authority'); }
}

/**
 * The assertion every runner-admitted mutation commits with: the presenting credential still carries its runner's
 * authority, under the same expiry its route admitted it with — `lapsed` on the rotation route alone.
 */
export function runnerWriteAssertion(db: RelationalStore, credentialId: string, expiry: 'live' | 'lapsed' = 'live'): () => PreparedStatement {
  return () => db.prepare(`SELECT CASE WHEN EXISTS (SELECT 1 FROM runner_credentials c WHERE c.id = ? AND ${runnerCredentialAuthority('c', SQL_NOW_MS, expiry)})
    THEN 1 ELSE json_extract('[]', ?) END AS admitted`).bind(credentialId, RUNNER_WRITE_REFUSED);
}

export function runnerWriteRefusal(error: unknown): never {
  if (error instanceof Error && error.message.includes(RUNNER_WRITE_REFUSED.slice(1))) throw new RunnerWriteRefused();
  throw error;
}

/** The request's mutations commit only while its runner credential still carries authority, in the same atomic batch. */
export function runnerWriteStore(db: RelationalStore, credentialId: string, expiry: 'live' | 'lapsed' = 'live'): RelationalStore {
  return writeGuardStore(db, runnerWriteAssertion(db, credentialId, expiry), runnerWriteRefusal);
}

/**
 * A successor's first authenticated use, once: the runner's live lease attribution moves to it, its first use is
 * stamped and its predecessor is revoked. The runner, its leases' attempts and their history stay as they are.
 */
export async function activateRunnerSuccessor(db: RelationalStore, auth: RunnerAuth & { predecessorId: string }, now: number): Promise<void> {
  await db.batch([
    db.prepare(`UPDATE agent_runs SET leased_runner_credential_id = ?
      WHERE leased_runner_id = ? AND leased_runner_credential_id = ? AND status = 'running'
        AND EXISTS (SELECT 1 FROM runner_credentials successor JOIN runner_credentials predecessor ON predecessor.id = successor.predecessor_id
          WHERE successor.id = ? AND predecessor.id = ? AND successor.first_used_at IS NULL AND successor.revoked_at IS NULL
            AND successor.runner_id = predecessor.runner_id AND successor.epoch = predecessor.epoch)`)
      .bind(auth.credentialId, auth.runnerId, auth.predecessorId, auth.credentialId, auth.predecessorId),
    db.prepare(`UPDATE runner_credentials SET first_used_at = ? WHERE id = ? AND first_used_at IS NULL`).bind(now, auth.credentialId),
    db.prepare(`UPDATE runner_credentials SET revoked_at = ? WHERE id = ? AND runner_id = ? AND revoked_at IS NULL`).bind(now, auth.predecessorId, auth.runnerId),
  ]);
}

export type RunnerRotation =
  | { rotated: true; credentialId: string; expiresAt: number; refreshAfter: number }
  | { rotated: false; code: 'refresh_too_early'; refreshAfter: number }
  | { rotated: false; code: 'parse' | 'candidate_conflict' | 'revoked'; reason: string };

/**
 * Bind the client's staged successor to the presented credential. The same candidate for the same predecessor answers
 * the successor it already bound, so a lost reply is recovered by asking again. A fresh candidate replaces any
 * successor the predecessor banked and never used, while the predecessor still carries authority at the write.
 */
export async function rotateRunnerCredential(db: RelationalStore, auth: RunnerAuth, candidate: unknown, now: number): Promise<RunnerRotation> {
  if (typeof candidate !== 'string' || !RUNNER_TOKEN_PATTERN.test(candidate)) return { rotated: false, code: 'parse', reason: 'candidate must be a runner bearer' };
  const digest = await sha256Hex(candidate);
  const bound = await db.prepare(`SELECT id, runner_id, predecessor_id, expires_at, revoked_at FROM runner_credentials WHERE token_hash = ?`)
    .bind(digest).first<{ id: string; runner_id: string; predecessor_id: string | null; expires_at: number; revoked_at: number | null }>();
  if (bound !== null) {
    if (bound.runner_id === auth.runnerId && bound.predecessor_id === auth.credentialId && bound.revoked_at === null) {
      return { rotated: true, credentialId: bound.id, expiresAt: bound.expires_at, refreshAfter: runnerWindowOpensAt(bound.expires_at) };
    }
    return { rotated: false, code: 'candidate_conflict', reason: 'that candidate is bound elsewhere; stage a fresh one' };
  }
  const opensAt = runnerWindowOpensAt(auth.expiresAt);
  if (now < opensAt) return { rotated: false, code: 'refresh_too_early', refreshAfter: opensAt };
  const successorId = newId(RUNNER_CREDENTIAL_ID_PREFIX);
  const expiresAt = now + RUNNER_TOKEN_TTL_MS;
  const predecessorLive = `EXISTS (SELECT 1 FROM runner_credentials p JOIN runners r ON r.id = p.runner_id
    WHERE p.id = ? AND p.runner_id = ? AND p.revoked_at IS NULL AND p.epoch = r.credential_epoch AND r.state <> 'removed'
      AND p.issued_at + ? > ?)`;
  const live = [auth.credentialId, auth.runnerId, RUNNER_LINEAGE_IDLE_MS, now];
  const [, inserted] = await db.batch([
    db.prepare(`UPDATE runner_credentials SET revoked_at = ? WHERE predecessor_id = ? AND revoked_at IS NULL AND first_used_at IS NULL AND ${predecessorLive}`)
      .bind(now, auth.credentialId, ...live),
    db.prepare(`INSERT INTO runner_credentials (id, runner_id, token_hash, epoch, issued_at, expires_at, predecessor_id, lineage_root, first_used_at, revoked_at, revoked_by)
      SELECT ?, p.runner_id, ?, p.epoch, ?, ?, p.id, p.lineage_root, NULL, NULL, NULL FROM runner_credentials p WHERE p.id = ? AND ${predecessorLive}`)
      .bind(successorId, digest, now, expiresAt, auth.credentialId, ...live),
  ]);
  if (inserted!.meta.changes !== 1) return { rotated: false, code: 'revoked', reason: 'the presented runner credential no longer carries authority' };
  return { rotated: true, credentialId: successorId, expiresAt, refreshAfter: runnerWindowOpensAt(expiresAt) };
}

/** A presented digest whose credential a used successor already superseded: the evidence that two holders rotated one lineage. */
export async function detectRunnerReplay(db: RelationalStore, digest: string): Promise<{ credentialId: string; runnerId: string; epoch: number; issuedAt: number } | null> {
  return db.prepare(`SELECT p.id AS credentialId, p.runner_id AS runnerId, p.epoch, p.issued_at AS issuedAt FROM runner_credentials p
    JOIN runner_credentials s ON s.predecessor_id = p.id AND s.first_used_at IS NOT NULL AND s.runner_id = p.runner_id
    WHERE p.token_hash = ? AND p.revoked_at IS NOT NULL AND p.revoked_by IS NULL LIMIT 1`)
    .bind(digest).first<{ credentialId: string; runnerId: string; epoch: number; issuedAt: number }>();
}

/** End every credential of a runner whose lineage a second holder replayed: its epoch moves on and the runner must be registered again. */
export async function revokeRunnerLineage(db: RelationalStore, replay: { runnerId: string; epoch: number }, now: number): Promise<number> {
  const results = await db.batch([
    db.prepare(`UPDATE runners SET credential_epoch = credential_epoch + 1, revision = revision + 1
      WHERE id = ? AND credential_epoch = ? AND state <> 'removed'`).bind(replay.runnerId, replay.epoch),
    db.prepare(`UPDATE runner_credentials SET revoked_at = ?, revoked_by = ? WHERE runner_id = ? AND revoked_at IS NULL
      AND EXISTS (SELECT 1 FROM runners WHERE id = ? AND credential_epoch = ?)`).bind(now, RUNNER_REPLAY_REVOKER, replay.runnerId, replay.runnerId, replay.epoch + 1),
    db.prepare(`INSERT INTO runner_audit (id, runner_id, actor_member, action, revision, at)
      SELECT ?, id, NULL, 'lineage_replayed', revision, ? FROM runners WHERE id = ? AND credential_epoch = ?
        AND NOT EXISTS (SELECT 1 FROM runner_audit WHERE runner_id = runners.id AND action = 'lineage_replayed' AND revision = runners.revision)`)
      .bind(crypto.randomUUID(), now, replay.runnerId, replay.epoch + 1),
  ]);
  return results[0]!.meta.changes;
}

/** A live owner or administrator, by member id; a held or revoked member is neither. Binds the member id. */
export const LIVE_RUNNER_ADMIN = `EXISTS (SELECT 1 FROM members approver WHERE approver.id = ? AND approver.revoked_at IS NULL
  AND (approver.role = 'admin' OR EXISTS (SELECT 1 FROM deployment_ownership o WHERE o.id = 1 AND o.member_id = approver.id)))`;

const REGISTRATION_REFUSED = '$[myco_runner_registration_refused]';

/** The device request a registration consumes: a runner request, undecided, unexpired, with no decision receipt. */
const PENDING_RUNNER_REQUEST = `EXISTS (SELECT 1 FROM device_requests d WHERE d.id = ? AND d.subject = 'runner'
  AND d.decision IS NULL AND d.expires_at > ? AND NOT EXISTS (SELECT 1 FROM device_decision_audit a WHERE a.request_id = d.id))`;

/**
 * The dashboard approval of a runner request: the runner, its first credential bound to the client's candidate, its
 * audit, the decision and its receipt commit together or not at all, while the request is pending and the approver is
 * a live owner or administrator at the write.
 */
export async function registerRunner(db: RelationalStore, approverId: string, requestId: string, sourceHash: string, now: number): Promise<{ runnerId: string } | null> {
  const runnerId = newId(RUNNER_ID_PREFIX);
  const credentialId = newId(RUNNER_CREDENTIAL_ID_PREFIX);
  const assertion = (): PreparedStatement => db.prepare(`SELECT CASE WHEN ${PENDING_RUNNER_REQUEST} AND ${LIVE_RUNNER_ADMIN}
    THEN 1 ELSE json_extract('[]', ?) END AS admitted`).bind(requestId, now, approverId, REGISTRATION_REFUSED);
  try {
    await writeGuardBatch(db, assertion, (error) => { throw error; }, [
      db.prepare(`INSERT INTO runners (id, name, state, credential_epoch, revision, labels, created_at, created_by_member, registration_id)
        SELECT ?, d.runner_name, 'enabled', 1, 1, '[]', ?, ?, d.id FROM device_requests d WHERE d.id = ? AND d.subject = 'runner'`)
        .bind(runnerId, now, approverId, requestId),
      db.prepare(`INSERT INTO runner_credentials (id, runner_id, token_hash, epoch, issued_at, expires_at, predecessor_id, lineage_root)
        SELECT ?, ?, d.candidate_hash, 1, ?, ?, NULL, ? FROM device_requests d WHERE d.id = ? AND d.subject = 'runner'`)
        .bind(credentialId, runnerId, now, now + RUNNER_TOKEN_TTL_MS, credentialId, requestId),
      db.prepare(`INSERT INTO runner_audit (id, runner_id, actor_member, action, revision, at) VALUES (?, ?, ?, 'registered', 1, ?)`)
        .bind(crypto.randomUUID(), runnerId, approverId, now),
      db.prepare(`UPDATE device_requests SET decision = 'approved', decided_by = ?, decided_at = ? WHERE id = ? AND subject = 'runner' AND decision IS NULL`)
        .bind(approverId, now, requestId),
      db.prepare(`INSERT INTO device_decision_audit (request_id, member_id, machine_id, machine_name, os, source_hash, decision, decided_at, subject)
        SELECT id, decided_by, machine_id, machine_name, os, ?, decision, decided_at, subject FROM device_requests WHERE id = ? AND decision = 'approved'`)
        .bind(sourceHash, requestId),
    ]);
  } catch (error) {
    if (error instanceof Error && /myco_runner_registration_refused|UNIQUE constraint failed/.test(error.message)) return null;
    throw error;
  }
  return { runnerId };
}

/** Whether a runner may take new work now: enabled, neither paused nor removed. */
export async function runnerAcceptsWork(db: RelationalStore, runnerId: string): Promise<boolean> {
  return (await db.prepare(`SELECT 1 AS one FROM runners WHERE id = ? AND state = 'enabled'`).bind(runnerId).first<{ one: number }>()) !== null;
}

/** The registered runner a decided request created, for the client polling it. */
export async function runnerOfRegistration(db: RelationalStore, requestId: string): Promise<{ id: string; name: string } | null> {
  return db.prepare(`SELECT id, name FROM runners WHERE registration_id = ?`).bind(requestId).first<{ id: string; name: string }>();
}

export type RunnerControl = 'pause' | 'resume' | 'remove';

const CONTROL_TRANSITIONS: Readonly<Record<RunnerControl, { from: string; to: RunnerState; audit: 'paused' | 'resumed' | 'removed' }>> = {
  pause: { from: `state = 'enabled'`, to: 'paused', audit: 'paused' },
  resume: { from: `state = 'paused'`, to: 'enabled', audit: 'resumed' },
  remove: { from: `state <> 'removed'`, to: 'removed', audit: 'removed' },
};

export interface RunnerRecord {
  id: string;
  name: string;
  state: RunnerState;
  revision: number;
  createdAt: number;
  createdBy: string | null;
  removedAt: number | null;
}

const RUNNER_COLUMNS = `id, name, state, revision, created_at AS createdAt, created_by_member AS createdBy, removed_at AS removedAt`;

export async function readRunner(db: RelationalStore, runnerId: string): Promise<RunnerRecord | null> {
  return db.prepare(`SELECT ${RUNNER_COLUMNS} FROM runners WHERE id = ?`).bind(runnerId).first<RunnerRecord>();
}

/**
 * An owner or administrator's control of one runner, attributed and audited in one batch. Pause and resume move only
 * its state; removal also moves its epoch and revokes every credential it holds. A control the runner's current state
 * does not admit, or one another control won first, changes nothing, writes no receipt, and answers the runner as it
 * stands: a revision has one receipt, the one its own transition wrote.
 */
export async function controlRunner(db: RelationalStore, actorId: string, runnerId: string, control: RunnerControl, now: number): Promise<{ changed: boolean; runner: RunnerRecord } | null> {
  const before = await readRunner(db, runnerId);
  if (before === null) return null;
  const transition = CONTROL_TRANSITIONS[control];
  const removing = control === 'remove';
  const results = await db.batch([
    db.prepare(`UPDATE runners SET state = ?, revision = revision + 1${removing ? ', removed_at = ?, credential_epoch = credential_epoch + 1' : ''}
      WHERE id = ? AND revision = ? AND ${transition.from} AND ${LIVE_RUNNER_ADMIN}`)
      .bind(transition.to, ...(removing ? [now] : []), runnerId, before.revision, actorId),
    ...(removing ? [db.prepare(`UPDATE runner_credentials SET revoked_at = ?, revoked_by = ? WHERE runner_id = ? AND revoked_at IS NULL
      AND EXISTS (SELECT 1 FROM runners WHERE id = ? AND state = 'removed' AND revision = ?)`)
      .bind(now, RUNNER_REMOVAL_REVOKER, runnerId, runnerId, before.revision + 1)] : []),
    db.prepare(`INSERT INTO runner_audit (id, runner_id, actor_member, action, revision, at)
      SELECT ?, id, ?, ?, revision, ? FROM runners WHERE id = ? AND revision = ? AND state = ?
        AND NOT EXISTS (SELECT 1 FROM runner_audit receipt WHERE receipt.runner_id = runners.id AND receipt.revision = runners.revision)`)
      .bind(crypto.randomUUID(), actorId, transition.audit, now, runnerId, before.revision + 1, transition.to),
  ]);
  const runner = await readRunner(db, runnerId);
  return { changed: results[0]!.meta.changes === 1, runner: runner! };
}

/** Every runner, newest first, with its last contact and any live lease: the read-only projection members share. */
export async function listRunners(db: RelationalStore, now: number): Promise<Array<RunnerRecord & { lastSeenAt: number | null; busy: { projectId: string; runId: string; leaseExpiresAt: number } | null }>> {
  const { results } = await db.prepare(`SELECT r.id, r.name, r.state, r.revision, r.created_at AS createdAt, r.created_by_member AS createdBy,
      r.removed_at AS removedAt, c.last_seen_at AS lastSeenAt,
      (SELECT json_object('projectId', a.project_id, 'runId', a.id, 'leaseExpiresAt', a.lease_expires_at) FROM agent_runs a
        INDEXED BY idx_agent_runs_runner_lease WHERE a.leased_runner_id = r.id AND a.status = 'running' AND a.lease_expires_at > ? LIMIT 1) AS busy
    FROM runners r LEFT JOIN runner_contacts c ON c.runner_id = r.id ORDER BY r.created_at DESC, r.id`)
    .bind(now).all<RunnerRecord & { lastSeenAt: number | null; busy: string | null }>();
  return results.map((row) => ({ ...row, busy: row.busy === null ? null : JSON.parse(row.busy) as { projectId: string; runId: string; leaseExpiresAt: number } }));
}
