import fs from 'node:fs';
import path from 'node:path';

/**
 * The canonical `.myco/.gitignore` body. Owned by the vault layer so the
 * CLI commands (`init`, `update`) and the activation pipeline can all
 * write/refresh it without going through `cli/shared.ts` (which has heavy
 * transitive imports inappropriate for the activation hot path).
 *
 * Every entry that touches files under `.myco/` and contains machine-local
 * or operationally-sensitive data MUST be listed here. Re-check this when
 * you add anything to `.myco/`.
 */
export const VAULT_GITIGNORE = `# SQLite database
myco.db*
vectors.db*

# Daemon state — per-machine, ephemeral
daemon.json
buffer/
logs/

# Secrets — API keys for cloud providers
secrets.env

# Machine ID
machine_id

# Update tracking — per-machine state
last-update-version
restart-reason.json

# Binary attachments — screenshots captured from transcripts
attachments/

# Team sync admin state + worker deployment
team/

# Staged files generated by the myco agent
staging/

# Grove activation marker/state — local to this checkout and contains
# machine-local paths and import metadata; never committed.
migration/

# Grove project binding — per-machine. \`project.toml\` itself is committed
# (portable project + Grove identity); the binding lives here.
project.local.toml

# Per-user appearance and settings overrides
local.yaml

# Project-scope runtime pin written by \`make dev-link\`. Per-machine,
# never committed.
runtime.command

# Grove migration archive — timestamped snapshot of pre-Grove vault data
# moved aside post-activation. Never committed; recoverable on disk.
.archive-*/

# Agent-config Grove promotion archive — timestamped snapshot of the
# embedding/agent fields the migration lifted from project tier to Grove.
# Local-only forensic safety net per the spec; never committed.
archive/
`;

/**
 * Write `<vaultDir>/.gitignore` to the canonical body if it's missing or
 * stale. Called from `myco init`, `myco update`, and the Grove activation
 * pipeline so users never have to wait for the next update tick to keep
 * machine-local files out of git. Idempotent — exits without writing
 * when the file already matches.
 */
export function ensureVaultGitignoreCurrent(vaultDir: string): boolean {
  const gitignorePath = path.join(vaultDir, '.gitignore');
  const current = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf-8') : '';
  if (current === VAULT_GITIGNORE) return false;
  fs.mkdirSync(vaultDir, { recursive: true });
  fs.writeFileSync(gitignorePath, VAULT_GITIGNORE, 'utf-8');
  return true;
}
