/**
 * The skill lifecycle, server-side: candidates, records, lineage and usage.
 *
 * Four properties the 1.4 vault encodes that a translation drops:
 *
 * **Lineage is the source of truth for a skill's content.** `skill_records`
 * carries metadata and a path; the on-disk SKILL.md is a materialization. The
 * published content is the latest lineage snapshot, ordered by generation.
 *
 * **`approved_at` stamps on the FIRST transition into approved and never
 * moves.** 1.4 reads the row, decides, then writes, which is safe only where
 * nothing yields between. Here it is one conditional expression, so two callers
 * approving at once cannot both stamp and the second cannot overwrite the first.
 *
 * **Deleting a skill dismisses the candidates that point at it.** A candidate
 * left approved and still naming a deleted skill is regenerated by the next
 * survey, which is how a deliberately removed skill comes back.
 *
 * **A candidate update may not move a candidate between Projects.** The
 * settable columns are a fixed list, as with a run update: `project_id`, `id`
 * and `agent_id` are absent from it.
 */
import type { RelationalStore } from './adapters.js';
import type { ReadScope } from '../read/scope.js';

export const SKILL_STATUSES = ['active', 'archived', 'superseded'] as const;
export const CANDIDATE_STATUSES = ['identified', 'approved', 'dismissed', 'generated'] as const;

/**
 * The columns a candidate update may set.
 *
 * `approved_at` is absent: it is stamped by the transition rather than written
 * by a caller, which is what makes it a single audit trail rather than a field
 * anyone may rewrite.
 */
export const CANDIDATE_UPDATE_COLUMNS = [
  'topic', 'rationale', 'confidence', 'status', 'source_ids', 'skill_id', 'supersedes',
  'evidence_bundle_id', 'quality_score', 'quality_failures', 'coverage_matches',
  'last_reconciled_at', 'reconciliation_reason',
] as const;
export type CandidateUpdateColumn = (typeof CANDIDATE_UPDATE_COLUMNS)[number];
export type CandidateUpdate = Partial<Record<CandidateUpdateColumn, string | number | null>>;

/** Columns a candidate update may never set. */
export const CANDIDATE_IMMUTABLE_COLUMNS = ['project_id', 'id', 'agent_id', 'approved_at'] as const;

const RECORD_COLUMNS = `id, agent_id AS agentId, name, display_name AS displayName, description,
  status, embedded, generation, candidate_id AS candidateId, source_ids AS sourceIds, path,
  usage_count AS usageCount, last_used_at AS lastUsedAt, created_at AS createdAt,
  updated_at AS updatedAt, properties`;

const CANDIDATE_COLUMNS = `id, agent_id AS agentId, topic, rationale, confidence, status,
  source_ids AS sourceIds, skill_id AS skillId, supersedes, evidence_bundle_id AS evidenceBundleId,
  quality_score AS qualityScore, quality_failures AS qualityFailures, coverage_matches AS coverageMatches,
  last_reconciled_at AS lastReconciledAt, reconciliation_reason AS reconciliationReason,
  created_at AS createdAt, updated_at AS updatedAt, approved_at AS approvedAt`;

export interface SkillRecordInsert {
  id: string; agentId: string; name: string; displayName: string; description: string;
  status?: string; generation?: number; candidateId: string | null; sourceIds: string;
  path: string; createdAt: number; properties?: string;
}

export interface CandidateInsert {
  id: string; agentId: string; topic: string; rationale: string; confidence: number;
  status?: string; sourceIds: string; createdAt: number;
}

export interface LineageInsert {
  id: string; skillId: string; generation: number; action: string; rationale: string;
  sourceIdsAdded: string; contentSnapshot: string; createdAt: number;
}

// ---------------------------------------------------------------------------
// Records
// ---------------------------------------------------------------------------

export async function insertSkillRecord(db: RelationalStore, scope: ReadScope, row: SkillRecordInsert): Promise<unknown> {
  return db.prepare(`INSERT INTO skill_records
      (project_id, id, agent_id, name, display_name, description, status, embedded, generation,
       candidate_id, source_ids, path, usage_count, created_at, updated_at, properties)
      VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, ?, ?, ?, 0, ?, ?, ?)
      RETURNING ${RECORD_COLUMNS}`)
    .bind(scope.projectId, row.id, row.agentId, row.name, row.displayName, row.description,
      row.status ?? 'active', row.generation ?? 1, row.candidateId, row.sourceIds, row.path,
      row.createdAt, row.createdAt, row.properties ?? '{}')
    .first();
}

/** By id, or by name — a name is unique within a Project, which the schema enforces. */
export async function getSkillRecord(db: RelationalStore, scope: ReadScope, idOrName: string): Promise<Record<string, unknown> | null> {
  return db.prepare(`SELECT ${RECORD_COLUMNS} FROM skill_records
     WHERE project_id = ? AND (id = ? OR name = ?) ORDER BY CASE WHEN id = ? THEN 0 ELSE 1 END LIMIT 1`)
    .bind(scope.projectId, idOrName, idOrName, idOrName).first();
}

export async function listSkillRecords(db: RelationalStore, scope: ReadScope, o: { status?: string; limit?: number } = {}): Promise<unknown[]> {
  const conditions = ['project_id = ?'];
  const params: unknown[] = [scope.projectId];
  if (o.status !== undefined) { conditions.push('status = ?'); params.push(o.status); }
  const { results } = await db
    .prepare(`SELECT ${RECORD_COLUMNS} FROM skill_records WHERE ${conditions.join(' AND ')} ORDER BY name ASC LIMIT ?`)
    .bind(...params, Math.min(o.limit ?? 100, 500)).all();
  return results;
}

/** One statement: a read-then-write would lose a concurrent increment. */
export async function incrementSkillUsage(db: RelationalStore, scope: ReadScope, skillId: string, now: number): Promise<void> {
  await db.prepare(`UPDATE skill_records SET usage_count = usage_count + 1, last_used_at = ?
     WHERE project_id = ? AND id = ?`).bind(now, scope.projectId, skillId).run();
}

/**
 * Remove a skill and everything that would resurrect it.
 *
 * Candidates naming this skill are dismissed and their `skill_id` cleared —
 * a candidate left approved and still pointing at a deleted skill is
 * regenerated by the next survey, which is how a deliberately removed skill
 * comes back. One batch, so the record cannot outlive its lineage or the
 * dismissal.
 */
export async function deleteSkillRecordCascade(
  db: RelationalStore, scope: ReadScope, skillId: string, now: number,
): Promise<boolean> {
  const results = await db.batch([
    db.prepare(`DELETE FROM skill_lineage WHERE project_id = ? AND skill_id = ?`).bind(scope.projectId, skillId),
    db.prepare(`DELETE FROM skill_usage WHERE project_id = ? AND skill_id = ?`).bind(scope.projectId, skillId),
    db.prepare(`UPDATE skill_candidates SET status = 'dismissed', skill_id = NULL, updated_at = ?
       WHERE project_id = ? AND (skill_id = ? OR id = (SELECT candidate_id FROM skill_records WHERE project_id = ? AND id = ?))`)
      .bind(now, scope.projectId, skillId, scope.projectId, skillId),
    db.prepare(`DELETE FROM skill_records WHERE project_id = ? AND id = ?`).bind(scope.projectId, skillId),
  ]);
  return results[3].meta.changes > 0;
}

// ---------------------------------------------------------------------------
// Candidates
// ---------------------------------------------------------------------------

export async function insertCandidate(db: RelationalStore, scope: ReadScope, row: CandidateInsert): Promise<unknown> {
  return db.prepare(`INSERT INTO skill_candidates
      (project_id, id, agent_id, topic, rationale, confidence, status, source_ids, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      RETURNING ${CANDIDATE_COLUMNS}`)
    .bind(scope.projectId, row.id, row.agentId, row.topic, row.rationale, row.confidence,
      row.status ?? 'identified', row.sourceIds, row.createdAt, row.createdAt)
    .first();
}

export async function getCandidate(db: RelationalStore, scope: ReadScope, id: string): Promise<Record<string, unknown> | null> {
  return db.prepare(`SELECT ${CANDIDATE_COLUMNS} FROM skill_candidates WHERE project_id = ? AND id = ?`)
    .bind(scope.projectId, id).first();
}

export async function listCandidates(db: RelationalStore, scope: ReadScope, o: { status?: string; limit?: number } = {}): Promise<unknown[]> {
  const conditions = ['project_id = ?'];
  const params: unknown[] = [scope.projectId];
  if (o.status !== undefined) { conditions.push('status = ?'); params.push(o.status); }
  const { results } = await db
    .prepare(`SELECT ${CANDIDATE_COLUMNS} FROM skill_candidates WHERE ${conditions.join(' AND ')} ORDER BY created_at DESC LIMIT ?`)
    .bind(...params, Math.min(o.limit ?? 100, 500)).all();
  return results;
}

/**
 * Apply a partial update, stamping `approved_at` on the first approval.
 *
 * The stamp is a conditional expression rather than a read, a decision and a
 * write: `COALESCE` keeps whatever is already there, so a second approval
 * cannot move it and two concurrent approvals cannot both claim to be first.
 */
export async function updateCandidate(
  db: RelationalStore, scope: ReadScope, id: string, update: CandidateUpdate, now: number,
): Promise<number> {
  const columns = CANDIDATE_UPDATE_COLUMNS.filter((c) => c in update);
  if (columns.length === 0) return 0;
  const sets = columns.map((c) => `${c} = ?`);
  const params: unknown[] = columns.map((c) => update[c] ?? null);
  sets.push('updated_at = ?');
  params.push(now);
  if (update.status === 'approved') {
    sets.push('approved_at = COALESCE(approved_at, ?)');
    params.push(now);
  }
  const result = await db
    .prepare(`UPDATE skill_candidates SET ${sets.join(', ')} WHERE project_id = ? AND id = ?`)
    .bind(...params, scope.projectId, id).run();
  return result.meta.changes;
}

// ---------------------------------------------------------------------------
// Lineage
// ---------------------------------------------------------------------------

export async function insertLineage(db: RelationalStore, scope: ReadScope, row: LineageInsert): Promise<void> {
  await db.prepare(`INSERT INTO skill_lineage
      (project_id, id, skill_id, generation, action, rationale, source_ids_added, content_snapshot, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(scope.projectId, row.id, row.skillId, row.generation, row.action, row.rationale,
      row.sourceIdsAdded, row.contentSnapshot, row.createdAt).run();
}

export async function listLineageForSkill(db: RelationalStore, scope: ReadScope, skillId: string, limit = 50): Promise<unknown[]> {
  const { results } = await db
    .prepare(`SELECT id, skill_id AS skillId, generation, action, rationale,
        source_ids_added AS sourceIdsAdded, content_snapshot AS contentSnapshot, created_at AS createdAt
      FROM skill_lineage WHERE project_id = ? AND skill_id = ?
      ORDER BY generation DESC, created_at DESC, id DESC LIMIT ?`)
    .bind(scope.projectId, skillId, Math.min(limit, 200)).all();
  return results;
}

/**
 * The canonical published content: the latest lineage snapshot.
 *
 * 1.4 reads this UNSCOPED: its lineage `project_id` is denormalized routing
 * metadata a legacy backfill can leave NULL, and a project filter there could
 * only hide a skill's own history. Server-side the column is NOT NULL, which
 * removes that hazard, and the read is scoped like every other.
 */
export async function getPublishedSkillContent(db: RelationalStore, scope: ReadScope, skillId: string): Promise<string | null> {
  const row = await db.prepare(`SELECT content_snapshot AS content FROM skill_lineage
     WHERE project_id = ? AND skill_id = ?
     ORDER BY generation DESC, created_at DESC, id DESC LIMIT 1`)
    .bind(scope.projectId, skillId).first<{ content: string | null }>();
  return row?.content ? row.content : null;
}

/** The snapshot a specific generation recorded, which a pinned reader asks for rather than the latest. */
export async function getSkillContentAtGeneration(
  db: RelationalStore, scope: ReadScope, skillId: string, generation: number,
): Promise<string | null> {
  const row = await db.prepare(`SELECT content_snapshot AS content FROM skill_lineage
     WHERE project_id = ? AND skill_id = ? AND generation = ?
     ORDER BY created_at DESC, id DESC LIMIT 1`)
    .bind(scope.projectId, skillId, generation).first<{ content: string | null }>();
  return row?.content ? row.content : null;
}

// ---------------------------------------------------------------------------
// Usage
// ---------------------------------------------------------------------------

export async function recordSkillUsage(
  db: RelationalStore, scope: ReadScope, row: { id: string; skillId: string; sessionId: string; detectedAt: number },
): Promise<void> {
  await db.batch([
    db.prepare(`INSERT INTO skill_usage (project_id, id, skill_id, session_id, detected_at) VALUES (?, ?, ?, ?, ?)`)
      .bind(scope.projectId, row.id, row.skillId, row.sessionId, row.detectedAt),
    db.prepare(`UPDATE skill_records SET usage_count = usage_count + 1, last_used_at = ?
       WHERE project_id = ? AND id = ?`).bind(row.detectedAt, scope.projectId, row.skillId),
  ]);
}
