// AUTO-GENERATED by scripts/gen-hook-config.ts — DO NOT EDIT.
// Run `npm run codegen` (or `npx tsx packages/myco/scripts/gen-hook-config.ts`) to regenerate.
//
// This file bakes the hook-relevant subset of every symbiont manifest into
// a typed const so hooks don't pay for YAML I/O + Zod parsing on every
// short-lived hook process. Keep it checked into git so tests don't need
// a build step. tests/meta/hook-config-generated-fresh.test.ts fails when
// this file drifts from the manifests or hook templates.

import type {
  CapturePrompts,
  CaptureRule,
  SessionContinuation,
  SymbiontManifest,
  SymbiontRegistration,
  TranscriptDiscovery,
} from '../symbionts/manifest-schema.js';

/** One harness event: the Myco hook its template wires and the declared timeout (seconds). */
export interface HookEventEntry {
  hook: string;
  timeout?: number;
}

/** The capability flags hook responses are gated on. */
export interface HookCapabilities {
  preToolUseInjection: boolean;
  sessionStartInjection: boolean;
  subagentStartInjection: boolean;
}

export interface HookConfigEntry {
  pluginRootEnvVar: string;
  configDir: string;
  hookFields: SymbiontManifest['hookFields'];
  /** Keyed by the harness's own event name (e.g. `Stop`, `post_cascade_response`). */
  hookEvents: Record<string, HookEventEntry>;
  planDirs: string[];
  planTags: string[];
  capabilities: HookCapabilities;
  transcriptDiscovery?: TranscriptDiscovery;
  hookResponse?: NonNullable<SymbiontRegistration['hookResponse']>;
  capturePrompts?: CapturePrompts;
  captureRules?: CaptureRule[];
  subagentParentPath?: string;
  subagentThreadIdPath?: string;
  subagentLabelPath?: string;
  sessionContinuation?: SessionContinuation;
}

export const HOOK_CONFIG: Readonly<Record<string, HookConfigEntry>> = {
  "antigravity": {
    "pluginRootEnvVar": "ANTIGRAVITY_PLUGIN_ROOT",
    "configDir": ".agents/plugins/myco",
    "hookFields": {
      "sessionId": "conversationId",
      "transcriptPath": "transcriptPath",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "toolCall.name",
      "toolInput": "toolCall.args",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "hookEvents": {
      "PostToolUse": {
        "hook": "post-tool-use",
        "timeout": 5
      },
      "PreInvocation": {
        "hook": "session-start",
        "timeout": 10
      },
      "Stop": {
        "hook": "stop",
        "timeout": 30
      }
    },
    "planDirs": [
      ".agents/plugins/myco/plans/"
    ],
    "planTags": [],
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false
    },
    "transcriptDiscovery": {
      "roots": [
        "~/.gemini/antigravity-cli",
        "~/.gemini/antigravity",
        "~/.gemini/antigravity-ide"
      ],
      "patterns": [
        "brain/{sessionId}/.system_generated/logs/transcript_full.jsonl"
      ]
    },
    "hookResponse": {
      "format": "antigravity-inject-steps"
    }
  },
  "claude-code": {
    "pluginRootEnvVar": "CLAUDE_PLUGIN_ROOT",
    "configDir": ".claude",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "hookEvents": {
      "PostCompact": {
        "hook": "post-compact",
        "timeout": 5
      },
      "PostToolUse": {
        "hook": "post-tool-use",
        "timeout": 5
      },
      "PostToolUseFailure": {
        "hook": "post-tool-use-failure",
        "timeout": 5
      },
      "PreCompact": {
        "hook": "pre-compact",
        "timeout": 5
      },
      "PreToolUse": {
        "hook": "pre-tool-use",
        "timeout": 3
      },
      "SessionEnd": {
        "hook": "session-end",
        "timeout": 10
      },
      "SessionStart": {
        "hook": "session-start",
        "timeout": 10
      },
      "Stop": {
        "hook": "stop",
        "timeout": 30
      },
      "StopFailure": {
        "hook": "stop-failure",
        "timeout": 10
      },
      "SubagentStart": {
        "hook": "subagent-start",
        "timeout": 5
      },
      "SubagentStop": {
        "hook": "subagent-stop",
        "timeout": 10
      },
      "TaskCompleted": {
        "hook": "task-completed",
        "timeout": 5
      },
      "UserPromptSubmit": {
        "hook": "user-prompt-submit",
        "timeout": 5
      }
    },
    "planDirs": [
      "~/.claude/plans/",
      ".claude/plans/"
    ],
    "planTags": [
      "ultraplan"
    ],
    "capabilities": {
      "preToolUseInjection": true,
      "sessionStartInjection": true,
      "subagentStartInjection": true
    },
    "transcriptDiscovery": {
      "roots": [
        "~/.claude/projects"
      ],
      "patterns": [
        "*/{sessionId}.jsonl"
      ],
      "transcriptCwdPath": "cwd"
    },
    "capturePrompts": {
      "shapes": [
        {
          "name": "agent_message",
          "match": {
            "type": "user",
            "fieldNotEquals": {
              "isMeta": true
            }
          },
          "textAt": "message.content",
          "textStartsWith": "<agent-message",
          "dedupeBy": "uuid"
        },
        {
          "name": "teammate_message",
          "match": {
            "type": "user",
            "fieldNotEquals": {
              "isMeta": true
            }
          },
          "textAt": "message.content",
          "textStartsWith": "<teammate-message",
          "dedupeBy": "uuid"
        },
        {
          "name": "user_prompt",
          "match": {
            "type": "user",
            "hasField": "promptId",
            "fieldNotEquals": {
              "isMeta": true
            }
          },
          "textAt": "message.content",
          "dedupeBy": "promptId"
        },
        {
          "name": "queued_command",
          "match": {
            "type": "attachment",
            "fieldEquals": {
              "attachment.type": "queued_command"
            }
          },
          "textAt": "attachment.prompt",
          "dedupeBy": "uuid"
        }
      ],
      "resetBoundaries": [
        {
          "match": {
            "type": "assistant",
            "fieldEquals": {
              "message.stop_reason": "end_turn"
            }
          }
        }
      ],
      "interruptMarker": "[Request interrupted by user for tool use]"
    },
    "captureRules": [
      {
        "event": "session_start",
        "scope": "this_agent",
        "when": {
          "transcript_meta_field_equals": {
            "path": "entrypoint",
            "value": "sdk-py"
          }
        },
        "action": "drop",
        "reason": "noninteractive-sdk",
        "trim": true
      },
      {
        "event": "session_start",
        "scope": "this_agent",
        "when": {
          "transcript_meta_field_equals": {
            "path": "entrypoint",
            "value": "sdk-ts"
          }
        },
        "action": "drop",
        "reason": "noninteractive-sdk",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "transcript_meta_field_equals": {
            "path": "entrypoint",
            "value": "sdk-py"
          }
        },
        "action": "drop",
        "reason": "noninteractive-sdk",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "transcript_meta_field_equals": {
            "path": "entrypoint",
            "value": "sdk-ts"
          }
        },
        "action": "drop",
        "reason": "noninteractive-sdk",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_starts_with": "<command-message>"
        },
        "action": "drop",
        "reason": "claude-code-slash-command-dispatch",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_starts_with": "<command-name>"
        },
        "action": "drop",
        "reason": "claude-code-builtin-command-dispatch",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_starts_with": "<local-command-stdout>"
        },
        "action": "drop",
        "reason": "claude-code-builtin-command-stdout",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_starts_with": "<<autonomous-loop"
        },
        "action": "classify",
        "reason": "claude-code-autonomous-loop",
        "trim": true,
        "set_origin": "system"
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_envelope_tag_in": [
            "agent-message",
            "teammate-message"
          ]
        },
        "action": "classify",
        "reason": "claude-code-agent-envelope",
        "trim": true,
        "set_origin": "agent_dispatch"
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_envelope_tag_in": [
            "task-notification",
            "system-reminder",
            "skill",
            "environment_context",
            "persisted-output",
            "local-command-caveat"
          ]
        },
        "action": "classify",
        "reason": "claude-code-system-envelope",
        "trim": true,
        "set_origin": "system"
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "record_field_equals": {
            "path": "isCompactSummary",
            "value": true
          }
        },
        "action": "classify",
        "reason": "claude-code-compact-continuation-summary",
        "trim": true,
        "set_origin": "system"
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_is_enclosing_envelope": true
        },
        "action": "classify",
        "reason": "claude-code-unknown-envelope",
        "trim": true,
        "set_origin": "system"
      }
    ],
    "sessionContinuation": {
      "parentSessionIdPath": "session_id",
      "defaultReason": "fork",
      "markers": [
        {
          "recordFlagPath": "isCompactSummary",
          "reason": "compact continuation"
        }
      ]
    }
  },
  "cline": {
    "pluginRootEnvVar": "CLINE_PLUGIN_ROOT",
    "configDir": ".cline",
    "hookFields": {
      "sessionId": "conversationId",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": "tool_output"
    },
    "hookEvents": {},
    "planDirs": [],
    "planTags": [],
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false
    },
    "captureRules": [
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_starts_with": "<user_input mode=\"act\">"
        },
        "action": "rewrite_prompt",
        "reason": "strip Cline act user_input envelope",
        "strip_envelope": {
          "open": "<user_input mode=\"act\">",
          "close": "</user_input>"
        },
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_starts_with": "<user_input mode=\"plan\">"
        },
        "action": "rewrite_prompt",
        "reason": "strip Cline plan user_input envelope",
        "strip_envelope": {
          "open": "<user_input mode=\"plan\">",
          "close": "</user_input>"
        },
        "trim": true
      }
    ]
  },
  "codex": {
    "pluginRootEnvVar": "CODEX_PLUGIN_ROOT",
    "configDir": ".codex",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "hookEvents": {
      "PostToolUse": {
        "hook": "post-tool-use",
        "timeout": 5
      },
      "PreToolUse": {
        "hook": "pre-tool-use",
        "timeout": 3
      },
      "SessionStart": {
        "hook": "session-start",
        "timeout": 10
      },
      "Stop": {
        "hook": "stop",
        "timeout": 30
      },
      "SubagentStart": {
        "hook": "subagent-start",
        "timeout": 5
      },
      "UserPromptSubmit": {
        "hook": "user-prompt-submit",
        "timeout": 5
      }
    },
    "planDirs": [],
    "planTags": [
      "proposed_plan"
    ],
    "capabilities": {
      "preToolUseInjection": true,
      "sessionStartInjection": true,
      "subagentStartInjection": true
    },
    "transcriptDiscovery": {
      "roots": [
        "~/.codex/sessions"
      ],
      "patterns": [
        "*/*/*/rollout-*-{sessionId}.jsonl"
      ],
      "sessionIdPattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
      "transcriptCwdPath": "payload.cwd"
    },
    "capturePrompts": {
      "shapes": [
        {
          "name": "user_message",
          "match": {
            "type": "response_item",
            "fieldEquals": {
              "payload.type": "message",
              "payload.role": "user"
            }
          },
          "textAt": "payload.content",
          "textExtraction": "joined_text_parts"
        }
      ],
      "resetBoundaries": [
        {
          "match": {
            "type": "turn_context"
          },
          "changeOn": "payload.turn_id"
        }
      ],
      "interruptMarker": "<turn_aborted>"
    },
    "captureRules": [
      {
        "event": "session_start",
        "scope": "any_agent",
        "when": {
          "transcript_path_missing": true
        },
        "action": "drop",
        "reason": "ephemeral-sub-invocation",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "any_agent",
        "when": {
          "transcript_path_missing": true
        },
        "action": "drop",
        "reason": "ephemeral-sub-invocation",
        "trim": true
      },
      {
        "event": "session_start",
        "scope": "this_agent",
        "when": {
          "transcript_meta_field_exists": "source.subagent"
        },
        "action": "drop",
        "reason": "subagent-thread-spawn",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "transcript_meta_field_exists": "source.subagent"
        },
        "action": "drop",
        "reason": "subagent-thread-spawn",
        "trim": true
      },
      {
        "event": "session_start",
        "scope": "this_agent",
        "when": {
          "transcript_meta_field_equals": {
            "path": "source",
            "value": "exec"
          }
        },
        "action": "drop",
        "reason": "noninteractive-exec",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "transcript_meta_field_equals": {
            "path": "source",
            "value": "exec"
          }
        },
        "action": "drop",
        "reason": "noninteractive-exec",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_starts_with": "# AGENTS.md instructions"
        },
        "action": "drop",
        "reason": "agents-md-context-injection",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_contains": "# AGENTS.md instructions",
          "prompt_envelope_tag_in": [
            "recommended_plugins"
          ]
        },
        "action": "drop",
        "reason": "agents-md-context-injection-enveloped",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_envelope_tag_in": [
            "subagent_notification"
          ]
        },
        "action": "classify",
        "reason": "codex-agent-envelope",
        "trim": true,
        "set_origin": "agent_dispatch"
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_envelope_tag_in": [
            "environment_context",
            "skill"
          ]
        },
        "action": "classify",
        "reason": "codex-system-envelope",
        "trim": true,
        "set_origin": "system"
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_contains": "## My request for Codex:"
        },
        "action": "rewrite_prompt",
        "reason": "codex-desktop-file-preamble",
        "extract_after": "## My request for Codex:\n",
        "trim": true
      },
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_is_enclosing_envelope": true
        },
        "action": "classify",
        "reason": "codex-unknown-envelope",
        "trim": true,
        "set_origin": "system"
      }
    ],
    "subagentParentPath": "source.subagent.thread_spawn.parent_thread_id",
    "subagentThreadIdPath": "id",
    "subagentLabelPath": "source.subagent.thread_spawn"
  },
  "copilot": {
    "pluginRootEnvVar": "COPILOT_PLUGIN_ROOT",
    "configDir": ".vscode",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": "tool_response"
    },
    "hookEvents": {
      "ErrorOccurred": {
        "hook": "error-occurred",
        "timeout": 5
      },
      "Notification": {
        "hook": "notification",
        "timeout": 5
      },
      "PostToolUse": {
        "hook": "post-tool-use",
        "timeout": 5
      },
      "PostToolUseFailure": {
        "hook": "post-tool-use-failure",
        "timeout": 5
      },
      "PreCompact": {
        "hook": "pre-compact",
        "timeout": 5
      },
      "PreToolUse": {
        "hook": "pre-tool-use",
        "timeout": 5
      },
      "SessionEnd": {
        "hook": "session-end",
        "timeout": 10
      },
      "SessionStart": {
        "hook": "session-start",
        "timeout": 10
      },
      "Stop": {
        "hook": "stop",
        "timeout": 30
      },
      "SubagentStart": {
        "hook": "subagent-start",
        "timeout": 5
      },
      "SubagentStop": {
        "hook": "subagent-stop",
        "timeout": 10
      },
      "UserPromptSubmit": {
        "hook": "user-prompt-submit",
        "timeout": 5
      }
    },
    "planDirs": [],
    "planTags": [],
    "capabilities": {
      "preToolUseInjection": true,
      "sessionStartInjection": true,
      "subagentStartInjection": true
    },
    "transcriptDiscovery": {
      "roots": [
        "~/.copilot/session-state"
      ],
      "patterns": [
        "{sessionId}/events.jsonl"
      ]
    }
  },
  "cursor": {
    "pluginRootEnvVar": "CURSOR_PLUGIN_ROOT",
    "configDir": ".cursor",
    "hookFields": {
      "sessionId": [
        "conversation_id",
        "session_id"
      ],
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "hookEvents": {
      "beforeSubmitPrompt": {
        "hook": "user-prompt-submit",
        "timeout": 5
      },
      "postToolUse": {
        "hook": "post-tool-use",
        "timeout": 5
      },
      "postToolUseFailure": {
        "hook": "post-tool-use-failure",
        "timeout": 5
      },
      "preCompact": {
        "hook": "pre-compact",
        "timeout": 5
      },
      "sessionEnd": {
        "hook": "session-end",
        "timeout": 10
      },
      "sessionStart": {
        "hook": "session-start",
        "timeout": 10
      },
      "stop": {
        "hook": "stop",
        "timeout": 30
      },
      "subagentStart": {
        "hook": "subagent-start",
        "timeout": 5
      },
      "subagentStop": {
        "hook": "subagent-stop",
        "timeout": 10
      }
    },
    "planDirs": [
      "~/.cursor/plans/",
      ".cursor/plans/"
    ],
    "planTags": [],
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false
    },
    "transcriptDiscovery": {
      "roots": [
        "~/.cursor/projects"
      ],
      "patterns": [
        "*/agent-transcripts/{sessionId}.txt",
        "*/agent-transcripts/{sessionId}/{sessionId}.jsonl"
      ]
    },
    "hookResponse": {
      "format": "json",
      "fieldNames": {
        "additionalContext": "additional_context",
        "continue": "continue",
        "stopReason": "stop_reason",
        "userMessage": "user_message",
        "followupMessage": "followup_message",
        "systemMessage": "system_message"
      }
    },
    "captureRules": [
      {
        "event": "user_prompt",
        "scope": "this_agent",
        "when": {
          "prompt_starts_with": "<user_query>"
        },
        "action": "rewrite_prompt",
        "reason": "strip Cursor user_query envelope",
        "strip_envelope": {
          "open": "<user_query>",
          "close": "</user_query>"
        },
        "trim": true
      }
    ]
  },
  "opencode": {
    "pluginRootEnvVar": "OPENCODE_PLUGIN_ROOT",
    "configDir": ".opencode",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "hookEvents": {},
    "planDirs": [
      ".opencode/plans/"
    ],
    "planTags": [],
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false
    }
  },
  "pi": {
    "pluginRootEnvVar": "PI_PLUGIN_ROOT",
    "configDir": ".pi",
    "hookFields": {
      "sessionId": "session_id",
      "transcriptPath": "transcript_path",
      "lastResponse": "last_assistant_message",
      "prompt": "prompt",
      "toolName": "tool_name",
      "toolInput": "tool_input",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "hookEvents": {},
    "planDirs": [
      ".pi/plans/"
    ],
    "planTags": [],
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": true,
      "subagentStartInjection": false
    }
  },
  "windsurf": {
    "pluginRootEnvVar": "WINDSURF_PLUGIN_ROOT",
    "configDir": ".windsurf",
    "hookFields": {
      "sessionId": "trajectory_id",
      "transcriptPath": "tool_info.transcript_path",
      "lastResponse": "tool_info.response",
      "prompt": "tool_info.user_prompt",
      "toolName": "agent_action_name",
      "toolInput": "tool_info",
      "toolOutput": [
        "tool_output",
        "tool_response"
      ]
    },
    "hookEvents": {
      "post_cascade_response": {
        "hook": "stop"
      },
      "post_cascade_response_with_transcript": {
        "hook": "stop"
      },
      "post_run_command": {
        "hook": "post-tool-use"
      },
      "post_write_code": {
        "hook": "post-tool-use"
      },
      "pre_user_prompt": {
        "hook": "user-prompt-submit"
      }
    },
    "planDirs": [
      "~/.windsurf/plans/"
    ],
    "planTags": [],
    "capabilities": {
      "preToolUseInjection": false,
      "sessionStartInjection": false,
      "subagentStartInjection": false
    },
    "transcriptDiscovery": {
      "roots": [
        "~/.windsurf/transcripts"
      ],
      "patterns": [
        "{sessionId}.jsonl"
      ]
    }
  }
} as const;
