import fs from 'node:fs';
export default fs;
export const appendFileSync: typeof fs.appendFileSync;
export const chmodSync: typeof fs.chmodSync;
export const copyFileSync: typeof fs.copyFileSync;
export const existsSync: typeof fs.existsSync;
export const lstatSync: typeof fs.lstatSync;
export const mkdirSync: typeof fs.mkdirSync;
export const mkdtempSync: typeof fs.mkdtempSync;
export const readFileSync: typeof fs.readFileSync;
export const readdirSync: typeof fs.readdirSync;
export const readlinkSync: typeof fs.readlinkSync;
export const realpathSync: typeof fs.realpathSync;
export const rmSync: typeof fs.rmSync;
export const statSync: typeof fs.statSync;
export const symlinkSync: typeof fs.symlinkSync;
export const unlinkSync: typeof fs.unlinkSync;
export const utimesSync: typeof fs.utimesSync;
export const writeFileSync: typeof fs.writeFileSync;
export type * from 'node:fs';
