/**
 * Activity insert/query helpers.
 *
 * All functions obtain the PGlite instance internally via `getDatabase()`.
 * Queries use parameterized placeholders ($1, $2, ...) throughout.
 */

import { getDatabase } from '@myco/db/client.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Default number of activities returned by listActivities when no limit given. */
const DEFAULT_LIST_LIMIT = 100;

/** Default success flag for new activities. */
const DEFAULT_SUCCESS = 1;

/** Default processed flag for new activities. */
const DEFAULT_PROCESSED = 0;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Fields required (or optional) when inserting an activity. */
export interface ActivityInsert {
  session_id: string;
  tool_name: string;
  timestamp: number;
  created_at: number;
  prompt_batch_id?: number | null;
  tool_input?: string | null;
  tool_output_summary?: string | null;
  file_path?: string | null;
  files_affected?: string | null;
  duration_ms?: number | null;
  success?: number;
  error_message?: string | null;
  processed?: number;
  content_hash?: string | null;
}

/** Row shape returned from activity queries. */
export interface ActivityRow {
  id: number;
  session_id: string;
  prompt_batch_id: number | null;
  tool_name: string;
  tool_input: string | null;
  tool_output_summary: string | null;
  file_path: string | null;
  files_affected: string | null;
  duration_ms: number | null;
  success: number;
  error_message: string | null;
  timestamp: number;
  processed: number;
  content_hash: string | null;
  created_at: number;
}

/** Filter options for `listActivities`. */
export interface ListActivitiesOptions {
  session_id?: string;
  prompt_batch_id?: number;
  limit?: number;
}

// ---------------------------------------------------------------------------
// Column list
// ---------------------------------------------------------------------------

const ACTIVITY_COLUMNS = [
  'id',
  'session_id',
  'prompt_batch_id',
  'tool_name',
  'tool_input',
  'tool_output_summary',
  'file_path',
  'files_affected',
  'duration_ms',
  'success',
  'error_message',
  'timestamp',
  'processed',
  'content_hash',
  'created_at',
] as const;

const SELECT_COLUMNS = ACTIVITY_COLUMNS.join(', ');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Normalize a PGlite result row into a typed ActivityRow. */
function toActivityRow(row: Record<string, unknown>): ActivityRow {
  return {
    id: row.id as number,
    session_id: row.session_id as string,
    prompt_batch_id: (row.prompt_batch_id as number) ?? null,
    tool_name: row.tool_name as string,
    tool_input: (row.tool_input as string) ?? null,
    tool_output_summary: (row.tool_output_summary as string) ?? null,
    file_path: (row.file_path as string) ?? null,
    files_affected: (row.files_affected as string) ?? null,
    duration_ms: (row.duration_ms as number) ?? null,
    success: row.success as number,
    error_message: (row.error_message as string) ?? null,
    timestamp: row.timestamp as number,
    processed: row.processed as number,
    content_hash: (row.content_hash as string) ?? null,
    created_at: row.created_at as number,
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Insert a new activity row.
 *
 * The `id` is auto-generated by the SERIAL primary key.
 */
export async function insertActivity(data: ActivityInsert): Promise<ActivityRow> {
  const db = getDatabase();

  const result = await db.query(
    `INSERT INTO activities (
       session_id, prompt_batch_id, tool_name, tool_input,
       tool_output_summary, file_path, files_affected, duration_ms,
       success, error_message, timestamp, processed,
       content_hash, created_at
     ) VALUES (
       $1, $2, $3, $4,
       $5, $6, $7, $8,
       $9, $10, $11, $12,
       $13, $14
     )
     RETURNING ${SELECT_COLUMNS}`,
    [
      data.session_id,
      data.prompt_batch_id ?? null,
      data.tool_name,
      data.tool_input ?? null,
      data.tool_output_summary ?? null,
      data.file_path ?? null,
      data.files_affected ?? null,
      data.duration_ms ?? null,
      data.success ?? DEFAULT_SUCCESS,
      data.error_message ?? null,
      data.timestamp,
      data.processed ?? DEFAULT_PROCESSED,
      data.content_hash ?? null,
      data.created_at,
    ],
  );

  return toActivityRow(result.rows[0] as Record<string, unknown>);
}

/**
 * List activities with optional filters, ordered by timestamp ASC.
 *
 * At least one of `session_id` or `prompt_batch_id` should be provided
 * to avoid unbounded queries.
 */
export async function listActivities(
  options: ListActivitiesOptions = {},
): Promise<ActivityRow[]> {
  const db = getDatabase();

  const conditions: string[] = [];
  const params: unknown[] = [];
  let paramIndex = 1;

  if (options.session_id !== undefined) {
    conditions.push(`session_id = $${paramIndex++}`);
    params.push(options.session_id);
  }

  if (options.prompt_batch_id !== undefined) {
    conditions.push(`prompt_batch_id = $${paramIndex++}`);
    params.push(options.prompt_batch_id);
  }

  const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
  const limit = options.limit ?? DEFAULT_LIST_LIMIT;

  params.push(limit);

  const result = await db.query(
    `SELECT ${SELECT_COLUMNS}
     FROM activities
     ${where}
     ORDER BY timestamp ASC
     LIMIT $${paramIndex}`,
    params,
  );

  return (result.rows as Record<string, unknown>[]).map(toActivityRow);
}

/**
 * Count total activities for a given session.
 */
export async function countActivities(sessionId: string): Promise<number> {
  const db = getDatabase();

  const result = await db.query(
    `SELECT COUNT(*)::integer AS count FROM activities WHERE session_id = $1`,
    [sessionId],
  );

  return (result.rows[0] as Record<string, unknown>).count as number;
}
