/**
 * Prompt batch CRUD query helpers.
 *
 * All functions obtain the SQLite instance internally via `getDatabase()`.
 * Queries use positional `?` placeholders throughout (better-sqlite3).
 */

import { getDatabase } from '@myco/db/client.js';
import { DEFAULT_MACHINE_ID } from '@myco/constants.js';
import { syncRow } from '@myco/db/queries/team-outbox.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Default number of unprocessed batches returned when no limit given. */
const DEFAULT_UNPROCESSED_LIMIT = 100;

/** Default number of batches returned by listBatchesBySession when no limit given. */
export const BATCHES_DEFAULT_LIMIT = 200;

/** Batch status value when a batch is closed normally. */
const STATUS_COMPLETED = 'completed';

/** Default batch status for new batches. */
const DEFAULT_STATUS = 'active';

/** Default activity count for new batches. */
const DEFAULT_ACTIVITY_COUNT = 0;

/** Default processed flag for new batches. */
const DEFAULT_PROCESSED = 0;

/** Processed flag value indicating a batch has been processed. */
const PROCESSED_FLAG = 1;

/** Number of characters used for prompt prefix matching. */
const PROMPT_PREFIX_MATCH_CHARS = 60;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Filter options for `listBatchesBySession`. */
export interface ListBatchesBySessionOptions {
  limit?: number;
  offset?: number;
}

/** Fields required (or optional) when inserting a prompt batch. */
export interface BatchInsert {
  session_id: string;
  created_at: number;
  prompt_number?: number | null;
  user_prompt?: string | null;
  response_summary?: string | null;
  classification?: string | null;
  started_at?: number | null;
  ended_at?: number | null;
  status?: string;
  activity_count?: number;
  processed?: number;
  content_hash?: string | null;
  machine_id?: string;
}

/** Row shape returned from batch queries. */
export interface BatchRow {
  id: number;
  session_id: string;
  prompt_number: number | null;
  user_prompt: string | null;
  response_summary: string | null;
  classification: string | null;
  started_at: number | null;
  ended_at: number | null;
  status: string;
  activity_count: number;
  processed: number;
  content_hash: string | null;
  created_at: number;
  machine_id: string;
  synced_at: number | null;
}

// ---------------------------------------------------------------------------
// Column list
// ---------------------------------------------------------------------------

const BATCH_COLUMNS = [
  'id',
  'session_id',
  'prompt_number',
  'user_prompt',
  'response_summary',
  'classification',
  'started_at',
  'ended_at',
  'status',
  'activity_count',
  'processed',
  'content_hash',
  'created_at',
  'machine_id',
  'synced_at',
] as const;

const SELECT_COLUMNS = BATCH_COLUMNS.join(', ');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Normalize a SQLite result row into a typed BatchRow. */
function toBatchRow(row: Record<string, unknown>): BatchRow {
  return {
    id: row.id as number,
    session_id: row.session_id as string,
    prompt_number: (row.prompt_number as number) ?? null,
    user_prompt: (row.user_prompt as string) ?? null,
    response_summary: (row.response_summary as string) ?? null,
    classification: (row.classification as string) ?? null,
    started_at: (row.started_at as number) ?? null,
    ended_at: (row.ended_at as number) ?? null,
    status: row.status as string,
    activity_count: row.activity_count as number,
    processed: row.processed as number,
    content_hash: (row.content_hash as string) ?? null,
    created_at: row.created_at as number,
    machine_id: (row.machine_id as string) ?? DEFAULT_MACHINE_ID,
    synced_at: (row.synced_at as number) ?? null,
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Insert a new prompt batch.
 *
 * The `id` is auto-generated by the INTEGER PRIMARY KEY (AUTOINCREMENT).
 * FTS5 index is kept in sync via a follow-up INSERT into prompt_batches_fts.
 */
export function insertBatch(data: BatchInsert): BatchRow {
  const db = getDatabase();

  const info = db.prepare(
    `INSERT INTO prompt_batches (
       session_id, prompt_number, user_prompt, response_summary,
       classification, started_at, ended_at, status,
       activity_count, processed, content_hash, created_at, machine_id
     ) VALUES (
       ?, ?, ?, ?,
       ?, ?, ?, ?,
       ?, ?, ?, ?, ?
     )`,
  ).run(
    data.session_id,
    data.prompt_number ?? null,
    data.user_prompt ?? null,
    data.response_summary ?? null,
    data.classification ?? null,
    data.started_at ?? null,
    data.ended_at ?? null,
    data.status ?? DEFAULT_STATUS,
    data.activity_count ?? DEFAULT_ACTIVITY_COUNT,
    data.processed ?? DEFAULT_PROCESSED,
    data.content_hash ?? null,
    data.created_at,
    data.machine_id ?? DEFAULT_MACHINE_ID,
  );

  const batchId = Number(info.lastInsertRowid);

  // FTS5 sync
  const userPrompt = data.user_prompt ?? null;
  if (userPrompt) {
    db.prepare('INSERT INTO prompt_batches_fts(rowid, user_prompt) VALUES (?, ?)').run(batchId, userPrompt);
  }

  const row = toBatchRow(
    db.prepare(`SELECT ${SELECT_COLUMNS} FROM prompt_batches WHERE id = ?`).get(batchId) as Record<string, unknown>,
  );

  syncRow('prompt_batches', row);

  return row;
}

/**
 * Close a batch — set status to 'completed' and record the end time.
 *
 * @returns the updated row, or null if the batch does not exist.
 */
export function closeBatch(
  id: number,
  endedAt: number,
): BatchRow | null {
  const db = getDatabase();

  const info = db.prepare(
    `UPDATE prompt_batches
     SET status = ?, ended_at = ?
     WHERE id = ?`,
  ).run(STATUS_COMPLETED, endedAt, id);

  if (info.changes === 0) return null;

  return toBatchRow(
    db.prepare(`SELECT ${SELECT_COLUMNS} FROM prompt_batches WHERE id = ?`).get(id) as Record<string, unknown>,
  );
}

/**
 * Populate response_summary on batches from transcript turns.
 *
 * Matches transcript turns (ordered by position) to batches (ordered by id ASC).
 * This is resilient to prompt_number duplicates caused by daemon restarts.
 * Only updates batches that don't already have a response_summary.
 *
 * @param sessionId — the session to update
 * @param responses — array of { response } ordered by turn position (1-indexed)
 */
export function populateBatchResponses(
  sessionId: string,
  responses: Array<{ turnIndex: number; response: string }>,
): void {
  const db = getDatabase();

  // Get all batches for this session ordered by id (insertion order = true order)
  const batches = db.prepare(
    `SELECT id FROM prompt_batches WHERE session_id = ? ORDER BY id ASC`,
  ).all(sessionId) as Array<{ id: number }>;

  // Map each response to the batch at the same position
  for (const { turnIndex, response } of responses) {
    const batchIndex = turnIndex - 1; // turns are 1-indexed
    if (batchIndex >= 0 && batchIndex < batches.length) {
      const batchId = batches[batchIndex].id;
      db.prepare(
        `UPDATE prompt_batches SET response_summary = ? WHERE id = ? AND response_summary IS NULL`,
      ).run(response, batchId);
    }
  }
}

/**
 * Get unprocessed batches, ordered by id ASC (insertion order).
 *
 * Supports cursor-based pagination via `after_id` and a `limit` cap.
 */
export function getUnprocessedBatches(
  options: { after_id?: number; limit?: number } = {},
): BatchRow[] {
  const db = getDatabase();

  const conditions: string[] = [`processed = ?`];
  const params: unknown[] = [DEFAULT_PROCESSED];

  if (options.after_id !== undefined) {
    conditions.push(`id > ?`);
    params.push(options.after_id);
  }

  const limit = options.limit ?? DEFAULT_UNPROCESSED_LIMIT;
  params.push(limit);

  const where = conditions.join(' AND ');

  const rows = db.prepare(
    `SELECT ${SELECT_COLUMNS}
     FROM prompt_batches
     WHERE ${where}
     ORDER BY id ASC
     LIMIT ?`,
  ).all(...params) as Record<string, unknown>[];

  return rows.map(toBatchRow);
}

/**
 * Increment the activity_count for a batch by 1.
 *
 * @returns the updated row, or null if the batch does not exist.
 */
export function incrementActivityCount(
  id: number,
): BatchRow | null {
  const db = getDatabase();

  const info = db.prepare(
    `UPDATE prompt_batches
     SET activity_count = activity_count + 1
     WHERE id = ?`,
  ).run(id);

  if (info.changes === 0) return null;

  return toBatchRow(
    db.prepare(`SELECT ${SELECT_COLUMNS} FROM prompt_batches WHERE id = ?`).get(id) as Record<string, unknown>,
  );
}

/**
 * Mark a batch as processed (processed = 1).
 *
 * @returns the updated row, or null if the batch does not exist.
 */
export function markBatchProcessed(
  id: number,
): BatchRow | null {
  const db = getDatabase();

  const info = db.prepare(
    `UPDATE prompt_batches
     SET processed = ?
     WHERE id = ?`,
  ).run(PROCESSED_FLAG, id);

  if (info.changes === 0) return null;

  return toBatchRow(
    db.prepare(`SELECT ${SELECT_COLUMNS} FROM prompt_batches WHERE id = ?`).get(id) as Record<string, unknown>,
  );
}

/**
 * Get a batch's ID by session and prompt number.
 * Used to link attachments to their prompt batch at stop time.
 */
export function getBatchIdByPromptNumber(
  sessionId: string,
  promptNumber: number,
): number | null {
  const db = getDatabase();

  const row = db.prepare(
    `SELECT id FROM prompt_batches WHERE session_id = ? AND prompt_number = ? LIMIT 1`,
  ).get(sessionId, promptNumber) as { id: number } | undefined;

  return row ? row.id : null;
}

/**
 * Find a batch by matching the start of its user_prompt text.
 * Used for attachment matching after transcript compaction where turn indices no longer
 * align with prompt_numbers.
 */
export function findBatchByPromptPrefix(
  sessionId: string,
  promptPrefix: string,
): { id: number; prompt_number: number } | null {
  const db = getDatabase();
  // Match first N chars — enough to be unique, tolerant of minor differences
  const prefix = promptPrefix.slice(0, PROMPT_PREFIX_MATCH_CHARS);
  const row = db.prepare(
    `SELECT id, prompt_number FROM prompt_batches
     WHERE session_id = ? AND user_prompt LIKE ? || '%'
     LIMIT 1`,
  ).get(sessionId, prefix) as { id: number; prompt_number: number } | undefined;
  return row ?? null;
}

/** Fields required when inserting a batch statelessly (prompt_number derived from DB). */
export interface StatelessBatchInsert {
  session_id: string;
  created_at: number;
  user_prompt?: string | null;
  started_at?: number | null;
  status?: string;
}

/**
 * Insert a new prompt batch with prompt_number derived from an inline subquery.
 *
 * The prompt_number is set to `COALESCE(MAX(prompt_number), 0) + 1` for the
 * session, so the caller never needs a separate SELECT. This makes the insert
 * stateless — no in-memory counter required.
 *
 * FTS5 index is kept in sync via a follow-up INSERT into prompt_batches_fts.
 */
export function insertBatchStateless(data: StatelessBatchInsert): BatchRow {
  const db = getDatabase();

  const info = db.prepare(
    `INSERT INTO prompt_batches (
       session_id, prompt_number, user_prompt, response_summary,
       classification, started_at, ended_at, status,
       activity_count, processed, content_hash, created_at, machine_id
     ) VALUES (
       ?,
       (SELECT COALESCE(MAX(prompt_number), 0) + 1 FROM prompt_batches WHERE session_id = ?),
       ?, NULL,
       NULL, ?, NULL, ?,
       ?, ?, NULL, ?, ?
     )`,
  ).run(
    data.session_id,
    data.session_id,
    data.user_prompt ?? null,
    data.started_at ?? null,
    data.status ?? DEFAULT_STATUS,
    DEFAULT_ACTIVITY_COUNT,
    DEFAULT_PROCESSED,
    data.created_at,
    DEFAULT_MACHINE_ID,
  );

  const batchId = Number(info.lastInsertRowid);

  // FTS5 sync
  const userPrompt = data.user_prompt ?? null;
  if (userPrompt) {
    db.prepare('INSERT INTO prompt_batches_fts(rowid, user_prompt) VALUES (?, ?)').run(batchId, userPrompt);
  }

  return toBatchRow(
    db.prepare(`SELECT ${SELECT_COLUMNS} FROM prompt_batches WHERE id = ?`).get(batchId) as Record<string, unknown>,
  );
}

/**
 * Close all open batches for a session — blind UPDATE, no prior SELECT needed.
 *
 * Sets `status = 'completed'` and `ended_at` on every batch that has no
 * `ended_at` value yet. Returns the number of batches closed.
 */
export function closeOpenBatches(
  sessionId: string,
  endedAt: number,
): number {
  const db = getDatabase();

  const info = db.prepare(
    `UPDATE prompt_batches
     SET status = ?, ended_at = ?
     WHERE session_id = ? AND ended_at IS NULL`,
  ).run(STATUS_COMPLETED, endedAt, sessionId);

  return info.changes;
}

/**
 * Set response_summary on a batch if it doesn't already have one.
 *
 * Idempotent — only updates NULL response_summary.
 */
export function setResponseSummary(
  batchId: number,
  summary: string,
): void {
  const db = getDatabase();
  db.prepare(
    `UPDATE prompt_batches SET response_summary = ? WHERE id = ? AND response_summary IS NULL`,
  ).run(summary, batchId);
}

/**
 * Get the most recent batch for a session (by id DESC), regardless of status.
 *
 * Used by processStopEvent to attach the AI response and images to the
 * correct batch without positional turn mapping.
 */
export function getLatestBatch(
  sessionId: string,
): BatchRow | null {
  const db = getDatabase();

  const row = db.prepare(
    `SELECT ${SELECT_COLUMNS} FROM prompt_batches
     WHERE session_id = ?
     ORDER BY id DESC LIMIT 1`,
  ).get(sessionId) as Record<string, unknown> | undefined;

  if (!row) return null;
  return toBatchRow(row);
}

export function listBatchesBySession(
  sessionId: string,
  options: ListBatchesBySessionOptions = {},
): BatchRow[] {
  const db = getDatabase();

  const limit = options.limit ?? BATCHES_DEFAULT_LIMIT;
  const offset = options.offset ?? 0;

  const rows = db.prepare(
    `SELECT ${SELECT_COLUMNS}
     FROM prompt_batches
     WHERE session_id = ?
     ORDER BY prompt_number ASC
     LIMIT ?
     OFFSET ?`,
  ).all(sessionId, limit, offset) as Record<string, unknown>[];

  return rows.map(toBatchRow);
}
