/**
 * Prompt batch CRUD query helpers.
 *
 * All functions obtain the PGlite instance internally via `getDatabase()`.
 * Queries use parameterized placeholders ($1, $2, ...) throughout.
 */

import { getDatabase } from '@myco/db/client.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Default number of unprocessed batches returned when no limit given. */
const DEFAULT_UNPROCESSED_LIMIT = 100;

/** Default number of batches returned by listBatchesBySession when no limit given. */
export const BATCHES_DEFAULT_LIMIT = 200;

/** Batch status value when a batch is closed normally. */
const STATUS_COMPLETED = 'completed';

/** Default batch status for new batches. */
const DEFAULT_STATUS = 'active';

/** Default activity count for new batches. */
const DEFAULT_ACTIVITY_COUNT = 0;

/** Default processed flag for new batches. */
const DEFAULT_PROCESSED = 0;

/** Processed flag value indicating a batch has been processed. */
const PROCESSED_FLAG = 1;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Filter options for `listBatchesBySession`. */
export interface ListBatchesBySessionOptions {
  limit?: number;
  offset?: number;
}

/** Fields required (or optional) when inserting a prompt batch. */
export interface BatchInsert {
  session_id: string;
  created_at: number;
  prompt_number?: number | null;
  user_prompt?: string | null;
  response_summary?: string | null;
  classification?: string | null;
  started_at?: number | null;
  ended_at?: number | null;
  status?: string;
  activity_count?: number;
  processed?: number;
  content_hash?: string | null;
}

/** Row shape returned from batch queries (all columns, no embedding). */
export interface BatchRow {
  id: number;
  session_id: string;
  prompt_number: number | null;
  user_prompt: string | null;
  response_summary: string | null;
  classification: string | null;
  started_at: number | null;
  ended_at: number | null;
  status: string;
  activity_count: number;
  processed: number;
  content_hash: string | null;
  created_at: number;
}

// ---------------------------------------------------------------------------
// Column list (excludes embedding — not useful in CRUD results)
// ---------------------------------------------------------------------------

const BATCH_COLUMNS = [
  'id',
  'session_id',
  'prompt_number',
  'user_prompt',
  'response_summary',
  'classification',
  'started_at',
  'ended_at',
  'status',
  'activity_count',
  'processed',
  'content_hash',
  'created_at',
] as const;

const SELECT_COLUMNS = BATCH_COLUMNS.join(', ');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Normalize a PGlite result row into a typed BatchRow. */
function toBatchRow(row: Record<string, unknown>): BatchRow {
  return {
    id: row.id as number,
    session_id: row.session_id as string,
    prompt_number: (row.prompt_number as number) ?? null,
    user_prompt: (row.user_prompt as string) ?? null,
    response_summary: (row.response_summary as string) ?? null,
    classification: (row.classification as string) ?? null,
    started_at: (row.started_at as number) ?? null,
    ended_at: (row.ended_at as number) ?? null,
    status: row.status as string,
    activity_count: row.activity_count as number,
    processed: row.processed as number,
    content_hash: (row.content_hash as string) ?? null,
    created_at: row.created_at as number,
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Insert a new prompt batch.
 *
 * The `id` is auto-generated by the SERIAL primary key.
 */
export async function insertBatch(data: BatchInsert): Promise<BatchRow> {
  const db = getDatabase();

  const result = await db.query(
    `INSERT INTO prompt_batches (
       session_id, prompt_number, user_prompt, response_summary,
       classification, started_at, ended_at, status,
       activity_count, processed, content_hash, created_at,
       search_vector
     ) VALUES (
       $1, $2, $3, $4,
       $5, $6, $7, $8,
       $9, $10, $11, $12,
       to_tsvector('english', COALESCE($3, ''))
     )
     RETURNING ${SELECT_COLUMNS}`,
    [
      data.session_id,
      data.prompt_number ?? null,
      data.user_prompt ?? null,
      data.response_summary ?? null,
      data.classification ?? null,
      data.started_at ?? null,
      data.ended_at ?? null,
      data.status ?? DEFAULT_STATUS,
      data.activity_count ?? DEFAULT_ACTIVITY_COUNT,
      data.processed ?? DEFAULT_PROCESSED,
      data.content_hash ?? null,
      data.created_at,
    ],
  );

  return toBatchRow(result.rows[0] as Record<string, unknown>);
}

/**
 * Close a batch — set status to 'completed' and record the end time.
 *
 * @returns the updated row, or null if the batch does not exist.
 */
export async function closeBatch(
  id: number,
  endedAt: number,
): Promise<BatchRow | null> {
  const db = getDatabase();

  const result = await db.query(
    `UPDATE prompt_batches
     SET status = $1, ended_at = $2
     WHERE id = $3
     RETURNING ${SELECT_COLUMNS}`,
    [STATUS_COMPLETED, endedAt, id],
  );

  if (result.rows.length === 0) return null;
  return toBatchRow(result.rows[0] as Record<string, unknown>);
}

/**
 * Update the response_summary for a batch by prompt_number within a session.
 *
 * Used at stop time to populate AI responses from the transcript.
 */
export async function updateBatchResponseSummary(
  sessionId: string,
  promptNumber: number,
  responseSummary: string,
): Promise<void> {
  const db = getDatabase();
  await db.query(
    `UPDATE prompt_batches
     SET response_summary = $1
     WHERE session_id = $2 AND prompt_number = $3 AND response_summary IS NULL`,
    [responseSummary, sessionId, promptNumber],
  );
}

/**
 * Get unprocessed batches, ordered by id ASC (insertion order).
 *
 * Supports cursor-based pagination via `after_id` and a `limit` cap.
 */
export async function getUnprocessedBatches(
  options: { after_id?: number; limit?: number } = {},
): Promise<BatchRow[]> {
  const db = getDatabase();

  const conditions: string[] = [`processed = $1`];
  const params: unknown[] = [DEFAULT_PROCESSED];
  let paramIndex = 2;

  if (options.after_id !== undefined) {
    conditions.push(`id > $${paramIndex++}`);
    params.push(options.after_id);
  }

  const limit = options.limit ?? DEFAULT_UNPROCESSED_LIMIT;
  params.push(limit);

  const where = conditions.join(' AND ');

  const result = await db.query(
    `SELECT ${SELECT_COLUMNS}
     FROM prompt_batches
     WHERE ${where}
     ORDER BY id ASC
     LIMIT $${paramIndex}`,
    params,
  );

  return (result.rows as Record<string, unknown>[]).map(toBatchRow);
}

/**
 * Increment the activity_count for a batch by 1.
 *
 * @returns the updated row, or null if the batch does not exist.
 */
export async function incrementActivityCount(
  id: number,
): Promise<BatchRow | null> {
  const db = getDatabase();

  const result = await db.query(
    `UPDATE prompt_batches
     SET activity_count = activity_count + 1
     WHERE id = $1
     RETURNING ${SELECT_COLUMNS}`,
    [id],
  );

  if (result.rows.length === 0) return null;
  return toBatchRow(result.rows[0] as Record<string, unknown>);
}

/**
 * Mark a batch as processed (processed = 1).
 *
 * @returns the updated row, or null if the batch does not exist.
 */
export async function markBatchProcessed(
  id: number,
): Promise<BatchRow | null> {
  const db = getDatabase();

  const result = await db.query(
    `UPDATE prompt_batches
     SET processed = $1
     WHERE id = $2
     RETURNING ${SELECT_COLUMNS}`,
    [PROCESSED_FLAG, id],
  );

  if (result.rows.length === 0) return null;
  return toBatchRow(result.rows[0] as Record<string, unknown>);
}

/**
 * List all prompt batches for a session, ordered by prompt_number ASC.
 *
 * Supports optional limit and offset for pagination.
 */
export async function listBatchesBySession(
  sessionId: string,
  options: ListBatchesBySessionOptions = {},
): Promise<BatchRow[]> {
  const db = getDatabase();

  const limit = options.limit ?? BATCHES_DEFAULT_LIMIT;
  const offset = options.offset ?? 0;

  const result = await db.query(
    `SELECT ${SELECT_COLUMNS}
     FROM prompt_batches
     WHERE session_id = $1
     ORDER BY prompt_number ASC
     LIMIT $2
     OFFSET $3`,
    [sessionId, limit, offset],
  );

  return (result.rows as Record<string, unknown>[]).map(toBatchRow);
}
