/**
 * Agent turn CRUD query helpers.
 *
 * All functions obtain the SQLite instance internally via `getDatabase()`.
 * Queries use positional `?` placeholders throughout (better-sqlite3).
 */

import { getDatabase } from '@myco/db/client.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Fields required (or optional) when inserting a turn. */
export interface TurnInsert {
  run_id: string;
  agent_id: string;
  turn_number: number;
  tool_name: string;
  tool_input?: string | null;
  tool_output_summary?: string | null;
  started_at?: number | null;
  completed_at?: number | null;
}

/** Row shape returned from agent_turns queries (all columns). */
export interface TurnRow {
  id: number;
  run_id: string;
  agent_id: string;
  turn_number: number;
  tool_name: string;
  tool_input: string | null;
  tool_output_summary: string | null;
  started_at: number | null;
  completed_at: number | null;
}

// ---------------------------------------------------------------------------
// Column list
// ---------------------------------------------------------------------------

const TURN_COLUMNS = [
  'id',
  'run_id',
  'agent_id',
  'turn_number',
  'tool_name',
  'tool_input',
  'tool_output_summary',
  'started_at',
  'completed_at',
] as const;

const SELECT_COLUMNS = TURN_COLUMNS.join(', ');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Normalize a SQLite result row into a typed TurnRow. */
function toTurnRow(row: Record<string, unknown>): TurnRow {
  return {
    id: row.id as number,
    run_id: row.run_id as string,
    agent_id: row.agent_id as string,
    turn_number: row.turn_number as number,
    tool_name: row.tool_name as string,
    tool_input: (row.tool_input as string) ?? null,
    tool_output_summary: (row.tool_output_summary as string) ?? null,
    started_at: (row.started_at as number) ?? null,
    completed_at: (row.completed_at as number) ?? null,
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Insert a new agent turn.
 *
 * The `id` is auto-generated by the INTEGER PRIMARY KEY (AUTOINCREMENT).
 */
export function insertTurn(data: TurnInsert): TurnRow {
  const db = getDatabase();

  const info = db.prepare(
    `INSERT INTO agent_turns (
       run_id, agent_id, turn_number, tool_name,
       tool_input, tool_output_summary, started_at, completed_at
     ) VALUES (
       ?, ?, ?, ?,
       ?, ?, ?, ?
     )`,
  ).run(
    data.run_id,
    data.agent_id,
    data.turn_number,
    data.tool_name,
    data.tool_input ?? null,
    data.tool_output_summary ?? null,
    data.started_at ?? null,
    data.completed_at ?? null,
  );

  const turnId = Number(info.lastInsertRowid);

  return toTurnRow(
    db.prepare(`SELECT ${SELECT_COLUMNS} FROM agent_turns WHERE id = ?`).get(turnId) as Record<string, unknown>,
  );
}

/**
 * List all turns for a specific run, ordered by turn_number ASC.
 */
export function listTurns(runId: string): TurnRow[] {
  const db = getDatabase();

  const rows = db.prepare(
    `SELECT ${SELECT_COLUMNS}
     FROM agent_turns
     WHERE run_id = ?
     ORDER BY turn_number ASC`,
  ).all(runId) as Record<string, unknown>[];

  return rows.map(toTurnRow);
}

/**
 * List all agent turns for a run, ordered by turn_number ASC.
 *
 * Alias for `listTurns` with an explicit "by run" naming convention used
 * by the dashboard API layer.
 */
export function listTurnsByRun(runId: string): TurnRow[] {
  return listTurns(runId);
}
