// AUTO-GENERATED by scripts/gen-hook-config.ts — DO NOT EDIT.

/** Each agent's resume command, from its symbiont manifest, keyed by the agent's name; `{sessionId}` stands for the session. An agent whose manifest names none is absent. */
export const RESUME_COMMANDS: Readonly<Record<string, string>> = {
  "claude-code": "claude --resume {sessionId}",
  "cline": "cline --id {sessionId}",
  "codex": "codex resume {sessionId}",
  "opencode": "opencode --session {sessionId}"
};
