// AUTO-GENERATED by scripts/gen-hook-config.ts — DO NOT EDIT.

/** Each harness a worker runs, in the order a worker ranks them, as its manifest's `runner:` block declares it. */
export const RUNNER_HARNESSES = [
  {
    "id": "claude-code",
    "asking": {
      "kind": "native"
    },
    "credential": {
      "provider": "anthropic",
      "slot": "anthropic",
      "variables": [
        "CLAUDE_CODE_OAUTH_TOKEN",
        "ANTHROPIC_API_KEY"
      ],
      "accepts": [
        "subscription",
        "api-key"
      ]
    },
    "profile": {
      "models": {
        "low": "haiku",
        "default": "sonnet",
        "high": "opus"
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "modelPattern": "^(haiku|sonnet|opus|fable|claude-[A-Za-z0-9][A-Za-z0-9._-]{0,240})$",
      "modelHint": "Use haiku, sonnet, opus, fable, or a claude-* model ID.",
      "modelFamilies": [
        "haiku",
        "sonnet",
        "opus",
        "fable"
      ],
      "modelFamilyPrefix": "claude-"
    }
  },
  {
    "id": "codex",
    "asking": {
      "kind": "sandbox"
    },
    "credential": {
      "provider": "openai",
      "slot": "codex",
      "variables": [
        "OPENAI_API_KEY"
      ]
    },
    "profile": {
      "models": {
        "low": null,
        "default": null,
        "high": null
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$",
      "modelHint": "Use a Codex model ID. An unset model holds runs at this tier."
    }
  },
  {
    "id": "opencode",
    "asking": {
      "kind": "run-agent",
      "env": "OPENCODE_CONFIG_CONTENT",
      "extensionsOff": {
        "OPENCODE_PURE": "1"
      }
    },
    "credential": {
      "provider": "anthropic",
      "slot": "anthropic",
      "variables": [
        "ANTHROPIC_API_KEY"
      ]
    },
    "profile": {
      "models": {
        "low": null,
        "default": null,
        "high": null
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._-]*/[A-Za-z0-9][A-Za-z0-9._:/-]{0,240}$",
      "modelHint": "Use provider/model. An unset model holds runs at this tier."
    }
  },
  {
    "id": "cursor",
    "asking": {
      "kind": "run-home",
      "env": "CURSOR_CONFIG_DIR"
    },
    "credential": {
      "provider": "anthropic",
      "slot": "anthropic",
      "variables": [
        "ANTHROPIC_API_KEY"
      ]
    },
    "profile": {
      "models": {
        "low": null,
        "default": null,
        "high": null
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [],
      "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$",
      "modelHint": "Model selection is unavailable for this agent."
    }
  },
  {
    "id": "antigravity",
    "asking": {
      "kind": "unheld"
    },
    "credential": {
      "provider": "google",
      "slot": null,
      "variables": [
        "GEMINI_API_KEY"
      ]
    },
    "profile": {
      "models": {
        "low": null,
        "default": null,
        "high": null
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [],
      "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$",
      "modelHint": "Model selection is unavailable for this agent."
    }
  }
] as const;

/** The Deployment secret slots a harness's manifest declares as its own (`runner.credential.slot: own`), named after it. */
export const RUNNER_OWN_SLOTS = [
  {
    "name": "codex",
    "label": "Codex (OpenAI)"
  }
] as const;
