// AUTO-GENERATED by scripts/gen-hook-config.ts — DO NOT EDIT.

/** Each harness a worker runs, in the order a worker ranks them, as its manifest's `runner:` block declares it. */
export const RUNNER_HARNESSES = [
  {
    "id": "claude-code",
    "name": "Claude Code",
    "asking": {
      "kind": "native"
    },
    "credential": {
      "provider": "anthropic",
      "slot": "anthropic",
      "variables": [
        "CLAUDE_CODE_OAUTH_TOKEN",
        "ANTHROPIC_API_KEY"
      ],
      "accepts": [
        "subscription",
        "api-key"
      ]
    },
    "profile": {
      "models": {
        "low": "haiku",
        "default": "sonnet",
        "high": "opus"
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "modelPattern": "^(haiku|sonnet|opus|fable|claude-[A-Za-z0-9][A-Za-z0-9._-]{0,240})$",
      "modelHint": "Use haiku, sonnet, opus, fable, or a claude-* model ID.",
      "modelFamilies": [
        "haiku",
        "sonnet",
        "opus",
        "fable"
      ],
      "modelFamilyPrefix": "claude-"
    },
    "diagnostics": [
      {
        "code": "login_missing",
        "pattern": "\\bauthentication_(?:failed|error)\\b|failed to authenticate|invalid api key|api key is invalid|please run /login|not logged in|oauth token (?:has )?expired|\\b401\\b"
      },
      {
        "code": "rate_limited",
        "pattern": "\\brate[_ -]?limit|\\b429\\b|usage limit|too many requests"
      },
      {
        "code": "model_refused",
        "pattern": "\\bmodel\\b[^\\n]{0,80}\\b(?:not found|not available|does not exist|is not supported)\\b|invalid model|\\bmodel_not_found\\b"
      },
      {
        "code": "timed_out",
        "pattern": "\\btimed? ?out\\b|\\bETIMEDOUT\\b|\\btimeout\\b"
      }
    ]
  },
  {
    "id": "codex",
    "name": "Codex",
    "asking": {
      "kind": "sandbox"
    },
    "credential": {
      "provider": "openai",
      "slot": "codex",
      "variables": [
        "OPENAI_API_KEY"
      ]
    },
    "profile": {
      "models": {
        "low": null,
        "default": null,
        "high": null
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$",
      "modelHint": "Use a Codex model ID. An unset model holds runs at this tier."
    },
    "diagnostics": [
      {
        "code": "login_missing",
        "pattern": "\\b401 Unauthorized\\b|\\bunauthorized\\b|not logged in|codex login|missing (?:openai )?api key|invalid_api_key|incorrect api key|\\btoken (?:is |has )?expired"
      },
      {
        "code": "rate_limited",
        "pattern": "\\b429\\b|too many requests|rate[_ -]?limit|usage limit|\\bquota\\b"
      },
      {
        "code": "model_refused",
        "pattern": "\\bmodel\\b[^\\n]{0,80}\\b(?:not found|not supported|does not exist|not available|unsupported)\\b|\\bmodel_not_found\\b|unsupported model"
      },
      {
        "code": "timed_out",
        "pattern": "\\btimed? ?out\\b|\\bETIMEDOUT\\b|deadline exceeded|\\btimeout\\b"
      }
    ]
  },
  {
    "id": "opencode",
    "name": "OpenCode",
    "asking": {
      "kind": "run-agent",
      "env": "OPENCODE_CONFIG_CONTENT",
      "extensionsOff": {
        "OPENCODE_PURE": "1"
      }
    },
    "credential": {
      "provider": "anthropic",
      "slot": "anthropic",
      "variables": [
        "ANTHROPIC_API_KEY"
      ]
    },
    "profile": {
      "models": {
        "low": null,
        "default": null,
        "high": null
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._-]*/~?[A-Za-z0-9][A-Za-z0-9._:/-]{0,240}$",
      "modelHint": "Use provider/model. An unset model holds runs at this tier.",
      "providerAliasPattern": "^openrouter/~",
      "presets": [
        {
          "id": "openrouter-claude-latest",
          "provider": "openrouter",
          "label": "Newest Claude through OpenRouter",
          "description": "Haiku, Sonnet and Opus through OpenRouter, always the newest version.",
          "models": {
            "low": "openrouter/~anthropic/claude-haiku-latest",
            "default": "openrouter/~anthropic/claude-sonnet-latest",
            "high": "openrouter/~anthropic/claude-opus-latest"
          }
        }
      ]
    },
    "diagnostics": [
      {
        "code": "login_missing",
        "pattern": "ProviderAuthError|LoadAPIKeyError|api key is missing|\\bunauthorized\\b|\\b401\\b|not authenticated|authentication required"
      },
      {
        "code": "rate_limited",
        "pattern": "\\b429\\b|too many requests|rate[_ -]?limit|usage limit|\\bquota\\b"
      },
      {
        "code": "model_refused",
        "pattern": "ModelNotFound|\\bmodel\\b[^\\n]{0,80}\\b(?:not found|not supported|does not exist|not available)\\b"
      },
      {
        "code": "timed_out",
        "pattern": "\\btimed? ?out\\b|\\bETIMEDOUT\\b|\\btimeout\\b"
      }
    ]
  },
  {
    "id": "cursor",
    "name": "Cursor",
    "asking": {
      "kind": "run-home",
      "env": "CURSOR_CONFIG_DIR"
    },
    "credential": {
      "provider": "anthropic",
      "slot": "anthropic",
      "variables": [
        "ANTHROPIC_API_KEY"
      ]
    },
    "profile": {
      "models": {
        "low": null,
        "default": null,
        "high": null
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [],
      "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$",
      "modelHint": "Model selection is unavailable for this agent."
    },
    "diagnostics": [
      {
        "code": "login_missing",
        "pattern": "authentication required|not logged in|\\blogin\\b[^\\n]{0,40}\\brequired\\b|agent login|\\bunauthorized\\b|\\b401\\b"
      },
      {
        "code": "rate_limited",
        "pattern": "\\b429\\b|too many requests|rate[_ -]?limit|usage limit|\\bquota\\b"
      },
      {
        "code": "model_refused",
        "pattern": "cannot use this model|\\bmodel\\b[^\\n]{0,80}\\b(?:not found|not supported|does not exist|not available)\\b"
      },
      {
        "code": "timed_out",
        "pattern": "\\btimed? ?out\\b|\\bETIMEDOUT\\b|\\btimeout\\b"
      }
    ]
  },
  {
    "id": "antigravity",
    "name": "Google Antigravity",
    "asking": {
      "kind": "unheld"
    },
    "credential": {
      "provider": "google",
      "slot": null,
      "variables": [
        "GEMINI_API_KEY"
      ]
    },
    "profile": {
      "models": {
        "low": null,
        "default": null,
        "high": null
      },
      "efforts": {
        "low": "low",
        "default": "medium",
        "high": "high"
      },
      "allowedEfforts": [],
      "modelPattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$",
      "modelHint": "Model selection is unavailable for this agent."
    },
    "diagnostics": [
      {
        "code": "login_missing",
        "pattern": "\\bunauthenticated\\b|\\bunauthorized\\b|\\b401\\b|not logged in|authentication required"
      },
      {
        "code": "rate_limited",
        "pattern": "\\b429\\b|resource_exhausted|too many requests|rate[_ -]?limit|\\bquota\\b"
      },
      {
        "code": "model_refused",
        "pattern": "\\bmodel\\b[^\\n]{0,80}\\b(?:not found|not supported|does not exist|not available)\\b"
      },
      {
        "code": "timed_out",
        "pattern": "\\btimed? ?out\\b|\\bETIMEDOUT\\b|deadline exceeded|\\btimeout\\b"
      }
    ]
  }
] as const;

/** The Deployment secret slots a harness's manifest declares as its own (`runner.credential.slot: own`), named after it. */
export const RUNNER_OWN_SLOTS = [
  {
    "name": "codex",
    "label": "Codex (OpenAI)"
  }
] as const;
