// AUTO-GENERATED by scripts/gen-hook-config.ts — DO NOT EDIT.

/** What a step of each harness did, in a reader's words, by the tool or kind of call its step log names it by. */
export const STEP_WORDS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "claude-code": {
    "ToolSearch": "Looked up a tool",
    "TodoWrite": "Updated its to-do list"
  },
  "codex": {},
  "opencode": {
    "think": "Thought it through",
    "switch_mode": "Switched its mode"
  },
  "cursor": {
    "think": "Thought it through",
    "switch_mode": "Switched its mode"
  },
  "antigravity": {
    "think": "Thought it through",
    "switch_mode": "Switched its mode"
  }
};
