/*
 * AUTO-GENERATED by packages/myco/scripts/gen-plugin-bundle.ts — DO NOT EDIT.
 *
 * What a client lists a shipped skill by. Bodies are deliberately absent: this
 * module is bundled into the Cloudflare Worker, whose size ceiling is a free-tier
 * tripwire, and a skill body is served from the plugin that installed it.
 */

/** One shipped skill, as a caller chooses between them. */
export interface ShippedSkill {
  readonly name: string;
  readonly description: string;
  readonly when_to_use: string;
}

export const SHIPPED_SKILLS: readonly ShippedSkill[] = [
  {
    "name": "myco",
    "description": "Myco is this project's memory — the sessions that happened, the durable observations (spores) drawn from them, and the plans. It holds why the code is the way it is, which the code itself cannot show. Use it before a design decision, when debugging something non-obvious, when a structure looks arbitrary, when picking up work someone else started, and after learning something worth keeping.",
    "when_to_use": "Reach for Myco when the question is \"why\", not \"what\" — why this approach, what was tried before, what broke, what a subsystem is defending against. Also when the user says vault, spore, session, plan, prior decision, team knowledge or institutional memory; when you are about to repeat work another session may have done; and when you have just found a gotcha or made a decision worth saving."
  },
  {
    "name": "myco-handoff",
    "description": "Carry a session's working intention to another session or another agent. PREPARE compresses why we are here, what we are doing, the gotchas, the dead ends and the decisions already closed into a digest of at most 1500 tokens, saved on a Myco plan. RECEIVE takes that plan id, rehydrates the context, marks the referenced plans in progress, loads the suggested skills and resumes the work.",
    "when_to_use": "\"hand this off\", \"prepare a handoff\", \"continue this in a new session\", \"pick up where I left off\", \"pass this to another agent\" — and unprompted when context is running low and the work will continue elsewhere, or when the work has drifted far enough out of scope that a fresh session should restart it."
  },
  {
    "name": "myco-okf",
    "description": "Create or maintain an OKF-conformant project wiki — a portable, git-committed markdown knowledge base that lives in the repository rather than in Myco. Turns what Myco holds, the spores and sessions and plans, into human-readable documentation that ships with the code. Any agent can run the procedure; it needs nothing beyond the ordinary Myco tools.",
    "when_to_use": "\"create a wiki\", \"build a project wiki\", \"document this codebase as a wiki\", \"keep the wiki in sync with the code\", or any request naming OKF, the Open Knowledge Format, or a knowledge catalog."
  },
  {
    "name": "myco-outcome-tasks",
    "description": "Author and debug the tasks Myco's own agent runs. A task is one prompt with declared expected evidence, dispatched to a worker: no phases, no turn budget, no orchestrator. It declares the gate that admits it, the tools its run may call, its schedule if it has one, and how the server decides afterwards that it actually did the work. Getting those four declarations consistent is the whole job.",
    "when_to_use": "Use when adding a task to the catalogue, changing what a task may call, changing when it runs, or working out why a run never started, ended partial, or closed without doing anything. Also when a catalogue gate fails and the message names a task."
  },
  {
    "name": "myco-rules",
    "description": "Keep AGENTS.md minimal, durable and canonical across every agent that reads it. Adds, trims and audits project rules without letting the rules file decay into a dump of whatever was true last week.",
    "when_to_use": "\"add a project rule\", \"trim AGENTS.md\", \"audit our rules\", or whenever a rule is about to be written down and it is not obvious whether it belongs in AGENTS.md or in Myco as a spore."
  },
  {
    "name": "myco-server-debugging",
    "description": "Work out why a Myco deployment refused something, lost something, or stopped doing something. The server answers a caller's own fault as a terminal refusal carrying a named code, and its own faults as a retryable failure — telling those two apart is the first move in every investigation, because only one of them is worth retrying and only one of them is your bug.",
    "when_to_use": "Use when a deployment refuses a call, when sessions or events are not landing, when a scheduled job appears not to run, when a member cannot authenticate, or when someone reports that \"the server is broken\" without saying what it did. Also when reading server logs and needing to know what a code means."
  },
  {
    "name": "myco-server-provisioning",
    "description": "Provision, update, roll back and destroy the Cloudflare Deployment — the Worker front door — with `myco server <verb> --target cloudflare`. One verb, from artifacts the binary carries: no source checkout on the machine that deploys, and no container runtime anywhere.",
    "when_to_use": "Use for any Cloudflare provisioning or deploy work, for D1 migration ordering against a live Deployment, for the free-tier surface rule, when changing the Worker bundle the binary carries, and when debugging a wrangler failure during a deploy. Also read it before adding any binding to `wrangler.toml`."
  },
  {
    "name": "myco-settings",
    "description": "Change a Myco deployment's settings safely, and add a new setting correctly. Deployment settings are one tier with one writer: every change admits the leaf, authorizes the actor, checks the leaf's own rule, persists it with its actor, and re-arms whatever schedule it moved — in that order, in one module. Bypassing that path is how one of those five steps quietly goes missing.",
    "when_to_use": "Use when changing a deployment setting, adding a new one, working out why a setting was refused, or wondering whether a value belongs in the deployment's settings at all. Also when a setting appears to save and change nothing, or when a capability seems off for a project that never turned it off."
  },
  {
    "name": "myco-setup",
    "description": "Finish setting Myco up on this machine. The plugin alone gives you skills and the Myco tools; the binary adds session capture, plan capture, import and the worker. This skill checks what is present, installs the binary with the user's consent, signs in or redeems a join code, wires the agent's hooks and verifies the result — and names the outcome plainly when an install cannot proceed.",
    "when_to_use": "Use when no Myco context arrives at session start, when this project's sessions are not being recorded, when a Myco tool call is refused for want of a credential, or when the user says \"set up Myco\", \"install Myco\", \"connect me to our Myco deployment\" or \"why isn't my work being captured\"."
  }
];
