import { describe, it, expect } from 'bun:test';
import { Database } from 'bun:sqlite';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { migrationFileName, readSchemaVersion, renderMigrationFile, renderMigrationFiles } from '@myco-server-worker/db/migrate.js';
import { applySchemaSteps } from './helpers/migrate.js';
import { SCHEMA_STEPS, type SchemaStep } from '@myco-server-worker/db/schema.js';
import { SERVER_SCHEMA_VERSION } from '@myco-server-worker/constants.js';
import { MEMBER_TOKEN_TTL_MS } from '@myco-server-worker/auth/tokens.js';
import { sqliteD1 } from './helpers/d1.js';

const MIGRATIONS = fileURLToPath(new URL('../../packages/myco-server/worker/migrations/', import.meta.url));

/** sha256 of every migration file a deployed database's `d1_migrations` ledger already records. An applied file is frozen: the applier never re-runs it, so a schema change is a new step, never an edit of one of these. Shipping step n+1 adds one line here at delivery. */
const SHIPPED_MIGRATION_DIGESTS: Record<string, string> = {
  '0001_v1.sql': '999b696d37063feb2126cdd716f57e8a15c9a177c4204eae3101ff4926fdaa02',
  '0002_v2.sql': '9a8cee5f16d76d37f2997148525de27e9716b1997263a67f7f4fecc3499a3ea4',
  '0003_v3.sql': 'ff2773c613c61ecedcc9bbb236c739c43b1811ae89e1b89c7547a7ed9f7e741b',
  '0004_v4.sql': '2f1928b973df6fa87ad00ec56bde8ac461cc81aaf484b54641ac84cdf3e5e950',
};
const sha256 = (bytes: Buffer): string => createHash('sha256').update(bytes).digest('hex');

/** The schema of a database as `sqlite_master` rows, ordered; the version row is compared separately. */
const shape = (sqlite: Database) =>
  sqlite.query(`SELECT type, name, tbl_name, sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY type, name`).all();
const version = (sqlite: Database) => (sqlite.query(`SELECT value FROM schema_meta WHERE key='version'`).get() as any).value;
const fresh = () => { const s = new Database(':memory:'); s.exec('PRAGMA foreign_keys = ON'); return s; };

/** Tables and typed columns a step's statements create or add, by scanning the DDL text. */
function declaredColumns(steps: readonly SchemaStep[]): Map<string, Map<string, string>> {
  const sqlite = fresh();
  for (const step of steps) sqlite.exec(renderMigrationFile(step));
  const out = new Map<string, Map<string, string>>();
  for (const { name } of sqlite.query(`SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'`).all() as { name: string }[]) {
    const cols = new Map<string, string>();
    for (const c of sqlite.query(`PRAGMA table_info(${name})`).all() as { name: string; type: string }[]) cols.set(c.name, c.type);
    out.set(name, cols);
  }
  return out;
}

/** Applies one step the way `wrangler d1 migrations apply` does: statement by statement, stopping at the first failure. `Database.exec` on a whole file runs past a failing statement, so a file-at-once apply cannot stand in for the production applier. */
const step = (sqlite: Database, s: SchemaStep): void => { for (const statement of s.statements) sqlite.exec(statement); };

describe('versioned schema steps', () => {
  it('stamps its version as the last statement of every step, in ascending order from 1', () => {
    SCHEMA_STEPS.forEach((step, i) => {
      expect(step.version).toBe(i + 1);
      expect(step.statements[step.statements.length - 1]).toMatch(new RegExp(`^INSERT OR REPLACE INTO schema_meta \\(key, value\\) (VALUES \\('version', '${step.version}'\\)|SELECT 'version', '${step.version}' WHERE )`));
    });
    expect(SCHEMA_STEPS[SCHEMA_STEPS.length - 1].version).toBe(SERVER_SCHEMA_VERSION);
  });

  it('renders one numbered file per step with a generated-file banner, matching the committed migrations directory byte for byte', () => {
    const files = renderMigrationFiles();
    expect(files.map((f) => f.name)).toEqual(SCHEMA_STEPS.map(migrationFileName));
    expect(readdirSync(MIGRATIONS).filter((f) => f.endsWith('.sql')).sort()).toEqual(files.map((f) => f.name));
    for (const f of files) {
      expect(f.sql.startsWith('-- Generated by npm run migrations:emit from src/db/schema.ts')).toBe(true);
      expect(readFileSync(join(MIGRATIONS, f.name), 'utf8')).toBe(f.sql);
    }
  });

  it('keeps every shipped migration file byte-identical to its recorded digest, so an applied step cannot be edited in place and pass as a rendered file', () => {
    const shipped = Object.keys(SHIPPED_MIGRATION_DIGESTS);
    expect(shipped).toEqual(renderMigrationFiles().map((f) => f.name).slice(0, shipped.length));
    for (const [name, digest] of Object.entries(SHIPPED_MIGRATION_DIGESTS)) {
      expect({ name, digest: sha256(readFileSync(join(MIGRATIONS, name))) }).toEqual({ name, digest });
    }
  });

  it('converges: applied to a fresh database once or twice, or on top of a v1 or a v2 database, the schema is identical and the version is the build\'s', async () => {
    const once = fresh();
    await applySchemaSteps(sqliteD1(once));
    const twice = fresh();
    await applySchemaSteps(sqliteD1(twice));
    expect(await applySchemaSteps(sqliteD1(twice))).toEqual([]);
    const fromV1 = fresh();
    fromV1.exec(renderMigrationFile(SCHEMA_STEPS[0]));
    fromV1.query(`INSERT INTO projects (project_id, name, created_at) VALUES ('proj_1', 'one', 0)`).run();
    fromV1.query(`INSERT INTO member_tokens (id, project_id, machine_id, token_hash, expires_at, revoked_at, bytes_written) VALUES ('mt_1', 'proj_1', 'm', 'h', 1, NULL, 0)`).run();
    expect(await readSchemaVersion(sqliteD1(fromV1))).toBe(1);
    expect(await applySchemaSteps(sqliteD1(fromV1))).toEqual(SCHEMA_STEPS.slice(1).map((s) => s.version));
    const fromV2 = fresh();
    await applySchemaSteps(sqliteD1(fromV2), SCHEMA_STEPS.slice(0, 2));
    fromV2.query(`INSERT INTO projects (project_id, name, created_at) VALUES ('proj_1', 'one', 0)`).run();
    fromV2.query(`INSERT INTO member_tokens (id, project_id, machine_id, token_hash, expires_at, revoked_at, bytes_written) VALUES ('mt_v2', 'proj_1', 'm', 'h', ${MEMBER_TOKEN_TTL_MS + 5_000}, NULL, 7)`).run();
    expect(await readSchemaVersion(sqliteD1(fromV2))).toBe(2);
    expect(await applySchemaSteps(sqliteD1(fromV2))).toEqual(SCHEMA_STEPS.slice(2).map((s) => s.version));
    for (const db of [once, twice, fromV1, fromV2]) {
      expect(shape(db)).toEqual(shape(once));
      expect(version(db)).toBe(String(SERVER_SCHEMA_VERSION));
    }
    expect(fromV1.query(`SELECT project_id, name FROM projects`).all()).toEqual([{ project_id: 'proj_1', name: 'one' }]);
    expect(fromV1.query(`SELECT project_id FROM member_tokens`).all()).toEqual([{ project_id: 'proj_1' }]);
    expect(await readSchemaVersion(sqliteD1(fresh()))).toBe(0);
  });

  it('backfills every pre-v3 token as the root of its own lineage, started one TTL before it expires, and leaves predecessor and first use unset', async () => {
    const sqlite = fresh();
    await applySchemaSteps(sqliteD1(sqlite), SCHEMA_STEPS.slice(0, 2));
    sqlite.query(`INSERT INTO projects (project_id, name, created_at) VALUES ('proj_1', 'one', 0)`).run();
    sqlite.query(`INSERT INTO member_tokens (id, project_id, machine_id, token_hash, expires_at, revoked_at, bytes_written) VALUES ('mt_a', 'proj_1', 'm', 'ha', ${MEMBER_TOKEN_TTL_MS + 1_000}, NULL, 0), ('mt_b', 'proj_1', 'm', 'hb', ${MEMBER_TOKEN_TTL_MS + 2_000}, 5, 9)`).run();
    await applySchemaSteps(sqliteD1(sqlite));
    expect(sqlite.query(`SELECT id, predecessor_id, lineage_root, lineage_started_at, first_used_at, bytes_written FROM member_tokens ORDER BY id`).all()).toEqual([
      { id: 'mt_a', predecessor_id: null, lineage_root: 'mt_a', lineage_started_at: 1_000, first_used_at: null, bytes_written: 0 },
      { id: 'mt_b', predecessor_id: null, lineage_root: 'mt_b', lineage_started_at: 2_000, first_used_at: null, bytes_written: 9 },
    ]);
  });

  it('is expand-only from step 2 on: every step after 2 keeps every earlier table and column with the same type, and a table dropped by step 2 is one it creates itself or one whose rows it copied first', () => {
    for (let n = 2; n < SCHEMA_STEPS.length; n++) {
      const before = declaredColumns(SCHEMA_STEPS.slice(0, n));
      const after = declaredColumns(SCHEMA_STEPS.slice(0, n + 1));
      for (const [table, cols] of before) {
        expect(after.has(table)).toBe(true);
        for (const [col, type] of cols) expect({ table, col, type: after.get(table)!.get(col) }).toEqual({ table, col, type });
      }
      for (const s of SCHEMA_STEPS[n].statements) expect(s).not.toMatch(/\b(DROP|RENAME)\b/i);
    }
    const stepTwo = SCHEMA_STEPS[1].statements;
    stepTwo.forEach((s, i) => {
      const dropped = /^DROP TABLE (?:IF EXISTS )?(\w+)/i.exec(s);
      if (!dropped) return;
      const scratch = stepTwo.some((x) => new RegExp(`^CREATE TABLE (?:IF NOT EXISTS )?${dropped[1]}\\b`).test(x));
      const copied = stepTwo.slice(0, i).some((prev) => new RegExp(`INSERT INTO \\w+ .* FROM ${dropped[1]}\\b`, 'is').test(prev));
      expect({ statement: s, safe: scratch || copied }).toEqual({ statement: s, safe: true });
    });
  });

  it('aborts step 2 on an out-of-grammar project id, leaving the database at v1, and completes once the row is fixed', () => {
    const good = fresh();
    good.exec(renderMigrationFile(SCHEMA_STEPS[0]));
    good.query(`INSERT INTO projects (project_id, name, created_at) VALUES ('proj-1.ok', 'one', 0)`).run();
    step(good, SCHEMA_STEPS[1]);
    expect(version(good)).toBe('2');

    const bad = fresh();
    bad.exec(renderMigrationFile(SCHEMA_STEPS[0]));
    bad.query(`INSERT INTO projects (project_id, name, created_at) VALUES ('bad/id', 'one', 0)`).run();
    expect(() => step(bad, SCHEMA_STEPS[1])).toThrow(/CHECK constraint failed/);
    expect(version(bad)).toBe('1');

    bad.query(`UPDATE projects SET project_id = 'good.id' WHERE project_id = 'bad/id'`).run();
    step(bad, SCHEMA_STEPS[1]);
    expect(version(bad)).toBe('2');
    expect(bad.query(`SELECT COUNT(*) c FROM sqlite_master WHERE type='trigger'`).get()).toEqual({ c: 2 });
  });

  it('aborts step 2 on a v1 session whose machine identity cannot be backfilled, and completes once the row is repaired', () => {
    // Identity binding reads `sessions.machine_id`. A session left without one refuses every later write to itself,
    // and no member request can repair it, so the step stops rather than carry the row forward.
    const sqlite = fresh();
    sqlite.exec(renderMigrationFile(SCHEMA_STEPS[0]));
    sqlite.query(`INSERT INTO projects (project_id, name, created_at) VALUES ('proj_1', 'one', 0)`).run();
    sqlite.query(`INSERT INTO member_tokens (id, project_id, machine_id, token_hash, expires_at) VALUES ('mt_named', 'proj_1', 'machine_1', 'h1', 9)`).run();
    sqlite.query(`INSERT INTO member_tokens (id, project_id, machine_id, token_hash, expires_at) VALUES ('mt_anon', 'proj_1', NULL, 'h2', 9)`).run();
    sqlite.query(`INSERT INTO sessions (project_id, session_id, machine_id, created_by_token_id, first_received_at, last_received_at) VALUES ('proj_1', 'sess_ok', NULL, 'mt_named', 0, 0)`).run();
    sqlite.query(`INSERT INTO sessions (project_id, session_id, machine_id, created_by_token_id, first_received_at, last_received_at) VALUES ('proj_1', 'sess_orphan', NULL, 'mt_anon', 0, 0)`).run();

    // The guard runs ahead of every ADD COLUMN, so the aborted step leaves nothing behind and re-applies whole.
    expect(() => step(sqlite, SCHEMA_STEPS[1])).toThrow(/CHECK constraint failed/);
    expect(version(sqlite)).toBe('1');
    expect(sqlite.query(`SELECT COUNT(*) c FROM pragma_table_info('events') WHERE name = 'producer_adapter'`).get()).toEqual({ c: 0 });

    sqlite.query(`UPDATE sessions SET machine_id = 'machine_recovered' WHERE session_id = 'sess_orphan'`).run();
    step(sqlite, SCHEMA_STEPS[1]);
    expect(version(sqlite)).toBe('2');
    // The backfill carried the session whose token names a machine; the repair stands on the one it could not reach.
    expect(sqlite.query(`SELECT session_id, machine_id FROM sessions ORDER BY session_id`).all())
      .toEqual([{ session_id: 'sess_ok', machine_id: 'machine_1' }, { session_id: 'sess_orphan', machine_id: 'machine_recovered' }]);
  });

  it('applies the project-id grammar as a CHECK on every table created or rebuilt by step 2 that has a project_id column', () => {
    const sqlite = fresh();
    for (const f of renderMigrationFiles()) sqlite.exec(f.sql);
    const tables = (sqlite.query(`SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'`).all() as { name: string }[]).map((t) => t.name);
    const checked: string[] = [];
    for (const t of tables) {
      const cols = sqlite.query(`PRAGMA table_info(${t})`).all() as { name: string; type: string; notnull: number; dflt_value: string | null }[];
      if (!cols.some((c) => c.name === 'project_id')) continue;
      if (t === 'member_tokens' || t === 'sessions' || t === 'events') continue;
      const insert = (projectId: string) => {
        const names = cols.map((c) => c.name);
        const values = cols.map((c) => (c.name === 'project_id' ? `'${projectId}'` : c.type === 'INTEGER' ? '0' : `'x'`));
        sqlite.query(`INSERT INTO ${t} (${names.join(', ')}) VALUES (${values.join(', ')})`).run();
      };
      expect(() => insert('bad/id')).toThrow(/CHECK constraint failed/);
      expect(() => insert('a'.repeat(65))).toThrow(/CHECK constraint failed/);
      // `.` and `..` sit inside the character class but are path segments wherever a project id reaches one.
      expect(() => insert('.')).toThrow(/CHECK constraint failed/);
      expect(() => insert('..')).toThrow(/CHECK constraint failed/);
      expect(() => insert('ok.id-1_A')).not.toThrow();
      checked.push(t);
    }
    expect(checked.sort()).toEqual(['attachments', 'blob_reservations', 'blobs', 'plans', 'projects', 'prompt_batches', 'responses', 'tags', 'tool_calls', 'transcript_segments', 'transcripts']);
  });
});
