import { describe, it, expect } from 'bun:test';
import { Database } from 'bun:sqlite';
import { SCHEMA_DDL } from '@myco-server-worker/db/schema.js';
import { renderSchemaSql } from '@myco-server-worker/db/migrate.js';
import { MEMBER_TOKEN_BYTE_QUOTA, SERVER_SCHEMA_VERSION } from '@myco-server-worker/constants.js';

const table = (name: string) => SCHEMA_DDL.find((s) => new RegExp(`CREATE TABLE .*\\b${name}\\b`).test(s))!;

describe('server schema', () => {
  it('scopes sessions and events by project', () => {
    expect(table('sessions')).toMatch(/PRIMARY KEY \(project_id, session_id\)/);
    expect(table('events')).toMatch(/PRIMARY KEY \(project_id, event_id\)/);
  });

  it('attributes every write to a token', () => {
    expect(table('events')).toMatch(/token_id\s+TEXT NOT NULL/);
    expect(table('sessions')).toMatch(/created_by_token_id TEXT NOT NULL/);
  });

  it('records server receipt time next to caller time on events, and only server times on sessions', () => {
    expect(table('events')).toMatch(/created_at\s+INTEGER NOT NULL/);
    expect(table('events')).toMatch(/received_at\s+INTEGER NOT NULL/);
    expect(table('sessions')).toMatch(/first_received_at\s+INTEGER NOT NULL/);
    expect(table('sessions')).toMatch(/last_received_at\s+INTEGER NOT NULL/);
    expect(table('sessions')).not.toMatch(/started_at|updated_at|transport|injection_delivered/);
  });

  it('gives project_id referential identity and tracks token write volume', () => {
    expect(table('projects')).toBeDefined();
    expect(table('member_tokens')).toMatch(/REFERENCES projects/);
    expect(table('member_tokens')).toMatch(/bytes_written INTEGER NOT NULL DEFAULT 0/);
    expect(table('member_tokens')).toMatch(new RegExp(`CONSTRAINT member_tokens_quota CHECK \\(bytes_written <= ${MEMBER_TOKEN_BYTE_QUOTA}\\)`));
    expect(table('member_tokens')).not.toMatch(/last_seen_at/);
    expect(table('events')).toMatch(/envelope_hash TEXT NOT NULL/);
    expect(table('events')).toMatch(/channel\s+TEXT NOT NULL/);
  });

  it('is idempotent by construction', () => {
    for (const s of SCHEMA_DDL) expect(s).toMatch(/IF NOT EXISTS/);
  });

  it('renders into real SQLite with a generated-file banner and records the version last', () => {
    const sql = renderSchemaSql();
    expect(sql.startsWith('-- Generated by npm run schema:emit from src/db/schema.ts; do not edit.\n')).toBe(true);
    expect(sql.trimEnd().endsWith(`INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('version', '${SERVER_SCHEMA_VERSION}');`)).toBe(true);
    const sqlite = new Database(':memory:');
    sqlite.exec(sql);
    expect((sqlite.query(`SELECT value FROM schema_meta WHERE key='version'`).get() as any).value)
      .toBe(String(SERVER_SCHEMA_VERSION));
  });
});
