# Myco installer for Windows x64 — https://myco.sh
# Usage: irm https://myco.sh/install.ps1 | iex
# Fresh defaults choose 2.x stable, then beta, then alpha.
# Existing legacy machines keep 1.x updates until -Replace14.
# Existing and downloaded 1.x binaries are never executed by this installer.
# MYCO_CHANNEL (alpha/beta/stable) overrides the recorded install channel.
# Requires Windows PowerShell 5.1+.

[CmdletBinding()]
param(
    [string]$Channel = "",
    [switch]$Replace14,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$Repo = "goondocks-co/myco"
$MycoHome = if ($env:MYCO_HOME) { $env:MYCO_HOME } else { Join-Path $env:USERPROFILE '.myco' }
$BinDir = if ($env:MYCO_BIN_DIR) { $env:MYCO_BIN_DIR } else { Join-Path $env:LOCALAPPDATA 'Myco/bin' }
$Exe = Join-Path $BinDir 'myco.exe'
$Asset = "myco-windows-x64.exe"
$Marker = Join-Path $MycoHome 'install.json'
$SelfHostingGuide = "https://github.com/$Repo/blob/main/docs/self-hosting.md"
$Replace14 = $Replace14 -or $env:MYCO_REPLACE_LEGACY -eq '1'
$ChannelExplicit = $Channel -ne "" -or $null -ne $env:MYCO_CHANNEL
$ChannelAuto = $false
$InstallMarker = $null

# ---------------------------------------------------------------------------
# Architecture check — x64 only (AMD64 in Windows terms)
# ---------------------------------------------------------------------------
$arch = $env:PROCESSOR_ARCHITECTURE
# WOW64: 32-bit process on 64-bit OS — check the native arch
if ($env:PROCESSOR_ARCHITEW6432) { $arch = $env:PROCESSOR_ARCHITEW6432 }

if ($arch -eq "ARM64") {
    Write-Host "Myco does not support Windows on ARM (ARM64) at this time." -ForegroundColor Red
    Write-Host "  x64 native Windows is required." -ForegroundColor Red
    exit 1
}

if ($arch -ne "AMD64") {
    Write-Host "Unsupported processor architecture: $arch" -ForegroundColor Red
    Write-Host "  Myco requires a 64-bit (x64) Windows machine." -ForegroundColor Red
    exit 1
}

# ---------------------------------------------------------------------------
# Channel resolution
# ---------------------------------------------------------------------------
if (Test-Path $Marker) { $InstallMarker = Get-Content $Marker -Raw | ConvertFrom-Json }
if ($Channel -eq "") {
    if ($ChannelExplicit) { $Channel = $env:MYCO_CHANNEL }
    elseif ($InstallMarker) { $Channel = $InstallMarker.channel }
    else { $Channel = 'stable'; $ChannelAuto = $true }
}
if ($Channel -cnotin @('alpha', 'beta', 'stable')) {
    throw "Unknown channel '$Channel'. Use alpha, beta or stable."
}

# Ensure TLS 1.2 is enabled — PowerShell 5.1 on older Windows (pre-1709 / Server 2016)
# does not include it by default, causing SSL/TLS failures against api.github.com.
# -bor preserves existing protocols; this is a no-op on newer Windows.
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

Write-Host "Myco installer — windows-x64 / channel: $Channel" -ForegroundColor Cyan
Write-Host "Windows support is beta. Report issues at https://github.com/$Repo/issues" -ForegroundColor Yellow
Write-Host ""

# ---------------------------------------------------------------------------
# GitHub API helpers — token-aware, token never printed
# ---------------------------------------------------------------------------
function Get-AuthHeaders {
    $tok = if ($env:GITHUB_TOKEN) { $env:GITHUB_TOKEN } elseif ($env:GH_TOKEN) { $env:GH_TOKEN } else { "" }
    $h = @{
        'User-Agent' = 'myco-installer/goondocks-co/myco'
        'Accept'     = 'application/vnd.github+json'
    }
    if ($tok -ne "") { $h['Authorization'] = "Bearer $tok" }
    return $h
}

function Invoke-GhApi {
    param([string]$Url)
    $headers = Get-AuthHeaders
    try {
        $resp = Invoke-WebRequest -Uri $Url -Headers $headers -UseBasicParsing -ErrorAction Stop
        return $resp
    } catch {
        $status = $null
        if ($_.Exception.Response) { $status = [int]$_.Exception.Response.StatusCode }
        if ($status -eq 403 -or $status -eq 429) {
            Write-Host "GitHub API rate limit hit (HTTP $status)." -ForegroundColor Red
            Write-Host "  Set GITHUB_TOKEN (or GH_TOKEN) to a personal access token and retry:" -ForegroundColor Red
            Write-Host "    `$env:GITHUB_TOKEN='ghp_...' ; irm https://myco.sh/install.ps1 | iex" -ForegroundColor Red
            exit 1
        }
        Write-Host "GitHub API request failed: $_" -ForegroundColor Red
        exit 1
    }
}

function Invoke-GhDownload {
    param([string]$Url, [string]$OutFile)
    $headers = Get-AuthHeaders
    try {
        Invoke-WebRequest -Uri $Url -Headers $headers -OutFile $OutFile -UseBasicParsing -ErrorAction Stop
    } catch {
        Write-Host "Download failed from $Url : $_" -ForegroundColor Red
        exit 1
    }
}

# release-selector:start
# Generated by packages/myco/scripts/gen-release-selector.mjs from release-policy.mjs.
function Get-MycoReleaseKey {
    param([string]$Version)
    $match = [regex]::Match($Version, '^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(-(alpha|beta|rc)[.](0|[1-9][0-9]*))?$')
    if (-not $match.Success -or $match.Value -cne $Version) { return $null }
    $phase = if ($match.Groups[5].Success) { $match.Groups[5].Value } else { 'stable' }
    $ranks = @{ alpha = 1; beta = 2; rc = 3; stable = 4 }
    $key = @([double]$match.Groups[1].Value, [double]$match.Groups[2].Value, [double]$match.Groups[3].Value, $ranks[$phase], [double]$match.Groups[6].Value)
    if (@($key | Where-Object { $_ -gt 9007199254740991 }).Count) { return $null }
    return [PSCustomObject]@{ Phase = $phase; Key = $key }
}

function Compare-MycoReleaseKeys {
    param($Left, $Right)
    for ($i = 0; $i -lt 5; $i++) {
        if ($Left[$i] -ne $Right[$i]) { if ($Left[$i] -gt $Right[$i]) { return 1 } else { return -1 } }
    }
    return 0
}

function Select-MycoRelease {
    param([object[]]$Releases, [string]$Channel, [string]$CurrentVersion = '', [int]$MinMajor = 2, [int]$MaxMajor = 0)
    $allowed = @{ alpha = @('alpha', 'beta', 'stable'); beta = @('beta', 'stable'); stable = @('stable') }
    $best = $null
    $bestKey = $null
    foreach ($release in $Releases) {
        if ($release.draft -or $release.tag_name -cnotmatch '^myco/v') { continue }
        $version = $release.tag_name.Substring(6)
        $parsed = Get-MycoReleaseKey $version
        if (-not $parsed -or $parsed.Key[0] -lt $MinMajor -or ($MaxMajor -gt 0 -and $parsed.Key[0] -gt $MaxMajor)) { continue }
        if ($allowed[$Channel] -cnotcontains $parsed.Phase -or ($parsed.Phase -eq 'stable' -and $release.prerelease)) { continue }
        if (@($release.assets | Where-Object { $_.name -ceq $Asset }).Count -eq 0 -or @($release.assets | Where-Object { $_.name -ceq 'SHA256SUMS' }).Count -eq 0) { continue }
        if (-not $best -or (Compare-MycoReleaseKeys $parsed.Key $bestKey) -gt 0) { $best = $release.tag_name; $bestKey = $parsed.Key }
    }
    if ($best -and $CurrentVersion -and $CurrentVersion -cnotmatch '^0[.]0[.]0(-dev)?([+][0-9A-Za-z.-]+)?$') {
        $current = Get-MycoReleaseKey $CurrentVersion
        if (-not $current -or (Compare-MycoReleaseKeys $bestKey $current.Key) -lt 0) { return 'stay-put' }
    }
    return $best
}
# release-selector:end

function Invoke-MycoCommand {
    param([string]$File, [string]$Arguments, [string]$WorkingDirectory, [int]$TimeoutMilliseconds, [hashtable]$ChildEnvironment = @{})
    $process = New-Object System.Diagnostics.Process
    $started = $false
    try {
        $process.StartInfo.FileName = $File
        $process.StartInfo.Arguments = $Arguments
        $process.StartInfo.WorkingDirectory = $WorkingDirectory
        $process.StartInfo.UseShellExecute = $false
        $process.StartInfo.RedirectStandardOutput = $true
        $process.StartInfo.RedirectStandardError = $true
        foreach ($name in $ChildEnvironment.Keys) { $process.StartInfo.EnvironmentVariables[$name] = $ChildEnvironment[$name] }
        $started = $process.Start()
        $stdout = $process.StandardOutput.ReadToEndAsync()
        $stderr = $process.StandardError.ReadToEndAsync()
        if (-not $process.WaitForExit($TimeoutMilliseconds)) { throw 'Myco command exceeded its time limit.' }
        return [PSCustomObject]@{ ExitCode = $process.ExitCode; Output = $stdout.Result; Error = $stderr.Result }
    } finally {
        if ($started -and -not $process.HasExited) { $process.Kill(); $process.WaitForExit() }
        $process.Dispose()
    }
}

function Get-MycoFiles {
    param([string]$Pattern)
    try { Get-ChildItem $Pattern -ErrorAction Stop }
    catch [System.Management.Automation.ItemNotFoundException] { return }
}

# Classification order: hash-bound recorded version, then an identical versioned slot.
# Unversioned binaries are unknown legacy; dependency strings are not identity.
$CurrentVersion = ''
$Legacy = $false
if (Test-Path $Exe) {
    $hash = (Get-FileHash $Exe -Algorithm SHA256).Hash
    if ($InstallMarker.version -and $InstallMarker.bin -eq $Exe -and $InstallMarker.binary_sha256 -eq $hash) { $CurrentVersion = $InstallMarker.version }
    if (-not $CurrentVersion) {
        foreach ($slot in Get-MycoFiles (Join-Path $BinDir 'versions/*/myco.exe')) {
            $candidate = Split-Path (Split-Path $slot.FullName) -Leaf
            if ((Get-MycoReleaseKey $candidate) -and (Get-FileHash $slot.FullName -Algorithm SHA256).Hash -eq $hash) {
                $CurrentVersion = $candidate
                break
            }
        }
    }
    if ($CurrentVersion -and -not (Get-MycoReleaseKey $CurrentVersion) -and $CurrentVersion -cnotmatch '^0[.]0[.]0(-dev)?([+][0-9A-Za-z.-]+)?$') {
        throw 'Invalid installed version; nothing was installed.'
    }
    $Legacy = -not $CurrentVersion -or $CurrentVersion.StartsWith('1.')
}
if (-not $ChannelExplicit -and $CurrentVersion -and $InstallMarker.version -and $InstallMarker.version.StartsWith('1.') -and -not $CurrentVersion.StartsWith('1.')) {
    $Channel = if ($CurrentVersion -match '-alpha[.]') { 'alpha' } elseif ($CurrentVersion -match '-beta[.]') { 'beta' } else { 'stable' }
}
$MemberHome = (Test-Path (Join-Path $MycoHome 'member/cutover.json')) -or @(Get-MycoFiles (Join-Path $MycoHome 'member/deployments/*.json')).Count -gt 0
$LegacyVault = @(Get-MycoFiles (Join-Path $MycoHome 'groves/*/myco.db')).Count -gt 0 -or (Test-Path (Join-Path $MycoHome 'myco.db')) -or (Test-Path (Join-Path $MycoHome 'vault/myco.db'))
if (-not $CurrentVersion -and $LegacyVault -and -not $MemberHome) { $Legacy = $true }

Write-Host "Resolving $Channel release..." -ForegroundColor Cyan
$releases = @()
$MaxReleasePages = 100
for ($page = 1; $page -le $MaxReleasePages; $page++) {
    $resp = Invoke-GhApi -Url "https://api.github.com/repos/$Repo/releases?per_page=100&page=$page"
    $rows = @($resp.Content | ConvertFrom-Json)
    $releases += $rows
    if ($rows.Count -lt 100) { break }
    if ($page -eq $MaxReleasePages) { throw "GitHub release discovery exceeded $MaxReleasePages pages." }
}
$LegacyInstall = $Legacy -and -not $Replace14
if ($LegacyInstall) {
    $tag = Select-MycoRelease $releases $Channel $CurrentVersion 1 1
} else {
    if (-not $ChannelExplicit -and ($ChannelAuto -or $Legacy)) {
        foreach ($candidateChannel in @('stable', 'beta', 'alpha')) {
            $Channel = $candidateChannel
            $tag = Select-MycoRelease $releases $Channel $CurrentVersion
            if ($tag) { break }
        }
    } else { $tag = Select-MycoRelease $releases $Channel $CurrentVersion }
}
if ($tag -eq 'stay-put') { Write-Host "Newest eligible release is older than installed $CurrentVersion; staying put."; exit 0 }
if (-not $tag) { throw "No eligible Myco release found; nothing was installed. Check https://github.com/$Repo/releases" }
Write-Host "Found: $tag" -ForegroundColor Cyan

# ---------------------------------------------------------------------------
# Download binary + SHA256SUMS to a temp dir under LOCALAPPDATA\Myco\bin
# (same volume as destination — enables Move-Item without cross-device copy)
# ---------------------------------------------------------------------------
$encodedTag = $tag -replace '/', '%2F'
$dlBase     = "https://github.com/$Repo/releases/download/$encodedTag"

# Extract the bare semver (e.g. "1.2.3") from the tag (e.g. "myco/v1.2.3").
# The versioned slot retains the selected artifact for subsequent classification.
$Version    = $tag -replace '^myco/v', ''
$VersionDir = Join-Path $BinDir (Join-Path "versions" $Version)

if ($DryRun) {
    Write-Host "Dry run: would install $Asset ($Version) to $Exe; nothing was changed."
    exit 0
}

New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$tmpDir = Join-Path $BinDir (".myco-install-" + [System.IO.Path]::GetRandomFileName().Replace('.',''))
New-Item -ItemType Directory -Force -Path $tmpDir | Out-Null

$tmpExe  = Join-Path $tmpDir $Asset
$tmpSums = Join-Path $tmpDir "SHA256SUMS"

try {
    Write-Host "Downloading $Asset..." -ForegroundColor Cyan
    Invoke-GhDownload -Url "$dlBase/$Asset"      -OutFile $tmpExe
    Invoke-GhDownload -Url "$dlBase/SHA256SUMS"  -OutFile $tmpSums

    # -------------------------------------------------------------------------
    # Checksum verification — no bypass
    # -------------------------------------------------------------------------
    Write-Host "Verifying checksum..." -ForegroundColor Cyan

    $sumsContent = Get-Content $tmpSums -Raw
    $expected    = $null

    foreach ($line in ($sumsContent -split "`n")) {
        $line = $line.Trim()
        if ($line -eq "") { continue }
        # Format: "<hash>  <filename>" or "<hash> *<filename>"
        $parts = $line -split '\s+', 2
        if ($parts.Count -lt 2) { continue }
        $hashField = $parts[0].Trim()
        $nameField = $parts[1].Trim() -replace '^\*', ''
        if ($nameField -eq $Asset) {
            $expected = $hashField
            break
        }
    }

    if (-not $expected) {
        Write-Host "Asset '$Asset' not found in SHA256SUMS." -ForegroundColor Red
        exit 1
    }

    $actual = (Get-FileHash -Path $tmpExe -Algorithm SHA256).Hash

    if ($expected.ToUpper() -ne $actual.ToUpper()) {
        Write-Host "Checksum mismatch for $Asset!" -ForegroundColor Red
        Write-Host "  expected: $($expected.ToLower())" -ForegroundColor Red
        Write-Host "  got:      $($actual.ToLower())"  -ForegroundColor Red
        exit 1
    }

    Write-Host "Checksum verified." -ForegroundColor Green

    if (-not $LegacyInstall) {
        $probeHome = Join-Path $tmpDir 'probe-home'
        New-Item -ItemType Directory -Force -Path $probeHome | Out-Null
        $homes = @{ HOME = $probeHome; USERPROFILE = $probeHome; MYCO_HOME = (Join-Path $probeHome '.myco');
            CODEX_HOME = (Join-Path $probeHome '.codex'); CLAUDE_CONFIG_DIR = (Join-Path $probeHome '.claude');
            XDG_CONFIG_HOME = (Join-Path $probeHome '.config'); LOCALAPPDATA = (Join-Path $probeHome 'AppData/Local');
            MYCO_LAUNCH_AGENTS_DIR = (Join-Path $probeHome 'service-units'); MYCO_TEAM_HOME = (Join-Path $probeHome '.myco-team');
            TMPDIR = $probeHome; TEMP = $probeHome; TMP = $probeHome }
        $result = Invoke-MycoCommand $tmpExe '--version' $probeHome 30000 $homes
        if ($result.ExitCode -ne 0 -or $result.Output.Trim() -cne $Version) { throw 'The downloaded binary did not report the selected version; nothing was installed.' }
    }

    # -------------------------------------------------------------------------
    # Versioned placement + atomic stable copy
    #
    # Installed binary layout:
    #   %LOCALAPPDATA%\Myco\bin\versions\<bare-semver>\myco.exe  — versioned slot
    #   %LOCALAPPDATA%\Myco\bin\myco.exe                         — stable (current) slot
    #
    # Sequence: place in version dir → temp+rename to stable path.
    # The temp file lives under $BinDir (same volume) so the final rename is
    # atomic — a partial copy can never leave a broken stable binary.
    # -------------------------------------------------------------------------

    # Place the versioned copy
    New-Item -ItemType Directory -Force -Path $VersionDir | Out-Null
    $VersionExe = Join-Path $VersionDir "myco.exe"
    try {
        Copy-Item -Path $tmpExe -Destination $VersionExe -Force -ErrorAction Stop
    } catch {
        Write-Host "Failed to place versioned binary at $VersionExe : $_" -ForegroundColor Red
        exit 1
    }

    if ($Legacy -and -not $LegacyInstall) {
        [System.IO.File]::WriteAllText((Join-Path $VersionDir '.adopt-failed'), [DateTime]::UtcNow.ToString('o'))
    }

    # Atomic stable copy via temp+rename (same volume as $BinDir)
    $tmpStable = Join-Path $BinDir (".myco-stable-" + [System.IO.Path]::GetRandomFileName().Replace('.','') + ".exe")
    try {
        Copy-Item -Path $VersionExe -Destination $tmpStable -Force -ErrorAction Stop
        Move-Item -Path $tmpStable -Destination $Exe -Force -ErrorAction Stop
    } catch {
        if (Test-Path $tmpStable) { Remove-Item -Path $tmpStable -Force -ErrorAction SilentlyContinue }
        Write-Host "Failed to place stable binary at $Exe : $_" -ForegroundColor Red
        Write-Host "  Close processes using this Myco executable, then retry." -ForegroundColor Yellow
        exit 1
    }

} finally {
    # Clean up temp dir (best-effort)
    if (Test-Path $tmpDir) { Remove-Item -Path $tmpDir -Recurse -Force -ErrorAction SilentlyContinue }
}

# ---------------------------------------------------------------------------
# User PATH — idempotent
# ---------------------------------------------------------------------------
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (-not $userPath) { $userPath = "" }

$pathParts = $userPath -split ';' | Where-Object { $_ -ne "" }
$alreadyInPath = $pathParts | Where-Object { $_.TrimEnd('\') -ieq $BinDir.TrimEnd('\') }

if (-not $alreadyInPath) {
    $newPath = ($pathParts + $BinDir) -join ';'
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    Write-Host "Added $BinDir to your User PATH." -ForegroundColor Yellow
    Write-Host "  Restart your shell (or open a new terminal window) to use 'myco' directly." -ForegroundColor Yellow
} else {
    Write-Host "$BinDir is already on your PATH." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# Write install marker
# ---------------------------------------------------------------------------
$markerDir = Split-Path $Marker
New-Item -ItemType Directory -Force -Path $markerDir | Out-Null

$markerObj = [PSCustomObject]@{
    channel = $Channel
    source = 'curl'
    version = $Version
    binary_sha256 = (Get-FileHash $Exe -Algorithm SHA256).Hash.ToLower()
    bin = $Exe
    prerelease = $Version.Contains('-')
}
$markerTemp = Join-Path $markerDir ('.install.json-' + [System.IO.Path]::GetRandomFileName())
try {
    [System.IO.File]::WriteAllText($markerTemp, ($markerObj | ConvertTo-Json), (New-Object System.Text.UTF8Encoding($false)))
    Move-Item $markerTemp $Marker -Force
} finally {
    if (Test-Path $markerTemp) { Remove-Item $markerTemp -Force }
}

Write-Host ""
Write-Host "Myco $Version installed to $Exe" -ForegroundColor Green
if ($LegacyInstall) {
    Write-Host "  Myco 1.4 was updated; its existing service and capture configuration were preserved."
    Write-Host "  To install its managed service explicitly: myco service install"
    Write-Host "  Next, sign this machine in with the invite link an admin gave you:"
    Write-Host "    myco login <link>"
    Write-Host "  Or run your own Deployment with: myco server create"
} elseif ($Legacy) {
    Write-Host "  2.0 took 1.4's place. Nothing was moved or deleted."
    Write-Host "    myco login <your-myco-address>"
    Write-Host "    myco cutover --dry-run"
    Write-Host "    myco cutover"
} elseif ($MemberHome) {
    Write-Host "  Refreshing this joined machine's agents: myco member provision --refresh"
    try {
        $result = Invoke-MycoCommand $Exe 'member provision --refresh' $MycoHome 120000
        Write-Host $result.Output
        if ($result.Error) { Write-Host $result.Error }
        if ($result.ExitCode -ne 0) { throw "Myco exited with status $($result.ExitCode)." }
    } catch {
        Write-Warning "Refresh failed: $_ Run: myco member provision --refresh"
    }
} else {
    Write-Host "  Next, join your team's Deployment:"
    Write-Host "    myco login <your-myco-address>"
    Write-Host "  Or run your own server: $SelfHostingGuide"
}
Write-Host ""
